### ISSUE TITLE
디시인사이드 광고차단 문의드립니다.

### ISSUE THREAD

**Issue by Moore2512** [SlowMemory/List-KR#100]
http://gall.dcinside.com/board/lists/?id=stock_new2&page=

예시 링크입니다.

광고차단을 쓰면 그림으로 화면을 가리고, 그림을 가리면 팝업이 뜹니다.

gall.dcinside.com##DIV[style*="width:394px; height:294px; border:3px solid #000;"]

사용자 필터로 임시로 막긴 했으나, 필터업데이트로 원천봉쇄부탁합니다.

**Comment by bradly1** [comment]
DC인사이드 모바일 페이지에서도 뜨네요
M.dcinside.com 입니다

**Comment by SlowMemory** [comment]
우선 https://github.com/SlowMemory/List-KR/commit/678fc7bd744ab7f878be2258898f52ec4b6f6cca 와 https://github.com/SlowMemory/List-KR/commit/94debaa4d8a100f99f046f5f791decf358d7a608 를 통해 해결되었습니다. 확인 후 문제가 있다면 알려주시기를 부탁드립니다.

**Comment by bradly1** [comment]
지금은 광고 안뜨지만, 또 언제 뜰지는 모르겠네요

**Comment by SlowMemory** [comment]
오늘 업데이트로 광고차단 알림이 갤러리 이름 옆에 나타나도록 변경되었네요.

![dc_abdetect](https://cloud.githubusercontent.com/assets/19346646/25041906/9677c808-214e-11e7-980e-45d918b8eee0.png)

알림을 표시하는 요소의 id도 의미가 분명하고, 차단을 어렵게 하기 위한 시도가 일시적으로 중단된 것으로 보입니다. 위 업데이트에서 현재 알림을 차단하도록 조치하였습니다.

참고로 이렇게 무해한 광고차단 알림은, 모든 광고차단 프로그램이 사용하고 있다 해도 과언이 아닌 EasyList 필터의 [정책](https://easylist.to/2013/05/10/anti-adblock-guide-for-site-admins.html)에 따르면 차단 대상이 아닙니다.
