### ISSUE TITLE
디시인사이드 광고차단 문의

### ISSUE THREAD

**Issue by Meatbox** [SlowMemory/List-KR#101]
필터 업뎃 이후로 광고차단은 잘 되는데
마이너갤러리글을 조회하면 아무것도 안보이게 됩니다

**Comment by SlowMemory** [comment]
안녕하세요, 문제가 발생하는 페이지의 정확한 URL 알려주시면 감사드리겠습니다. 몇몇 마이너 갤러리 페이지를 열어보았지만 문제를 확인하지 못했습니다. 또 사용자 필터에 필터를 직접 추가하셨다면 충돌이 일어날 수 있으니 사용자 필터를 비활성화 하시고 확인 부탁드립니다.

**Comment by Meatbox** [comment]
설정 초기화하니 제대로 나오네요 꼬인게 있었나봅니다
