### ISSUE TITLE
네이버 메인 광고 미삭제

### ISSUE THREAD

**Issue by cjh980402** [SlowMemory/List-KR#102]
광고이미지 주소
https://ssl.pstatic.net/tveta/libs/1155/1155579/20170412152832-cOYM2wgb.jpg
https://ssl.pstatic.net/tveta/libs/1154/1154211/20170406134203-Ynrpi6gr_1.jpg
https://ssl.pstatic.net/tveta/libs/1156/1156998/20170410183627-s3jDEJDU.jpg

광고장면 스크린샷
![screenshot_20170412-161927](https://cloud.githubusercontent.com/assets/23624124/24945868/ecb85be2-1f9b-11e7-9dee-f162676343af.png)
![screenshot_20170412-161704](https://cloud.githubusercontent.com/assets/23624124/24945869/ecbb4aa0-1f9b-11e7-87f3-a2ce3020799e.png)
![screenshot_20170412-161658](https://cloud.githubusercontent.com/assets/23624124/24945870/ecbd40da-1f9b-11e7-93e3-ea655d59cd4f.png)

**Comment by SlowMemory** [comment]
해당 광고가 재현되지는 않지만, 차단되지 않은 얇은 광고 박스가 있어서 이를 차단하도록 업데이트 하였습니다.
도움이 되는지 확인 부탁드립니다.

글쓴님의 문제는 필터 문제가 아니라 "모바일 데이터를 사용할 때 ipv6 관련 설정을 체크해야 광고가 차단되는 경우" 가 아닐까 싶네요. 로우 레벨 설정에서 pref.vpn.ipv6.disable, pref.vpn.ipv6.bypass 중 하나를 활성화하셨을 때 문제가 해결될 수 있습니다. 직접 해 보시고 문제가 해결되는지 확인해주시면 감사드리겠습니다.

**Comment by cjh980402** [comment]
로우레벨에서 앞에거만 활성화했는데
뒤에거도 해보겠습니다.

**Comment by cjh980402** [comment]
둘 다 활성화했는데도 뜨네요...

**Comment by cjh980402** [comment]
광고가 바로 뜨는게 아니라 페이지 로딩 완료후
1초정도 후에 뜹니다

**Comment by cjh980402** [comment]
해당광고들이 wi-fi일때도 뜹니다

**Comment by todayhumor** [comment]
동일 페이지 모바일 웹에서는 차단이 잘 되서 해당 광고가 보이지 않는군요.
앱에 뭔가 있지 않을까요

**Comment by cjh980402** [comment]
저도 그게 좀 이상하긴 해요
컴퓨터에서 모바일버전 들어가면 차단이 잘 되는데...
