### ISSUE TITLE
디시인사이드 광고차단 팝업 뜨네요

### ISSUE THREAD

**Issue by park407** [SlowMemory/List-KR#103]
예제 http://gall.dcinside.com/board/lists/?id=stock_new2

dcinside.com##.pop_useinfo_layer + div:style(visibility:hidden)

일단 사용자필터에 위에 문구 추가해주니까 광고차단 팝업이 나오질 않습니다.

추가부탁드립니다.

**Comment by SlowMemory** [comment]
안녕하세요, 해당 요소의 `display` 스타일 값이 `none` 인지 외에도 `visibility` 값이 `hidden`인지 여부를 검사하는 로직이 추가되어 제안해주신 필터는 현재 작동하지 않습니다. 

관련 논의가 길어질 가능성이 있어, https://github.com/SlowMemory/List-KR/issues/100 이곳을 통해 논의를 이어가주시면 감사드리겠습니다.
