### ISSUE TITLE
특정이미지 차단은 어떻게하나요

### ISSUE THREAD

**Issue by cjh980402** [SlowMemory/List-KR#104]
https://ssl.pstatic.net/tveta/libs
로시작하는 광고이미지를 차단하려고해요

**Comment by SlowMemory** [comment]
`|https://ssl.pstatic.net/tveta/libs` 를 추가하시면 됩니다.

애드블록 플러스 필터 규칙은 기본적으로 필터의 문자열을 *포함* 하고 있는 주소로의 요청을 필터링합니다.
`|` 기호는 문자열의 시작과 끝을 나타내는 기호로, 위 규칙은 `https://ssl.pstatic.net/tveta/libs` 로 시작하는 주소를 차단하게 됩니다.
