### ISSUE TITLE
안녕하세요. 사이트 광고 차단이 되지 않아 글 남깁니다.

### ISSUE THREAD

**Issue by todayhumor** [SlowMemory/List-KR#105]
네이버 광고, 유튜브 광고, 일반 모바일웹 광고, 몇몇 앱의 광고는 잘 차단되었습니다.
그러나 웹사이트(모바일웹 포함) 몇개는 차단이 되질 않더라구요.

컴퓨터 사양 : 윈도우 8
브라우저 : 익스플로러 11

1. https://torrentwiz4.com

![default](https://cloud.githubusercontent.com/assets/27630015/25072164/04a381d6-2303-11e7-97e9-9a81429cbf24.JPG)

2. http://www.newscj.com/news/articleView.html?idxno=418604
![2](https://cloud.githubusercontent.com/assets/27630015/25072217/09c99492-2304-11e7-9134-cf4476d1e0c4.JPG)
빈칸이 AD라는 공간으로 남아있습니다.

**Comment by SlowMemory** [comment]
제보 감사합니다. 토렌트위즈 사이트는 최근도메인이 `torentwiz3.com`에서 바뀌어 차단되지 않은 것 같습니다. 위 두 commit에서 제보하신 광고를 차단하도록 업데이트 하였습니다.

**Comment by todayhumor** [comment]
감사합니다.
Torrentwiz4.com 방문해보니 다행히 광고는 뜨지 않는데 그곳에 빈공간, 여백이 남아있었습니다. 지금도 만족하지만 혹시나해서 답글 남겨 봅니다. 감사합니다
