### ISSUE TITLE
광고가 딱히 거슬리지는 않으나 이유가 궁금하네요

### ISSUE THREAD

**Issue by cjh980402** [SlowMemory/List-KR#106]
![screenshot_20170417-201054](https://cloud.githubusercontent.com/assets/23624124/25087476/388ce7ce-23aa-11e7-927b-7de08f682017.png)
![screenshot_20170417-201100](https://cloud.githubusercontent.com/assets/23624124/25087481/3e6f7238-23aa-11e7-985e-3aa56f643ba0.png)
![screenshot_20170417-201113](https://cloud.githubusercontent.com/assets/23624124/25087485/434ca29e-23aa-11e7-9d0e-c342ab41cf0f.png)
관련 설정도 다 해놓았는데 차단이 안 되네요 사용자필터에 따로 추가해도 안되고
브라우저 캐시삭제나 데이터 삭제도 2번정도 해봤습니다.

**Comment by SlowMemory** [comment]
Adguard 앱 자체의 버그가 아닐까 싶습니다.
[위키 글](https://github.com/SlowMemory/List-KR/wiki/Adguard-%EC%95%88%EB%93%9C%EB%A1%9C%EC%9D%B4%EB%93%9C-%EB%B2%84%EC%A0%84%EC%9D%98-%EB%A1%9C%EA%B7%B8%EB%A5%BC-%EC%96%BB%EB%8A%94-%EB%B2%95)을 참조하셔서, Full log를 올려주실 수 있으신가요?

사용하시는 안드로이드 버전, Adguard 버전, 사용하시는 브라우저 앱 관련 정보도 함께 부탁드립니다.

**Comment by cjh980402** [comment]
안드로이드 6.0.1 adguard 2.9.64 브라우저 크롬 57.0.2987.132
[adguard.zip](https://github.com/SlowMemory/List-KR/files/930330/adguard.zip)

**Comment by SlowMemory** [comment]
https 필터링을 활성화 하셨나요?

**Comment by cjh980402** [comment]
그거 활성화 하니까 안뜨네요ㄷㄷ...

**Comment by SlowMemory** [comment]
아.. 여하튼 문제가 해결되었다니 다행입니다. 
앞으로 GitHub 이슈 템플릿에 필요한 정보를 적는 란을 추가해야겠습니다.
