### ISSUE TITLE
앱 하단 광고 문의드립니다.

### ISSUE THREAD

**Issue by todayhumor** [SlowMemory/List-KR#107]
안녕하세요.
안드로이드 킷캣 지프로2 사용중이고, 앱 이름은 '성경책& 찬송가' 입니다.
개발자는 '전원주' 입니다.
해당 앱 최신 버전으로 업데이트 된 상태입니다.
성경 앱 내용 중 구약 및 신약을 들어가보면 하단에 광고가 나옵니다.
또한 찬송가를 악보형식으로 봤을 때도 (설정에서 가사만 보기-악보로 보기 있음) 하단 광고가 보입니다.
업데이트 요청 부탁드립니다.
++ 덧붙여서 앱을 종료하게 되면 전체화면으로 광고가 보여집니다.

![screenshot_2017-04-18-12-32-31](https://cloud.githubusercontent.com/assets/27630015/25113551/421f6e04-2433-11e7-8818-de2c0c905083.png)
![screenshot_2017-04-16-23-58-03](https://cloud.githubusercontent.com/assets/27630015/25113552/42c070d8-2433-11e7-8a55-e42c9300454a.png)

**Comment by SlowMemory** [comment]
http://www.clien.net/cs2/bbs/board.php?bo_table=cm_andro&wr_id=373336 에서 설명드린 문제와 관련 있습니다.
아마 Adguard 안드로이드 2.8 버전을 사용하고 계실 텐데요, 2.9 베타 버전으로 업데이트 하시면 광고가 나타나지 않을 겁니다.

**Comment by todayhumor** [comment]
업데이트 전이라 알려주신 링크의 첫 번째 방법인 DNS 요청 필터링 사용 설정을 통해 해결하였습니다.
감사합니다#
