### ISSUE TITLE
해당 사이트 광고차단 추가 부탁드립니다.

### ISSUE THREAD

**Issue by edoko** [SlowMemory/List-KR#108]
해당 블로그( http://frostfire.tistory.com )에서 adblock 등의 광고차단을 감지해서 포스팅이 표시되지 않는데
현재 임의로 제가 규칙을 추가해서 사용 중입니다.
아예 개발자님이 리스트에 추가해주시면 고맙겠습니다.

언제나 감사합니다^^.

@@||frostfire.tistory.com^$generichide

**Comment by SlowMemory** [comment]
제보 감사합니다. 필터 업데이트 후 확인 부탁드립니다.
