### ISSUE TITLE
사용자필터 질문드립니다

### ISSUE THREAD

**Issue by Meatbox** [SlowMemory/List-KR#109]
test1.test.com/test.php?test=xxx
으로 접속하려는걸
test2.test.com/test.php?test=xxx 로 접속하게 하려면 어떻게 해야하나요
xxx는 고정된 값이 아닌 변경되는 값입니다

**Comment by SlowMemory** [comment]
일반적인 페이지 리디렉션 기능은 Adguard 윈도우 버전 이슈 트래커에 따르면 6.3 버전에서 지원될 것이라 합니다.
하지만 현재도 실제 적용 환경에 따라 비슷한 효과를 낼 수는 있습니다. 

`test1.test.com/test.php?test=xxx` 이 페이지 주소라면,

```
test1.test.com#%#AG_onLoad(function(){window.location.href=window.location.href.replace("test1.test.com", "test2.test.com")});
```

이미지 등 페이지에서 추가로 로드하는 리소스의 주소라면,
```
||test.com/$replace=/test1\.test\.com\//test2.test.com/
```
을 사용하여 페이지의 모든 test1.test.com를 포함하는 링크를 test2.test.com으로 바꿀 수 있습니다.

replace 규칙을 사용할 시 주의할 점은, 첫 `/`과 두번째 `/` 사이의 문자열은 정규표현식으로 취급되므로 `.` 등 일부 문자 앞에 `\`를 붙여야 하는 것과, 두 번째 `/` 과 세 번째 `/` 사이의 문자열은 정규표현식이 아닌 문자열 자체로 취급된다는 점이 있습니다.
위와 같은 replace 규칙은 원하지 않는 요소까지 바꿀 가능성이 있습니다. 보다 안전한 규칙은 실제 규칙을 적용하고자 하는 상황에 맞게 따로 작성되어야 할 것입니다.

**Comment by Meatbox** [comment]
답변감사합니다
