### ISSUE TITLE
List-KR 적용후 G마켓 구매하기 버튼이 안먹힙니다.

### ISSUE THREAD

**Issue by hnhr1995** [SlowMemory/List-KR#110]
List-KR 을 킨 상태로 G마켓에서 물건을 구매하려 했으나
구매하기 버튼을 눌러도 주문확인 페이지로 넘어가지 않습니다.
List-KR 을 해제하고 난 후에는 정상적으로 주문확인 페이지로 넘어가는 걸 확인했고요.

현재 Windows 10 PC 환경에서 크롬을 쓰고 있고 버전은 57.0.2987.133 입니다.

현재 활성화된 필터는 영어 필터, 스파이웨어 필터, 소셜미디어 필터, Annoyance 필터, 일본 필터, Adguard DNS 필터, EasyList China, 그리고 List-KR 입니다.

혹시 이외에 다른 궁금한점 있으신가요.

**Comment by SlowMemory** [comment]
https://github.com/SlowMemory/List-KR/commit/72c515dbc98d3a52b45e0eac89526ac34ce7d972 에서 해결되었습니다. 필터 업데이트 후 확인 부탁드립니다.
