### ISSUE TITLE
옥션티켓 제보

### ISSUE THREAD

**Issue by Meatbox** [SlowMemory/List-KR#111]
http://ticketgen.auction.co.kr/VIP/32346.html
위 링크에서 로그인 후 예매하기를 누르면 잘못된 파라미터라고 뜹니다
애드가드를 사용안함으로 설정하면 제대로 되구요

http://i.imgur.com/0sNSTyp.png

**Comment by SlowMemory** [comment]
제보 감사합니다. 문제가 되는 규칙을 제거하였습니다.
