### ISSUE TITLE
안녕하세요. 앱 광고 차단 문의 드립니다.

### ISSUE THREAD

**Issue by todayhumor** [SlowMemory/List-KR#112]
안드로이드 킷캣 지프로2 입니다.

1. '마루' 라는 뷰어 앱입니다. 
이 앱을 실행하면 먼저 아래와 같은 광고창이 하나 뜹니다.

![screenshot_2017-04-24-22-51-56](https://cloud.githubusercontent.com/assets/27630015/25369339/1f8fbd72-29be-11e7-9325-e5a4699f4b96.png)
![screenshot_2017-04-24-22-51-15](https://cloud.githubusercontent.com/assets/27630015/25369338/1f8b8b76-29be-11e7-88b8-955421df3077.png)

그러나 Adguard 내 설정 - 앱관리 메뉴에서는 이렇다할 이상점은 찾기 어려웠습니다.
![screenshot_2017-04-24-22-53-30](https://cloud.githubusercontent.com/assets/27630015/25369407/a91860bc-29be-11e7-8849-ac20bb70c603.png)

2. '올원페이' (NH모바일 앱카드) 는 Adguard를 실행중에 결제가 되지 않더라구요. Adguard 메인 화면 보호 중지 버튼을 눌러야 실행이 되던데, 이 부분은 설정 - 앱관리 - 필터링 체크 해제 하면 해결 되는거겠지요?

3. 백그라운드 데이터 사용이 많은 편이던데, 외출시에는 데이터를 끌 수 없으니(최소한 카톡, 길찾기 등 사용) 보호모드를 사용안해야 하는건가요? 아니면 휴대폰 설정 - 데이터 - 백그라운드 사용제한을 걸어둬야할까요?
 
![screenshot_2017-04-25-13-01-45](https://cloud.githubusercontent.com/assets/27630015/25369419/b97fc0ee-29be-11e7-9855-b7bb75a65768.png)
![screenshot_2017-04-25-13-01-19](https://cloud.githubusercontent.com/assets/27630015/25369418/b97aedee-29be-11e7-891d-8673b5397d4b.png)

**Comment by bradly1** [comment]
1번 문제에 대해서 광고 링크를 찾아보려고 했지만, 저도 못찾겠네요... 
List-KR 담당자분이 해달라고 adguard log 올립니다 ㅠㅠ 
https://1drv.ms/u/s!ApWoXpwTlSjLkh60jNp2ncIq25B1

**Comment by SlowMemory** [comment]
1. 앱의 캐시를 삭제해 보시고 Adguard를 최신 베타 버전으로 업데이트 하신 후 문제가 재현되는지 확인해보세요. 제 기기에서는 재현이 되지 않습니다.
 2. ssl 문제로 보입니다. 앱 관리 메뉴에서 '올원페이' 앱을 'HTTPS 필터링' 에서 제외해 보세요. 해당 문제를 Adguard 팀에 제보하였으며 향후 업데이트에서 https 필터링 예외 목록에 포함될 듯 합니다.
 3. VPN 모드를 사용하고 계시다면, 다른 앱의 백그라운드 데이터 사용량이 Adguard가 사용한 것으로 잡히는 것입니다. Adguard 자체는 업데이트 체크, 라이센스 체크 정도의 용도로만 데이터를 사용하는 것으로 알고 있습니다.

**Comment by todayhumor** [comment]
말씀해주신대로 1번 문제 해결했습니다. 2번도 제외한 상태에서 문제 해결 하였습니다. 비슷한 네트워크 오류 생기는 앱들에 대해 같은 방법으로 해결 가능할 것 같습니다.
3번도 안심하고 백그라운드에서 쓰려고 합니다. 감사합니다.
