### ISSUE TITLE
디시인사이드 공앱 차단 문의

### ISSUE THREAD

**Issue by Meatbox** [SlowMemory/List-KR#115]
1.8.8 업데이트 이후로 앱내
게시판 상단, 하단 광고
종료시에 팝업광고가 뜹니다

json.dcinside.com/App/app_ad_setting.php
의 주소가
json.dcinside.com/json0/app_ad_setting.php로 변경되서 
||json.dcinside.com/json0/app_ad_setting.php^ 이걸 사용자필터에 추가했는데
게시판 상단, 하단 광고는 안뜨는데 종료시 광고가 뜨네요

**Comment by SlowMemory** [comment]
제보 감사합니다. 우선 업데이트된 주소를 차단하도록 업데이트 하였습니다.
앱 내 광고는 재현이 되지 않습니다. 
 - 사용하고 계신 Adguard 버전을 알려주세요.
 - 디시인사이드 앱의 캐시를 삭제하신 후 광고가 차단되는지 확인해 보세요.
