### ISSUE TITLE
안녕하세요 웹사이트 광고 차단 문의드립니다.

### ISSUE THREAD

**Issue by todayhumor** [SlowMemory/List-KR#117]
컴퓨터 사양 : 윈도우 8
브라우저 : 익스플로러 11
사용자입니다.

링크 주소를 매번 업데이트 해야하나보군요. 어떤 패턴으로는 해결이 어려운가 봅니다.
그럼 잘 부탁드립니다. 

1. https://m.torrentkim10.net/bc.php?bo_table=torrent_variety&wr_id=839394
m.torrentkim10.net 에서 상세 페이지(위의 링크와 같은)에 들어가면 중간에 배너가 있습니다.
pc 버전으로 잘 차단 중인데도 보이는군요.

![1](https://cloud.githubusercontent.com/assets/27630015/25553514/15832afa-2cf0-11e7-8c53-6c764fc56bd9.JPG)

![default](https://cloud.githubusercontent.com/assets/27630015/25553506/d3fc70a0-2cef-11e7-80cc-943e7ecada4b.JPG)

2. http://www.torrentgum.net/
양쪽 사이드바 + 팝업 광고 하나 뜨는 것 같습니다.
![2](https://cloud.githubusercontent.com/assets/27630015/25553505/d3ac7b4a-2cef-11e7-94f5-c4871864ceea.JPG)

**Comment by SlowMemory** [comment]
제보 감사합니다. 위 커밋에서 제보해주신 광고를 차단하도록 업데이트 하였으니 확인 부탁드립니다.
>링크 주소를 매번 업데이트 해야하나보군요. 어떤 패턴으로는 해결이 어려운가 봅니다.
제보해주신 광고들은 (이미 차단하고 있는)광고사를 통한 것이 아니라 토렌트 사이트 측에서 타 업체와 제휴하여 자체적으로 등록한 배너 이미지이며 이런 경우 대개 그 사이트만을 위한 차단 규칙이 필요합니다.

**Comment by todayhumor** [comment]
감사합니다. 2번 사이트 잘 제거되어 나옵니다. 1번사이트는 피시에서 저 링크 그대로 들어가서 그런지 아직 보이더군요. 그래도 감사합니다!
