### ISSUE TITLE
네이버 웹툰 광고차단 요청합니다

### ISSUE THREAD

**Issue by bradly1** [SlowMemory/List-KR#118]
모바일웹, 어플, PC웹 전부 광고가 뜹니다 
웹툰 제일 마지막 부분에 광고가 있습니다
http://m.comic.naver.com/webtoon/detail.nhn?titleId=20853&no=1089&week=tue&listPage=1

**Comment by SlowMemory** [comment]
제보 감사합니다. 해당 광고를 차단하는 필터를 추가하였으니 필터 업데이트 후 확인 부탁드립니다.
