### ISSUE TITLE
다음 카페 웹페이지에 문제있습니다. 

### ISSUE THREAD

**Issue by bradly1** [SlowMemory/List-KR#119]
![default](https://cloud.githubusercontent.com/assets/6886994/25730407/718dd2ce-3177-11e7-86d9-dc1aaee6b6b0.png)

여기 빨간색으로 표시해놓은 부분의 JS가 전부 제대로 실행되지 않습니다. 
Adguard 6.2.357.1887 버전을 사용하고 있습니다.

**Comment by SlowMemory** [comment]
문제를 좀 더 자세히 설명해주세요. 제 측에서는 특별한 문제를 발견하지 못했습니다.
문제가 발생하는 페이지의 주소, 사용 중이신 필터 목록, 문제를 관찰하기 위한 행동을 스텝 바이 스텝으로 설명해주세요.

**Comment by bradly1** [comment]
저기서 자주가는 카페나 내소식, 내카페, 쪽지 기능이 제대로 동작하지 않습니다. 그러나 Adguard를 종료하면 제대로 사용이 가능하네요.
adguard 6.2.357.1887 버전을 사용하고 있으며, List-KR 외에 영어필터, 소셜미디어, easylist, adblock warning remove list를 사용하고 있습니다. 
문제 발생 페이지 주소는 top.cafe.daum.net 이며 재현 영상은 아래 youtube 링크입니다.,
https://youtu.be/58tLSVA8fDI

**Comment by bradly1** [comment]
지금 다시 확인해보니 문제가 없네요..
죄송합니다..
