### ISSUE TITLE
몇 가지 제보합니다

### ISSUE THREAD

**Issue by WingsK** [SlowMemory/List-KR#120]
안녕하세요. 항상 감사하게 사용하고 있습니다.

1. 크몽 광고 관리 부분
https://kmong.com/seller/order_advertisement_gig
https://kmong.com/seller/advertisement_history
회원이 아닐 경우 접근이 불가능한 페이지입니다만, 차단되어야 할 광고가 아니라, 해당 사이트 내부적으로 광고를 구매하고, 관리하는 부분입니다. 현재 접급은 가능하지만, 일부 버튼들이 작동하지 않고 있습니다.

2. 고파스
고려대 재학생 및 졸업생 커뮤니티입니다.

koreapas.com##DIV:nth-child(11) > TABLE:first-child > TBODY > TR > TD:nth-child(2) > A:last-child > IMG
koreapas.com##DIV:nth-child(11) > TABLE:first-child > TBODY > TR > TD:last-child > A:last-child > IMG
메인 페이지의 중앙 배너 2개가 차단되는 규칙입니다.

koreapas.com##DIV:nth-child(9) > TABLE:first-child > TBODY > TR:nth-child(2) > TD:last-child > A:last-child > IMG
koreapas.com##DIV:nth-child(10) > DIV:nth-child(2) > DIV:last-child > A:last-child > IMG
상단 배너 차단 규칙입니다.

3. 클리앙
오늘 개편이 이루어졌습니다.
https://www.clien.net/service/
광고는 표시되지 않으나 광고 영역이라는 안내가 자리를 차지하고 있습니다.

**Comment by SlowMemory** [comment]
제보 감사드립니다.

 1. 일부 이미지 파일이 잘못 차단되는 것을 확인하여 이를 허용하도록 업데이트 하였습니다. 버튼이 동작하지 않는 현상은 무엇을 말씀하시는지 이해가 어렵습니다. 증상을 보다 자세히 설명해주시면 감사하겠습니다.

 1. 해당 사이트에서 광고 배너를 koreapas.com/bbs/no_unicorn 경로에 저장하고 있는 듯하여 이를 차단하도록 업데이트 하였습니다. 또한 https://www.koreapas.com/bbs/view.php?id=kfc&no=31801 페이지에서 fuckAdBlock이 사용되는 것을 확인하여 이를 무력화하도록 조치하였습니다.

 1. 클리앙 사이트의 광고는 최근 몇 차례 업데이트하여 차단하였습니다.

다른 제보 사항이 있으시다면 언제든 알려주세요.
