### ISSUE TITLE
크몽 관련 재문의 드립니다

### ISSUE THREAD

**Issue by WingsK** [SlowMemory/List-KR#122]
안녕하세요.

1.0.2.77 버전 기준으로, 이전에 문의드렸던 크몽 광고 부분이 정상적으로 작동하지 않습니다.

https://kmong.com/seller/order_advertisement_gig

위 페이지에서 서비스 선택과 광고기간 선택 리스트가 차단되는 듯 합니다.

그리고, 혹 MLBPark 좌측 사이드바의 광고성 컨텐츠들은 차단하지 않은 것이 방침인가요...??

**Comment by WingsK** [comment]
추가로, 아래 페이지의 좌측 사이드바 배너가 차단이 되지 않고 있습니다.
http://www.cooln.kr/bbs/38/1112027

**Comment by SlowMemory** [comment]
위 커밋에서 크몽 사이트 문제는 해결되었습니다.
쿨엔조이 웹사이트의 배너는 제 측에서는 나타나지 않습니다. 차단되지 않은 광고를 표시한 스크린샷을 올려주실 수 있으신가요?

**Comment by WingsK** [comment]
쿨엔조이 사이드 바의 배너는 간헐적으로 나타나는 것 같습니다. 아래 규칙으로 차단 가능한 것으로 보이고요.
cooln.kr###jb-sidebar-right
![2](https://cloud.githubusercontent.com/assets/28503484/25993279/7209995e-3744-11e7-8fac-0af329de9fb8.png)

**Comment by SlowMemory** [comment]
해당 배너는 이미 차단하고 있습니다. 제보자님께서 사용하시는 브라우저의 캐시 문제로 추정됩니다. 광고차단을 자주 껐다 켜시는 경우 이와 같은 문제가 발생할 수 있습니다.

브라우저의 캐시를 삭제하시고 확인 부탁드립니다. 여전히 광고가 나타나신다면 광고가 나타날 때의 페이지 html 코드를 올려주시면 확인해 보겠습니다.
