### ISSUE TITLE
광고 차단 문의 드립니다. 

### ISSUE THREAD

**Issue by McGorty** [SlowMemory/List-KR#123]
http://mlbpark.donga.com/mp/b.php?b=bullpen

사이트 하단 검색창 밑에 광고가 제거되고 나서 가로형태의 긴 막대 형태의 빈공간이 생기는데요. 
크게 눈에는 안 띄지만 부탁 드려봅니다. 

mlbpark.donga.com###container > DIV.contents:nth-child(2) > DIV.left_cont:first-child > DIV:nth-child(5)
이거 추가하면 없어지는데 게시글 클릭하면 여전히 하단 검색창 밑에 긴 막대 형태의 빈공간이  생기네요.
그리고 게시글 클릭하면 본문과 댓글 사이에도 광고 제거되면서 막대 형태의 공간이 있습니다.

추가로 http://zipbogo.net/ 이 사이트에서 광고가 아닌 항목이 제거되는 부분이 있습니다.
로그인 하고 다운로드 게시판(ex- http://www.zipbogo.net/cdsb/board.php?board=newmovie) 들어가면 왼쪽 사이드 바에 "토렌트 자료실 분류"라고 게시판 목록이 있는데 이걸 없애버립니다.<br>
<img src="http://i.imgur.com/PGVd2nk.png">
adguard 미적용 화면<br><br>
<img src="http://i.imgur.com/BwdtEun.png">
adguard  적용 화면<br><br>
mybogo.net,zipbogo.net##.sidebar > ul > li:nth-of-type(2) 

필터에서 이 부분이 문제인 것 같습니다. 메인화면이나 다른 게시판에서는 "보고보고 광고문의" 항목이  li:nth-of-type(2)에 해당 돼서 정상적으로 삭제되는데 다운로드 게시판에 들어가면 "토렌트 자료실 분류" 항목이 li:nth-of-type(2)에 해당 돼서 삭제 되는 것 같습니다.  "보고보고 광고문의"항목은  다운로드 게시판에서  li:nth-of-type(3)에 해당되고요. 

다운로드 게시판은 로그인 하지 않으면 보이지 않고 접근 불가능합니다. 게시판 접근 못 하셔서 수정하기 힘드시면 계정 정보 알려 드리겠습니다.

**Comment by SlowMemory** [comment]
제보 감사합니다. 위 두 커밋에서 제보해주신 문제를 반영하였습니다. 필터 업데이트 후 확인 부탁드립니다.

**Comment by McGorty** [comment]
감사합니다. 요청드린 2건 모두 잘 작동합니다. 근데 필터 업데이트 후 보고보고 다운로드 게시판 클릭하거나 새로고침 하면 왼쪽 사이드바에 있는 "보고보고 광고문의" 항목이 로딩 돼서 화면에 나타났다가 순식간에 사라지는데 원천적으로 로딩 안 되게 할 순 없을까요? 혹시나 해서 인터넷 사용기록, 쿠키도 삭제해봤는데 화면에 나타났다가 0.1초 후 사라지네요. 
 제 시스템 환경은 윈도우7 sp1 64bit,  크롬 58.0.3029.110 (64-bit), 윈도우 adguard 6.1.331.1732 사용 중입니다.

**Comment by SlowMemory** [comment]
요소가 늦게 사라지는 현상은 `:has` 선택자의 polyfill의 성능 문제입니다. 원천적으로 Adguard에서 사용하는 polyfill의 성능이 향상되어야 해결됩니다.

'보고보고 광고문의' 페이지 요소를 다른 요소와 구분해주는 특징이 없기 때문에 `:has` 선택자를 사용하지 않으려면 `nth-of-child` 가상 클래스 등을 사용해야 하는데, 이는 의도하지 않은 요소를 차단할 가능성이 높습니다.

이와 같은 방법이 가능할지는 추후 시간이 되는 대로 확인해 보겠습니다.
