### ISSUE TITLE
[재문의] 넷스루 - 자사 웹로그분석 스크립트의 List-KR 필터 목록에 포함된 건

### ISSUE THREAD

**Issue by sung-uk** [SlowMemory/List-KR#124]
관련이슈: #113 , #114 

안녕하세요 넷스루입니다.

국문으로 코멘트를 남기시는 것을 확인 후 국문으로 작성합니다. 말씀하신 정책에 관해서는 한 명의 인터넷 사용자로써 저희도 충분히 공감하고 있습니다. 저희가 고객사에 제공하는 스크립트들은 모두 Google Analytics에서 제공하는 스크립트와 매우 동일한 형식의 스크립트임을 먼저 공유 드립니다.

몇 가지 궁금한 부분이 있어 여쭈어봅니다. GA측에서는 analytics.js 가 List-KR에 등록되어있는 것을 인지하고 SlowMemory 담당자님께 필터목록에서의 제외를 요청한 이력이 있는지 궁금합니다. 만약 있었다면, 저희와 같은 이유로 Reject를 하셨는지요?

혹시 없었다면, 향후 GA측의 필터 제외 요청이 있을 경우 이에 대해 어떻게 대응하실 예정이신지 여쭙고 싶습니다.

답변에 시간을 할애해주셔서 감사 드립니다.

-넷스루

**Comment by SlowMemory** [comment]
analytics.js는 List-KR에 등록되어 있지 않습니다. Google Analytics 등 전 세계적으로 광범위하게 사용되는 사용자 정보 수집 리소스는 EasyPrivacy등에서 이미 차단하고 있어, List-KR에서 차단하지 않습니다.

List-KR에는 특정 사이트에서 https://www.google-analytics.com/analytics.js 를 차단 해제하는 규칙이 일부 등록되어 있는데, 이는 EasyPrivacy 등과 함께 사용할 때 국내의 특정 사이트가 사용 불능이 되는 문제를 해결하기 위함입니다.

현재까지 다른 필터 제외 요청은 없었으며, 필터 제외 요청을 받는 경우 앞서 코멘트에서 언급한 기준에 따라, 특정 리소스가 실제로 사용자 정보를 수집하는 데 사용되는지, 차단될 시 사이트의 주 기능에 영향을 미치는지를 참고하여 필터에 반영할 계획입니다.

**Comment by sung-uk** [comment]
안녕하십니까 넷스루 입니다. 
답변 적어주신 부분은 잘 확인하였습니다. 

Google Analytics의 경우 무료로 서비스를 제공하는 정책을 사요하고 있기에 유상 고객보다
무상으로 사용하는 고객사가 많습니다. 
그리고 스크립트를 통해서 수집된 데이터를 실사용자가 아닌 Google에서 수집을 하기 때문에 자사의 서비스 정책과는 다른 부분이 있구요.

자사의 경우에는 100% 유상 서비스 고객사이며, 
 - 스크립트를 통해 수집된 데이터를 자사가 수집하는 것이 아닌 
 - 해당 솔루션을 유상으로 구매한 고객(개인이 아닌 기업들)이 고객사 사이트에 접속항 방문자의 기록을
   고객의 IDC 내 통계 분석 서버로 데이터를 저장을 하고 있는 상황입니다. 

따라서 SlowMemory 리스트에 포함된 자사 관련 TEXT 로 인해
고객(기업) 자체적으로 수집하는 로그데이터가 누락되는 상황이 발생하기에 자사가 요청한 TEXT 제거 사안은 현재 시급한 이슈이며 빠른 제거를 요청 합니다. 

이 안을 자사에서도 요청을 하고 있지만 유상으로 구매한 고객(기업)에서도 제거를 요청하고 있으며
답변에 따라 해당 기업에서 공식적인 대응이 갈수도 있는 점을 공유 드립니다. 

그럼 빠른 답변을 요청 합니다.

**Comment by 8weemfoa0v** [comment]
github.com이 해외 기업이고, 그 기업의 서버에 텍스트 파일을 올려놓은것에 대하여 어떤 "공식적인 대응"을 하실건지 궁금하네요.

EasyPrivacy 같은 다른 트랙킹 리스트에 넷스루가 포함되어도 이런식으로 대응하실지 궁금하기도 하구요.

**Comment by SlowMemory** [comment]
넷스루 담당자님께,

귀사가 제공하는 서비스에 대한 설명은 잘 확인하였습니다.

귀사의 서비스가 유상으로 제공되며 사용자 정보가 귀사가 아닌 귀사 고객사의 소유라는 점을 말씀하셨는데, 귀사는 고객에게 계약관계에 따라 서비스를 제공할 뿐이고 사용자가 귀사(또는 그 고객)에 자신의 정보를 제공해야 할 의무는 전혀 없습니다. 사용자의 정보는 귀사(또는 그 고객)가 마땅히 소유해야 할 재산이 아닙니다.

오히려 대부분 사용자는 자신의 정보가 자신의 정보가 수집된다는 사실을 모른 채 웹 브라우징을 하게 되고, 일부 업체는 이러한 사실을 이용하여 대다수의 사용자가 직접 알게 된다면 꺼림칙할 정도의 정보 수집을 하고 있는 실정입니다.

사용자가 네트워크 차단 툴을 사용하여 이러한 정보 수집을 막는 것은 사용자가 자신의 컴퓨터라는 사적 영역에서 행사하는 정당한 행위입니다. 귀사가 사용자 정보를 수집하는 데 영향을 미치는 일부 텍스트를 본인이 시급히 삭제해야 할 어떠한 의무도 없습니다.

또한, 본인이 필터를 관리하지 않더라도 오픈소스 라이센스에 따라 누구나 데이터베이스를 포크하여 관리할 수 있으며, 본인은 필터를 관리하며 어떠한 금전적 이익도 얻고 있지 않다는 점을 말씀드립니다.

그럼 제 입장에 대한 답변이 되었길 바랍니다. List-KR 필터에 관심을 두어 주신 것에 대해 감사드리며 귀사의 발전을 기원합니다.
