### ISSUE TITLE
크롬에서 클리앙 모바일 버전이 정상적으로 작동하지 않습니다.

### ISSUE THREAD

**Issue by escart0312** [SlowMemory/List-KR#125]
안녕하세요

얼마전 클리앙 개편으로 인해 업데이트 해주셨다고 하셨는데,
list-kr 2017.5.12 버전인데도 여전히 차단되지 않고 있는 부분이 있습니다.

1. 모바일 버전의 광고는 거의 차단되었으나 틀이 비어서 떠있습니다.
(전체적으로 틀이 다 남아있네요. 첫페이지와 글을 들어갔을때 뜨는 광고틀이 다 그대로 보입니다)
2. 작성글과 댓글 사이의 파워링크AD는 차단이 되지 않고 그대로 보여집니다.

PC버전은 아주 잘됩니다. 
항상 감사합니다.

**Comment by SlowMemory** [comment]
사용하시는 Adguard의 버그로 추정됩니다. [위키 글](https://github.com/SlowMemory/List-KR/wiki/Adguard-%EC%95%88%EB%93%9C%EB%A1%9C%EC%9D%B4%EB%93%9C-%EB%B2%84%EC%A0%84%EC%9D%98-%EB%A1%9C%EA%B7%B8%EB%A5%BC-%EC%96%BB%EB%8A%94-%EB%B2%95) 을 참고하셔서 Full log를 올려주세요.

**Comment by SlowMemory** [comment]
며칠 전 짧게 답을 달았습니다만, 다시 확인해보니 HTTPS 필터링을 활성화하지 않으셨을 때의 증상과 유사하네요.
HTTPS 필터링을 활성화 하셨는지 확인 부탁드리며, 이미 활성화 체크 되어있더라도, `https 비활성화 후 앱 메인 화면에서 보호 중지 후 활성화 -> https 필터링 활성화 후 앱 메인 화면에서 보호 중지 후 활성화` 를 하신 뒤 공백이 사라지는지 확인 부탁드립니다.
