### ISSUE TITLE
보안카드+ 어플 광고 차단이 안됩니다.

### ISSUE THREAD

**Issue by foelfoel** [SlowMemory/List-KR#126]
'보안카드+' 확인 - https://play.google.com/store/apps/details?id=jjong.kim.securitycard_m

하단광고가 없어지지 않는데.. 혹시 개선 가능할까요?

**Comment by SlowMemory** [comment]
"거주 국가에서 사용할 수 없는 항목" 이라고 나오네요 -_-..
구글링해도 apk가 안 나오는데, 혹시 apk를 추출해서 보내주실 수 있으신가요?

**Comment by foelfoel** [comment]
https://www.dropbox.com/s/yaqtacaen4ytv61/base.apk?dl=0

**Comment by foelfoel** [comment]
https://drive.google.com/file/d/0B92PK-kGovThWW5XN1JXakFoOXc/view?usp=drivesdk

이걸로 다운 받으세요

**Comment by SlowMemory** [comment]
안녕하세요, 올려주신 apk를 설치하여 테스트하였습니다. 그런데 제 측에서는 광고가 나타나지 않으며 구글 광고만 차단되는 것으로 나타납니다.
 * https 필터링을 활성화 하셨는지,
 * 시스템 앱 중 수동으로 필터링을 해제하신 앱이 있는지
확인 부탁드립니다.
