### ISSUE TITLE
커뮤니티의 광고가 묘하게 차단됩니다.

### ISSUE THREAD

**Issue by dldh** [SlowMemory/List-KR#127]
안녕하세요.

부끄럽습니다만 아무튼 종종 들리는 커뮤니티의 광고가 있던 자리에 회색칸이 남게 되어 글을 적습니다.

일단 제가 해본바, 광고 차단에서 '단순화된 도메인 네임 필터'를 체크하게 되면 저 회색 칸이 생기고

해당 필터를 해제하게 되면 회색칸이 없어지는 것을 확인했습니다. 

(다만 회색칸이 차지했던 곳만큼 공란이 생깁니다)

모쪼록 확인 한 번 부탁드리겠습니다.

(애드가드 ver 2.9.70 // 안드로이드 7.0 // 삼성인터넷)

사이트 주소 :  http://nsbu.co.kr/bbs/board.php?bo_table=ggolit

**Comment by SlowMemory** [comment]
제보 감사합니다. 위 커밋에서 빈칸을 차단하도록 업데이트 하였습니다. 약 1시간 후 필터를 업데이트 하신 후 확인 부탁드립니다.
