### ISSUE TITLE
네이버TV 재생에러 뜹니다. 

### ISSUE THREAD

**Issue by bradly1** [SlowMemory/List-KR#128]
네트워크 상태가 원할하지 않다면서 재생이 안되네요. 
PC버전 adguard 를 사용하고 있고, 같이 사용하는 필터는 영어필터 뿐입니다.

**Comment by SlowMemory** [comment]
EasyList에 최근에 추가된 규칙으로 인한 오류인 듯 합니다. 현재는 해결된 듯 합니다. 
필터 업데이트 후 확인 부탁드립니다.

**Comment by bradly1** [comment]
http://tv.naver.com/v/1343037
재생해보면 광고가 뜹니다.

**Comment by bradly1** [comment]
http://tv.naver.com/v/1343037
재생해보면 광고가 뜹니다.
또한, 카카오TV 의 경우, 재생 자체가 되지 않네요..

**Comment by SlowMemory** [comment]
제보 감사합니다. 차단되지 않은 광고 서버를 추가하였으며 그 외 tv캐스트 관련 오래된 규칙을 업데이트 하였습니다. 필터 업데이트 후 문제가 해결되었는지 확인 부탁드립니다.
카카오 TV는 재생되지 않는 동영상을 확인할 수 있는 url을 알려주실 수 있으신가요?

**Comment by bradly1** [comment]
http://tv.naver.com/v/1695392
네이버 TV 이 링크도 재생 에러가 뜨네요..

똑같은 영상을 카카오 TV에서 검색해서 볼때는 재생이 안됩니다
http://tv.kakao.com/channel/2653158/cliplink/356222440

**Comment by bradly1** [comment]
![image](https://cloud.githubusercontent.com/assets/6886994/26234313/ac91a224-3c9e-11e7-8ada-7fc43a76c792.png)
List-KR 은 최신버전이라고 하네요

**Comment by SlowMemory** [comment]
'EasyList' 필터를 사용하고 계신가요? EasyList 에서는 아직 문제가 고쳐지지 않은 것 같습니다. 만약 EasyList를 사용하지 않고 계신데도 문제가 발생한다면 사용하고 계신 필터 목록을 알려주시면 문제를 재현하는 데 도움이 될 것 같습니다.

**Comment by bradly1** [comment]
1. 스파이웨어 필터
2. 소셜미디어 필터
3. annoyance 필터
4. 모바일 광고 필터
5. easy privacy
6. adblock warning remove list
7. List-KR 
이렇게 사용하고 있습니다.

**Comment by SlowMemory** [comment]
언급하신 필터만으로 문제가 재현되지 않습니다. 다른 필터를 추가로 사용하고 계신 것이 아닌가 싶은데요, 사용하고 계신 필터 목록을 다시 한번 확인해주시길 부탁드리며, 혹시 '단순화된 도메인 네임 필터' 를 사용하고 계신지도 확인 부탁드립니다.

List-KR 은 영어 필터 또는 EasyList와 같이 사용하도록 만들어졌습니다. 이 둘 중 하나를 사용하지 않을 경우 한국 사이트에서도 차단되지 않은 광고가 있을 수 있습니다.

**Comment by bradly1** [comment]
단순화된 도메인 네임 필터를 끄니까 제대로 사용이 가능하네요.
