### ISSUE TITLE
안녕하세요. 사이트 광고 차단 부탁드립니다.

### ISSUE THREAD

**Issue by todayhumor** [SlowMemory/List-KR#129]
윈도우 8 및 익스플로러 11 사용중입니다.

1. https://www.cucudas.com/ 내의 특정 게시판마다 조금씩 다른 형태의 광고가 있는 것을 확인했습니다.
주로 게시물 바디 영역 최상단, 오른쪽 사이드 바,  바디 영역 최하단 으로 보입니다.

https://www.cucudas.com/bbs/board.php?bo_table=humor2&wr_id=461228

![2](https://cloud.githubusercontent.com/assets/27630015/26187710/ea7a5d98-3bd5-11e7-95d5-cba8bfbffe76.JPG)

2.  http://www.ppomppu.co.kr/zboard/zboard.php?id=freeboard  에서 "이니스프리"로 검색했을 경우 하단에 광고가 뜨더라구요. 평소엔 뜨지 않습니다.

http://www.ppomppu.co.kr/zboard/zboard.php?id=freeboard&page_num=30&category=&search_type=sub_memo&keyword=%C0%CC%B4%CF%BD%BA%C7%C1%B8%AE

![default](https://cloud.githubusercontent.com/assets/27630015/26187757/3254671c-3bd6-11e7-8ff4-4e3d538eea7e.JPG)

그럼 잘 부탁드리겠습니다.

**Comment by todayhumor** [comment]
혹시 가능하시면 댓글에 있는 곳도 차단 부탁드리겠습니다. 우측 사이드바와 본문 상단에 있습니다.

https://torrenthaja.com/bbs/board.php?bo_table=torrent_movie

![default](https://cloud.githubusercontent.com/assets/27630015/26275075/91c6e60c-3d93-11e7-99ed-edfc6ca1e384.JPG)

**Comment by SlowMemory** [comment]
안녕하세요, 제보해주신 사항들을 반영하였습니다. 필터 업데이트 후 확인 부탁드립니다.
