### ISSUE TITLE
네이버tv 재생오류 뜹니다.

### ISSUE THREAD

**Issue by SHxXxJ** [SlowMemory/List-KR#131]
http://i.imgur.com/F8mJg6r.png
http://i.imgur.com/0041qbr.png
설정한 필터는 위 사진과 같구요.
http://i.imgur.com/ZT9UTo3.png
이렇게 안틀어집니다. 업데이트도 한 상태구요 뭐가 문제일까요.
참고로 아이패드로 확인햇습니다.

**Comment by SHxXxJ** [comment]
https://i.imgur.com/7nO7nq6.png
확인해보니까 필터가 업데이트가 안된것같네요...
근데 업데이트해도 최신으로 안되는데 어플자체 문제인걸까요?

**Comment by SlowMemory** [comment]
안녕하세요,

Adguard PRO 앱을 사용하시는 것으로 보아, 해당 앱의 DNS 기능을 이용하고 계신 것이 아닌가 싶습니다.
이번 네이버tv 이슈가 EasyList의 규칙 때문에 발생했는데, Adguard DNS 서버는 EasyList에서 자동으로 차단할 도메인을 추출하여 적용하기 때문에 이로 인해 네이버tv 동영상 서버가 차단되었을 수 있습니다. 이에 대해 제보해놓은 상태입니다.

DNS 기능을 사용 중지하시면 문제가 해결되는지 확인 부탁드립니다.

**Comment by SHxXxJ** [comment]
예 말씀대로 dns 기능쓰고 있으며
이번엔 list kr를 제외한 모든 필터를 비활성화하고 dns도 비활성화하고 사파리만 적용시켯습니다만
http://i.imgur.com/3lC99Lo.png
사진과같이 오류도 안뜨고 검은화면만 나오네요

**Comment by SHxXxJ** [comment]
ilstkr포함한 모든 필터 끄면 잘됩니다...
얼마전까지만해도 잘됫는데 어디서 꼬인건지 모르겟네요.

**Comment by SHxXxJ** [comment]
참고로 안드로이드 adguard와 윈도우 뮤블럭은 잘되는데...ios만 말썽이네요

**Comment by SHxXxJ** [comment]
전 안드로이드에선 문제없는데
아이패드에서 말썽이네요

**Comment by SlowMemory** [comment]
필터 업데이트를 한번 더 하신 뒤 확인 부탁드리며, 여전히 문제가 발생하신다면 '단순화된 도메인 네임 필터' 를 비활성화 하시고 테스트 해주세요.

iOS 에서 사용하실 때 '사파리 필터' 는 언제나 활성화 되어있어야 합니다.

**Comment by SHxXxJ** [comment]
해결되었습니다.
감사합니다
