### ISSUE TITLE
blockadblock 차단

### ISSUE THREAD

**Issue by lkl089** [SlowMemory/List-KR#132]
https://anigod.com

http://kirito.tistory.com/entry/%EC%95%A0%EB%8B%88%EA%B0%93-%EA%B4%91%EA%B3%A0-%EC%B0%A8%EB%8B%A8%ED%95%98%EA%B8%B0

이 블로그에 올라와 있던 필터랑 lisk-kr 사용하면서 잘쓰고있었는데 오늘 들어가보니 
![default](https://cloud.githubusercontent.com/assets/20037318/26281212/c133c0fc-3e2b-11e7-9701-837d9f126c24.PNG)이런게 나오면서 막히네요
모바일에서는 안뜹니다

**Comment by SlowMemory** [comment]
제보 감사합니다. 약 1시간 뒤 필터 업데이트 후 문제가 해결되었는지 확인 부탁드립니다.

**Comment by lkl089** [comment]
빠른답변 감사합니다.
사용자 필터 해제하니 저 알림은 안뜨고 하단 광고창이 하나 생겼네요/
![default](https://cloud.githubusercontent.com/assets/20037318/26281786/93e14ba4-3e3c-11e7-93be-3b95a99b10c7.PNG)
그리고 메인 페이지에서 첫 클릭시 새창 광고창이 뜹니다.

**Comment by lkl089** [comment]
+ deeppanda 주소가 여러개네요
끝자리는 .net, .org, .io, .com이돌림되네요
blog.deeppanda.*
blog.deepanda.*
blog0.deeppanda.*
blog.deepanda.*

**Comment by SlowMemory** [comment]
deeppanda 도메인마다 실제 사용되는지 사용할 수 있는 링크를 올려주실 수 있으신가요?
또 어떤 광고차단 소프트웨어를 사용하시는지 알 수 있을까요?

**Comment by lkl089** [comment]
adguard 사용중입니다

blog.deepanda.org/ads/blog
blog.deepanda.io/ads/blog
blog.deepanda.net/ads/blog
blog.deepanda.com/ads/blog //현재는 502오류 뜨네요
blog.deeppanda.org/ads/blog
blog.deeppanda.io/ads/blog
blog.deeppanda.net/ads/blog
blog.deeppanda.com/ads/blog
//

blog0.deepanda.com/ads/blog

현재 광고로 쓰이고 있는 도메인은 이정도인거같네요

**Comment by lkl089** [comment]
위 페이지 안에서 빈공간으로 표시되거나 서버에 대한 요청이 확장 프로그램에 의해 차단되었습니다. 라고 나오는 요소들입니다

###aswift_0
###aswift_1
###aswift_2
###realssp_aahqfcn4umw00001_9146
###realssp_aahqfcn4umw00001_9147

**Comment by SlowMemory** [comment]
우선 말씀하신 deeppanda 도메인들을 필터에 추가하였습니다.
과거에 사용되던 gryfindor.com 도메인은 이제 더 이상 사용되지 않고 있는지 아시나요?

영어 필터와 사용해도 팝업이 뜨지 않아야 하며,

List-KR 필터를 adguard에서 사용하시면 adguard 서버에서 캐싱된 버전을 사용하시기 때문에, 이 repository에서 업데이트 되었더라도 적용되는데 1시간 정도 걸릴 수 있습니다.

위 커밋의 변경 사항을 직접 적용하셔서 테스트해 주시거나, 1시간 뒤 필터 업데이트를 체크하시고 확인해 주세요. 감사합니다.

**Comment by lkl089** [comment]
네 몇개월전부터 gryfindor.com도메인으로는 접속되지 않았네요
변경된 필터목록 적용하고 접속하니 본문 글,팝업,blockadblock모두 차단됐습니다

귀중한 주말 시간 내주셔서 감사합니다
