### ISSUE TITLE
blockadblock 차단

### ISSUE THREAD

**Issue by parksueng** [SlowMemory/List-KR#133]
https://anigod.com/
페이지에서 통과되는 페이지와 통과되지 않는 페이지가 있습니다.

![1](https://cloud.githubusercontent.com/assets/28855928/26295092/16f5c558-3f03-11e7-82a5-2f85bd01ba1f.png)
![2](https://cloud.githubusercontent.com/assets/28855928/26295100/1be3f274-3f03-11e7-9b2f-1b24542fefaf.png)

이 전 글은 확인했습니다!! 확인 후 업데이트도 완료 후 들어갔지만
통과되는 글과 통과되지 않는 글이 있었습니다.
![3](https://cloud.githubusercontent.com/assets/28855928/26295149/645ceaa6-3f03-11e7-8fa3-2a2085f2c8d4.png)

**Comment by lkl089** [comment]
deepanda.org
deepanda.io
deepanda.net
deepanda.com
==deepanda(추가안됨)

deeppanda.org
deeppanda.io
deeppanda.net
deeppanda.com
==deeppanda(추가됨)

추가된 소스들 다시한번 보니 deeppanda 도메인만 추가되있고 deepanda는 추가가 안되있네요

+@@/js/ads.js^$domain=anigod.com|deeppanda.com|deeppanda.io|deeppanda.net|deeppanda.org|kflix.tv|netmics.com

**Comment by SlowMemory** [comment]
제보 감사합니다. deepanda 도메인도 마찬가지로 추가하였습니다. 확인 부탁드립니다.

**Comment by parksueng** [comment]
넵넵 정상적으로 작동합니다!!감사합니다
