### ISSUE TITLE
동영상 재생 싸이트 광고/애드블럭 차단

### ISSUE THREAD

**Issue by nskzhd** [SlowMemory/List-KR#134]
https://vidlox.tv/embed-xalcu00o1m3r.html 
모바일에서 접속 시에 애드블럭을 꺼달라는 메세지가 뜨는데.. 끄지 않고 재생 할 수 없는지 궁금합니다.

https://estream.to/embed-qd8i530we0w6.html
이 링크는 pc에서는 광고나 팝업 없이 재생이 되는데..
모바일로 들어가면 광고 팝업이 여러개 뜹니다. 11번가앱이 자동으로 실행되기도 하구요.
차단 부탁드려봅니다.

**Comment by SlowMemory** [comment]
* 어떤 광고차단 프로그램을 사용하고 계신가요?
 * 어떤 필터를 사용하고 계신가요?

제 기기에서 모바일 Adguard 앱 사용시에는 애드블럭을 꺼달라는 메세지나 팝업 광고가 뜨지 않습니다.

**Comment by nskzhd** [comment]
안드로이드 애드가드 프리미엄 사용중입니다.
필터는 english, spyware, social media, annoyances, mobile ads, list-kr 사용중이고, https필터링과  dns request 필터링을 켜둔 상태입니다.

아 그리고 두번째 링크는 그냥 링크를 클릭했을때는 아무런 광고가 뜨지 않는데 영상화면을 누르면 11번가앱이 실행이되고 market으로 시작하는 주소의 팝업이 뜹니다.

로그파일을 생성해서 첨부합니다. 확인 부탁드리겠습니다.
감사합니다.
[adguard.zip](https://github.com/SlowMemory/List-KR/files/1030586/adguard.zip)

**Comment by bradly1** [comment]
제가 리스트 담당자는 아니지만, 
http://re19fla.com/?g=KR&l=0Y4CioFCvQX9ClU&s=323874015156&ssk=c96d8ee7b0ad4777d824ca60e6c8e3c7&svar=1495762740.7441&z=942771

라는 url 로 접속을 하면 11번가가 뜨네요... 
||re19fla.com^

이 규칙을 추가하면 11번가로 안넘어갈것 같습니다.

**Comment by nskzhd** [comment]
답변 감사드립니다.
말씀해주신 규칙을 추가했더니.. estream.to 영상의 경우
11번가로는 넘어가지 않는데 플레이스토어의 다른 게임으로 넘어가기도 하고.. 새로운 광고페이지가 뜨기도하고.. 계속적으로 광고새창이 뜹니다.

주소들은 
https://app.adjust.com/uc208o?campaign=Sangokushi+Sousouden+%28Android%2C+Free%2C+KR%2C+50MB%2C+w%2Fcapping%2C+NRB%29&adgroup=23309&gps_adid=%24IDFA&creative=&install_callback=http%3A%2F%2Ftracking.applift.com%2Faff_lsr%3Ftransaction_id%3D10262939618ed83d8f91d1aae1ad87%26adv_sub2%3D%7Binstalled_at%7D%26adv_sub3%3D%7Blanguage%7D%26adv_sub%3D%7Bgps_adid%7D&event_callback=http%3A%2F%2Fevents.applift.com%2Fv1%2Fevents%3Fsource%3Dadeven%26pub_reference_id%3D10262939618ed83d8f91d1aae1ad87%26event_ref_id%3D%7Bevent%7D%26event_name%3D%7Bevent_name%7D%26event_value%3D%7Brevenue_usd%7D&session_callback=http%3A%2F%2Fevents.applift.com%2Fv1%2Fevents%3Fsource%3Dadeven%26pub_reference_id%3D10262939618ed83d8f91d1aae1ad87%26event_ref_id%3Dsession&rejected_install_callback=http%3A%2F%2Fevents.applift.com%2Fv1%2Fevents%3Fsource%3Dadeven%26pub_reference_id%3D%7Btransaction_id%7D%26custom10%3Drejected_%7Brejection_reason%7D%26custom9%3D23309%26custom8%3D47152%26post%3D1
http://play.entretenimientolz.com/red/?code=JDKWM7X43ZOV&a=942771
https://onclkds.com/?auction_id=49622584-20e5-4e02-8bc2-349d97e502d2&zoneid=942771&xref=https%3A%2F%2Festream.to%2Fembed-bmbzdrj5gup5.html&pbk2=ee9a6bee2e25b4259535baaae4bfd8936424697199867553866&r=%2Foc%2Fhan&ab=186&uuid=3f9b1ddb-50ec-4051-9ad0-28d699f4060c&co=-1&rf=-1&hs=&fs=0&sw=360&sh=640&wx=0&wy=0&ww=360&wh=574&wiw=360&wih=574&wfc=0&pl=https%3A%2F%2Festream.to%2Fembed-bmbzdrj5gup5.html&drf=http%3A%2F%2Fkkull.tv%2Fpin%2F239519%2F&np=0&pt=undefined&nb=1&ng=1
http://re19fla.com/?g=KR&l=ap6TgsYIzlQ7tSb&s=314027473711&ssk=5d5ce62644696aae66d218a371612bc3&svar=1495866285.0528&z=942771

이런 페이지들입니다. 찾을 수 없는 페이지들이라고 뜨기도하는데 새 창이 뜨는게 불편해서 아예 차단이 가능한지 문의드리고싶네요.

**Comment by SlowMemory** [comment]
@nskzhd 올려주신 로그를 확인해 보니, HTTPS 연결에 대해서는 주소가 도메인까지만 기록되어 있습니다. 
HTTPS 필터링이 켜져 있지 않거나, 또는 어떤 버그로 인해 적용되지 않은 듯 합니다. HTTPS 필터링을 활성화하신 뒤 확인 부탁드립니다.

**Comment by nskzhd** [comment]
@SlowMemory 버그인걸까요? 며칠전에 누가로 업데이트를 한거 외에는 변경된 사항이 없는데..
혹시나 해서 조금전에 https 필터링을 끄고 인증서 제거 했다가 다시 켜보기도 하고.. 아예 애드가드 자체를 삭제했다가 다시 설치해봤는데도 여전히 새창들이 뜹니다.

그리고 첫번째 링크의 애드블럭을 꺼달라는 메세지는.. 크롬과 다른 브라우저로 접속해봤더니 안뜨네요. 제가 지금 현재 사용하는 브라우저(TF 브라우저)와 관련이 있지 않나 하는 생각이 듭니다. 이 부분은 브라우저 개발자분께 문의해보려고 합니다.

**Comment by SlowMemory** [comment]
TF 브라우저의 문제가 아니라, TF 브라우저가 애드가드 앱에 HTTPS 필터링 가능 브라우저로 등록되지 않아서 발생하는 문제로 추정됩니다.

안드로이드 누가에서 일부 앱은 사용자 인증서를 신뢰하지 않기 때문에 신뢰하는 것으로 확인된 브라우저에서만 HTTPS 필터링을 사용합니다. 

대개 크로뮴 기반 브라우저에서는 HTTPS 필터링을 적용하는 데 문제가 없다고 합니다. 이를 확인할 수 있는 TF 브라우저에 대한 정보, 개발자님의 블로그 등이 없을까요?

**Comment by nskzhd** [comment]
tf브라우저 개발자님이 운영하시는 네이버카페입니다.
http://cafe.naver.com/teamfeedback

근데 두번째 링크(광고창이 뜨는 링크)를 크롬 브라우저에서 열어도 똑같이 광고창이 뜹니다.
그리고 제가 롤리팝 기기가 있어서 애드가드를 똑같이 설정해놓고 위 링크를 접속해봤더니.. 이 기기에서도 광고창이 뜨더라구요. 

tf브라우저와 크롬에서 다른점은 첫번째링크에서 나오는 애드블럭을 꺼달라는 메세지가 뜨는 유무의 차이만 있네요.

계속 신경써주셔서 정말 감사합니다.

**Comment by nskzhd** [comment]
@SlowMemory 
tf브라우저 개발자님이 운영하시는 네이버카페입니다.
http://cafe.naver.com/teamfeedback

근데 두번째 링크(https://estream.to/embed-qd8i530we0w6.html)를 크롬 브라우저에서 열어도 똑같이 광고창이 뜹니다.

tf브라우저와 크롬에서 다른점은 첫번째링크(https://vidlox.tv/embed-xalcu00o1m3r.html)에서 나오는 애드블럭을 꺼달라는 메세지가 뜨는 유무의 차이만 있네요.

계속 신경써주셔서 정말 감사합니다.

**Comment by SlowMemory** [comment]
답변 감사합니다. TF 브라우저 문제는 제가 확인후 Adguard 안드로이드 개발자에게 제보하도록 하겠습니다.

해외 사이트 관련 이슈는 Adguard 피드백 기능으로 Adguard측에 제보해주세요.
글쓴님께서 겪으시는 estream.to 이슈는 글쓴님의 설정 문제 또는 Adguard 버그일 가능성이 있기 때문에 좀 더 살펴보려 합니다.

estream.to 링크에서 광고가 뜨는 현상은, 크롬 브라우저로 접속하였을 때의 로그를 올려 주실 수 있으신가요? 위에 올려주신 TF 브라우저 사용시의 로그에는 특정 팝업광고 서버가 의도한 대로 차단되지 않아 광고가 나타날 있을 것 같습니다. 하지만 크롬에서는 이러한 현상이 일어나서는 안 됩니다.

**Comment by nskzhd** [comment]
제가 브라우저를 왔다갔다 하면서 뭔가 착각했나봅니다. 
크롬에서는 팝업광고가 뜨지 않네요. 죄송합니다.

**Comment by SlowMemory** [comment]
확인 감사합니다!
