### ISSUE TITLE
네이버티비재생 안돼요

### ISSUE THREAD

**Issue by urtheuniverse** [SlowMemory/List-KR#135]
밑에 써진것도 봤는데요

저는 애드가드 프리미엄 윈도우+안드로이드 같이쓰는데

안드로이드는 네이버티비 어플로보니까 상관없는데

PC에서만 말썽이네요

현재 웨일브라우저와 스윙브라우저 이용중이고

윈도우에 애드가드 프로그램이 설치되어있지만 스윙과 웨일브라우저에 적용이 되고있는지 아닌지 확인이 안되서 일단 확장프로그램도 같이 사용중입니다.

확장설정은 
http://imgur.com/q7nc3W9
프로그램설정은
http://imgur.com/q7nc3W9

사진들과같습니다.

2주전부터인가 언제부터인지는 잘 모르겠습니다 블로그에 포스팅된 네이버플레이어를 이용한 영상들과

네이버tv에 등록된 영상들이

영상을 재생할수없습니다

혹은

네트워크상태가원활하지않아영상로딩에실패했습니다
페이지새로고침후다시이용해주십시오

라고 뜹니다.

가끔 새로고침 하다보면 0.1초 영상이 재생되다가 끊깁니다.

밑에도 같은 증상문의있던데

단순화된 도메인 네임 필터' 를 비활성화 하시고 테스트 해주세요

는 단순화된 도메인네임필터가 어디있는지 몰라서 설정은 못해봤고

나머지 업데이트는 다시 하고 해봤는데 역시 안되네요

**Comment by SlowMemory** [comment]
EasyList의 문제로 추측됩니다. EasyList의 문제가 해결될 때 까지 사용 해제하시면 동영상이 잘 재생되리라 생각합니다. 

(Adguard) 영어 필터가 EasyList의 자체 fix이기 때문에 영어 필터를 사용하시면 EasyList를 사용하지 않으셔도 됩니다. EasyList의 업데이트가 약간 늦게 반영되는 정도의 차이는 있을 수 있습니다.

**Comment by urtheuniverse** [comment]
답변감사합니다. 이지리스트지웠는데 영상을재생할수없습니다 문구뜨면서 안되는건.... 똑같네요 ㅠ

**Comment by SlowMemory** [comment]
안녕하세요, 여전히 문제를 겪으신다면 재생이 되지 않는 네이버TV 동영상 링크와 네이버플레이어를 이용하는 블로그 포스트 링크를 각각 알려주실 수 있으신가요? 직접 확인해 보겠습니다.

문제가 재현되지 않는다면, 필터링 로그를 올려주셔야 더 문제 해결을 진행할 수 있을 것 같습니다.

**Comment by urtheuniverse** [comment]
답변 감사합니다. 음..... 특정 영상만 재생이 안되는건아닌거같습니다. 그래서 필터링로그를 올려야할거같은데 어떻게 하는건지
말씀해주실수있나요? 감사합니다

On May 29, 2017 2:55 PM, "SlowMemory" <notifications@github.com> wrote:

안녕하세요, 여전히 문제를 겪으신다면 재생이 되지 않는 네이버TV 동영상 링크와 네이버플레이어를 이용하는 블로그 포스트 링크를 각각
알려주실 수 있으신가요? 직접 확인해 보겠습니다.

문제가 재현되지 않는다면, 필터링 로그를 올려주셔야 더 문제 해결을 진행할 수 있을 것 같습니다.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/SlowMemory/List-KR/issues/135#issuecomment-304578341>,
or mute the thread

**Comment by SlowMemory** [comment]
1. 애드가드 베타 버전으로 업그레이드 해주세요. "일반 설정 ➜ 업데이트시 베타 채널 사용" 에 체크하시고 메인 화면에서 업데이트 체크를 하시면 됩니다.
1. 필터링 로그 창을 열어주세요.
1. 문제가 발생하는 페이지를 브라우저에서 연 후, 동영상 재생 에러가 나타날 때까지 진행해주세요.
1. 필터링 로그 창의 "Export all" 버튼을 눌러서 `.json` 확장자의 파일을 저장해주세요.
![fl](https://cloud.githubusercontent.com/assets/19346646/26543886/9d31d322-449a-11e7-9f16-b413f1f3a192.png)
1. 저장하신 파일을 이곳에 업로드 해주세요.

**Comment by urtheuniverse** [comment]
바쁘실텐데 친절한 설명감사드립니다


이번에 로그하려고 하면서 보니 이번에는 네트워크 어쩌구 메세지나 영상을 재생할수없습니다 하는 문구 없이

그냥 빈 화면으로 나오네요

랜덤으로 아무거나 재생했을 시 이럽니다

순위1위나 2위 해봐도 다 저렇게 빈 화면이네요

링크입니다 http://tv.naver.com/v/1721589/list/67096

감사합니다!
​

2017년 5월 29일 오후 6:17, SlowMemory <notifications@github.com>님이 작성:

**Comment by SlowMemory** [comment]
로그에 네이버tv 동영상 관련 기록은 있는데 동영상 자체를 로드하는 요청이 없네요. 

원글을 다시 읽어보니 확장 프로그램을 같이 사용 중이시라고 하셨는데요, 요청에 Adguard 프로그램에 도달하기 전 확장 프로그램에서 차단되는 것이 일단은 의심됩니다. 어떤 확장 프로그램을 사용중이신지 모두 나열 부탁드리며, 확장 프로그램에서도 EasyList를 사용 중지하셨는지 확인 부탁드려요.

**Comment by urtheuniverse** [comment]
체크감사합니다.

일단 확장프로그램 이용중인 것들 캡쳐본입니다.

http://imgur.com/7Onlnaz

Sidebar - Naver Memo (브라우저기본앱)
Adguard AdBlocker  (윈도우프로그램과 호환됨)
Grammarly for Chrome (그래머체크)
Snstar Me (영상다운로드 확장프로그램) +off 하고 네이버tv확인해봤는데 역시 똑같이 안나오네요 ㅠ

이용중입니다

애드가드 리스트입니다
http://imgur.com/q3LrJI9

영어필터
스파이웨어필터
소셜미디어필터
Annoyance 필터
List-KR 필터
사용자필터(리스트목록봤는데 아무것도없네요 비어있습니다)

스텔스모드 사용안하고있습니다.

웹확장프로그램 리스트입니다.
http://imgur.com/0B5mn4V
-----------------------------------------
영상재생문제화면
http://imgur.com/dlN9uWX
http://imgur.com/IvohwS7

유선무선사용시 문제현상같고 
같은 와이파이 쓰는데 모바일은 정상작동됩니다

**Comment by SlowMemory** [comment]
다음 방법을 시도해볼 수 있을 것 같습니다..
 - 웨일 브라우저에서 확장앱을 모두 임시로 비활성화
 - 쿠키와 임시 파일 삭제 (설정 > 개인정보보호 > 인터넷 사용 기록 삭제 항목에서 "임시 저장된 이미지나 파일", "쿠키" 선택 후 "모든 기록삭제" 클릭)

 - 웨일 브라우저나 스윙 브라우저 외 인터넷 익스플로러, 크롬에서 같은 문제가 나타나는지 확인

 - 아래 두 줄을 사용자 필터에 추가하였을 때 문제가 해결되는지 확인
```
@@||tv.naver.com^$jsinject,elemhide
@@||serviceapi.nmv.naver.com^$jsinject,elemhide
```
로그에는 특별히 차단된 기록이 없고 특히 블로그 내의 동영상의 경우에는 차단된 기록이 없습니다.

**Comment by urtheuniverse** [comment]
[블로그,네이버tv 로그.zip](https://github.com/SlowMemory/List-KR/files/1038567/tv.zip)

네이버티비라고 된거는 네이버티비이고 안써있는건 블로그 로그입니다.

1. http://imgur.com/9v7Nz3b 
비활성후에도 증상이..같네요 ㅠ 

2. 쿠키 임시파일삭제는 매번 브라우저를 닫을때마다 지워지게 설정해뒀고 네이버티비재생이 안되는 문제로 웨일팀의 원격조정을 받아본결과. 크롬 기반 브라우저에서 재생이 안된다는거 알고 해결 못했습니다.

3. 웨일 스윙 똑같이 네트워크문제로 재생할수없다. 영상을재생할수없습니다 문구뜨고 익스에서는 그냥 빈 검은 화면만 뜹니다.

4. 필터 추가후 변경사항이없습니다.

+왜 그랬는지 모르겠는데 블로그영상, 일반네이버티비영상 다 로딩바 돌아가거나 안된다고 문구뜨거나
재생완료후 화면이 뜨네요
새로고침하다가 딱 두번 재생이 됐는데요 네이버tv영상 http://tv.naver.com/v/1725937/list/67096

링크는 이거고 딱 30초 정도 재생되다가 재생할수없다고 하고 문구 뜨고 짤리네요

다른영상은 아예 재생할수없다고 떴습니다 이 로그 첨부했습니다.

인터넷문제는아닌거같은게... 2주전까지만해도 잘 재생됐는데 갑자기 안됐거든요.. 인터넷도 그전과같이 변경사항없이 쓰고있었어서..... ㅠ 계속 확인해주시고 감사드립니다 진짜 ㅠ

**Comment by SlowMemory** [comment]
안녕하세요, 답변이 늦어서 죄송합니다. 로그를 봐도 문제의 원인이라 할 만한 것이 발견되지 않네요..
```
@@||naver.com^$document
```
규칙을 추가하시고 확인 부탁드리며, 
더 해볼 만한 건 Adguard 에 버그 리포트를 보내는 것 정도가 있을 것 같습니다.
프로그램에서 고객 지원 버튼을 통해 버그 리포트를 보내시고, 보내실 때 사용하신 메일 주소를 알려주세요.
제보 내용에는 문제의 설명과 함께 이 이슈의 url을 붙여넣으시면 될 것 같습니다.

**Comment by urtheuniverse** [comment]
안녕하세요 늦게라도 답변주셔서 감사합니다.

제 컴퓨터의 OS에서 다른 문제가있어서 윈도우 포맷을했습니다. 그런후 다시 같은 설정으로 다 해보니 재생이 되네요

뭐가 문제였는지 잘 모르겠습니다. 한달전까지만해도 잘 되던게 안됐었어서 무튼 포맷하고 하니 되서 다행이네요

끝까지 봐주셔서 감사드립니다!! ^^ 도움이 많이 됐던거같습니다.

2017년 6월 6일 오후 4:45, SlowMemory <notifications@github.com>님이 작성:
