### ISSUE TITLE
네이버스포츠의 경기기록란이 보이지 않습니다.

### ISSUE THREAD

**Issue by dldh** [SlowMemory/List-KR#136]
http://m.sports.naver.com/baseball/gamecenter/kbo/index.nhn?gameId=20170528SSWO02017&tab=record

안녕하세요.

원래라면 해당 링크의 기록들이 보였어야하는데

안 보이기에 애드가드를 꺼봤더니 보이기 시작하네요.

혹시 가능하시다면 한 번 확인 부탁드립니다.

**Comment by SlowMemory** [comment]
안녕하세요, "모바일 광고 필터" 를 사용하고 계신가요? 해당 문제를 위한 허용 규칙이 모바일 광고 필터에 포함되어 있습니다.

**Comment by dldh** [comment]
모바일 광고 필터를 사용하지 않고 있었습니다.
번거롭게 해드려 죄송합니다.
