### ISSUE TITLE
모 블로그 광고 차단 문제입니다.

### ISSUE THREAD

**Issue by edoko** [SlowMemory/List-KR#137]
이전에 이슈가 있어서 제보하여 해결되었으나
최근에 확인해보니 다른 방식으로 바뀌었습니다.

reblogit.tistory.com##u
reblogit.tistory.com###p64a

구문을 추가하면 정상적으로 작동하는 것으로 보입니다.

**Comment by SlowMemory** [comment]
제보 감사합니다. 필터 업데이트 후 문제가 해결되었는지 확인 부탁드립니다.

**Comment by edoko** [comment]
네 해결되었습니다. 감사합니다.
