### ISSUE TITLE
tvple 양쪽 광고 2개 표시

### ISSUE THREAD

**Issue by edoko** [SlowMemory/List-KR#138]
![2](https://cloud.githubusercontent.com/assets/1365682/26615594/eb1648f2-4602-11e7-89e8-f1ccadb5ddcc.PNG)

위 사진처럼 광고는 차단되지만 레이아웃은 사라지지 않는 문제가 있습니다.
현재 크로미움 기반 네이버 웨일 브라우저 최신버전, ublock origin 사용 중입니다.

대신 광고 규칙에

tvple.com##.side-right > .text-center > .lazyloaded
tvple.com##.side-left > .text-center > .lazyloaded

을 삽입하면 그 부분도 사라지는데 반영해주시면 감사하겠습니다^^.

**Comment by SlowMemory** [comment]
제보 감사합니다. 말씀하신 요소를 차단하도록 반영하였습니다.
