### ISSUE TITLE
알송어플 광고차단이 되지 않습니다

### ISSUE THREAD

**Issue by clampxp** [SlowMemory/List-KR#139]
대부분의 어플들은 광고차단이 되는데 알송이 되지않아 문의글 썼습니다

**Comment by SlowMemory** [comment]
안녕하세요, 제 기기에서는 광고 차단이 잘 되지만 HTTPS 필터링을 끌 경우 앱 실행시 전면광고가 나타나는 것을 확인했습니다.

혹시 안드로이드 누가 버전을 사용하고 계신가요? 누가 버전에서는 알송 어플에서 HTTPS 필터링이 적용되지 않을 수 있어, 기존 광고를 차단하는 데 사용되던 규칙을 HTTPS 필터링 없이도 적용되도록 도메인 기반 규칙으로 바꾸었습니다.

약 1시간 뒤 필터를 업데이트하신 후 확인 부탁드립니다.

**Comment by clampxp** [comment]
마시멜로우 입니다. 빠른 피드백 감사합니다

**Comment by clampxp** [comment]
업데이트를 해도 증상은 똑같습니다 ㅠㅠ

**Comment by SlowMemory** [comment]
- HTTPS 필터링이 활성화되어 있는지,
 - 알송 어플의 캐시를 안드로이드 설정에서 삭제 후 광고가 나타나는지,
 - Wi-Fi 환경에서 광고가 나타나는지,
 - 또 혹시 모르니 List-KR 필터를 필터 선택 창에서 체크 해제 ➜ 보호 중지 ➜ 보호 재시작 ➜ List-KR 필터 체크 ➜ 보호 중지 ➜ 보호 재시작 하신 후 문제가 해결되는지 확인 부탁드립니다.

**Comment by clampxp** [comment]
1. 활성화 했습니다
2. 캐시 삭제 후 앱실행해도 광고가 나왔습니다
3. 와이파이 켜도 나오고 데이터 사용해도 나왔습니다
4. 해봤지만 광고가 나왔습니다

**Comment by nskzhd** [comment]
@clampxp 예전에 https필터링을 켜도 광고차단이 안되는 앱이 있어서 문의글 남겼을때 slowmemory님이 dns 필터링도 켜보라고 하셔서 해결됐던 적이 있습니다.

고급설정에 dns 필터링도 한번 켜보세요.

**Comment by clampxp** [comment]
네 했지만 광고가 나옵니다. 
제가 설정을 잘못한것일까요?

**Comment by SlowMemory** [comment]
Adguard 앱의 버그일 수도 있습니다.
[위키 글](https://github.com/SlowMemory/List-KR/wiki/Adguard-%EC%95%88%EB%93%9C%EB%A1%9C%EC%9D%B4%EB%93%9C-%EB%B2%84%EC%A0%84%EC%9D%98-%EB%A1%9C%EA%B7%B8%EB%A5%BC-%EC%96%BB%EB%8A%94-%EB%B2%95) 을 참고하셔서 HAR log를 보내주실 수 있으신지요? 감사합니다.

**Comment by clampxp** [comment]
공초해서 새로 설치해서 해결했습니다 ㅎㅎ
감사합니다
