### ISSUE TITLE
애니갓 광고 도메인 추가

### ISSUE THREAD

**Issue by lkl089** [SlowMemory/List-KR#140]
http://twitter0.unknowncdn.com
http://twitter0.oderk.com
http://twitter0.teslacdn.com
http://twitter0.awscontent.com

요렇게 네개가 또 추가됐더군요

**Comment by SlowMemory** [comment]
제보 감사합니다. 필터 업데이트 후 확인 부탁드립니다.

**Comment by lkl089** [comment]
감사합니다 잘 작동합니다

**Comment by lkl089** [comment]
지금 확인해보니 도메인이 또 추가됐네요

twitter0.facebooook.website
twitter0.youtubbe.website
twitter0.goooooooogle.website
twitter0.teslaaa.website
twitter0.kakaooo.website
twitter0.twittter.website
twitter0.netflixxx.website

============

@@/cdn-dgi/pe/bag2?r[]=*%2Fjs%2Fads.exoclick.com.js^$~third-party,domain=​twitter0.facebooook.website|twitter0.youtubbe.website|twitter0.goooooooogle.website|twitter0.teslaaa.website|twitter0.kakaooo.website|twitter0.twittter.website|twitter0.netflixxx.website

@@/js/ads.exoclick.com.js^$~third-party,domain=twitter0.facebooook.website|twitter0.youtubbe.website|twitter0.goooooooogle.website|twitter0.teslaaa.website|twitter0.kakaooo.website|twitter0.twittter.website|twitter0.netflixxx.website

twitter0.facebooook.website|twitter0.youtubbe.website|twitter0.goooooooogle.website|twitter0.teslaaa.website|twitter0.kakaooo.website|twitter0.twittter.website|twitter0.netflixxx.website#@##banner_ad

twitter0.facebooook.website|twitter0.youtubbe.website|twitter0.goooooooogle.website|twitter0.teslaaa.website|twitter0.kakaooo.website|twitter0.twittter.website|twitter0.netflixxx.website#%#(function(){var a={debug:{set:function(){return a}},on:function(b,c){b||setTimeout(function(){c()},1);return a},onDetected:function(b){return a.on(!0,b)},onNotDetected:function(b){return a.on(!1,b)},check:function(){}};Object.defineProperty(window,"fuckAdBlock",{get:function(){return a}})})();
twitter0.facebooook.website|twitter0.youtubbe.website|twitter0.goooooooogle.website|twitter0.teslaaa.website|twitter0.kakaooo.website#%#window.canRunAds = !0;

@@/fuckadblock.js^$~third-party,domain=twitter0.facebooook.website|twitter0.youtubbe.website|twitter0.goooooooogle.website|twitter0.teslaaa.website|twitter0.kakaooo.website|twitter0.twittter.website|twitter0.netflixxx.website
@@/js/ads.js^$domain=twitter0.facebooook.website|twitter0.youtubbe.website|twitter0.goooooooogle.website|twitter0.teslaaa.website|twitter0.kakaooo.website|twitter0.twittter.website|twitter0.netflixxx.website

@@||twitter0.facebooook.website^$generichide
@@||twitter0.youtubbe.website^$generichide
@@||twitter0.goooooooogle.website^$generichide
@@||twitter0.teslaaa.website^$generichide
@@||twitter0.kakaooo.website^$generichide
@@||twitter0.twittter.website^$generichide
@@||twitter0.netflixxx.website^$generichide

**Comment by lkl089** [comment]
![1](https://cloud.githubusercontent.com/assets/20037318/26750635/d8f0c97e-4862-11e7-8ffa-49b94bcfc9fd.PNG)
![2](https://cloud.githubusercontent.com/assets/20037318/26750636/d8f1b8f2-4862-11e7-9f1d-03676469b5b2.PNG)
 
이제는 넘어가는 버튼에 광고창 크기 체크하고 지정된 크기가 아니면 안넘어가게 바꼈네요

**Comment by SlowMemory** [comment]
제보 감사합니다. 도메인이 바뀔 때마다 필터에 추가하는 작업이 번거로워 소소하게나마 이를 자동화 하는 스크립트를 추가하였습니다.
여러 도메인을 돌려가며 광고차단을 회피하는 행위는 adf.ly 등 해외 사이트에서는 빈번합니다.
도메인이 또 추가된다면 알려주시길 부탁드리겠습니다. 감사합니다.

**Comment by lkl089** [comment]
정상적으로 넘어가지네요
매번 감사드립니다

**Comment by lkl089** [comment]
이번엔 도메인 앞부분을 twitter0에서 twitter1로 바꿨네요
새로 추가된 링크는 없고 기존 추가된 링크에서 twitter0만 삭제하시면 될거같습니다

twitter1.facebooook.website
twitter1.youtubbe.website
twitter1.goooooooogle.website
twitter1.teslaaa.website
twitter1.kakaooo.website
twitter1.twittter.website
twitter1.netflixxx.website
twitter1.apppple.website
twitter1.iiinstagram.website
twitter1.amazooon.website

**Comment by lkl089** [comment]
애니갓 메인 접속주소가 anigod.com에서
anigod.org로 변경됐네요

**Comment by parksueng** [comment]
업데이트 했지데 광고기능 차단을 중지해달라고 뜨네요ㅜㅜ

**Comment by lkl089** [comment]
gryfindor.com

결국 이도메인을 또 쓰네요

**Comment by lkl089** [comment]
![2017-06-10 5 34 34](https://user-images.githubusercontent.com/20037318/27001361-4020180c-4e03-11e7-9c94-419a02472876.png)
광고가 차단이 안되는거같더니만 이젠 document.write를 써서 우회하네요

**Comment by ji1park** [comment]
![default](https://user-images.githubusercontent.com/22656220/27011114-19239a60-4ef0-11e7-8e25-a01b2a8a2333.PNG) 이렇게 만들어 놨네요

**Comment by SlowMemory** [comment]
@lkl089 안녕하세요, 광고가 며칠간 차단되지 않은 현상은 제가 임시로 범위가 넓은 예외 규칙을 추가하여 발생한 것입니다. `document.write` 자체는 일반적인 광고 로딩 방식입니다.
당시 해당 규칙 없이는 리디렉션 페이지를 따라가다 보면 어느 순간 링크가 작동하지 않는 현상이 보이더군요.

현재는 리디렉션 페이지 대신 바로 shorte.st 등 서버로 연결되기에 해당 규칙을 삭제하였습니다.
