### ISSUE TITLE
광고제보

### ISSUE THREAD

**Issue by SHxXxJ** [SlowMemory/List-KR#142]
http://etobang.com

![image](https://cloud.githubusercontent.com/assets/28824568/26811374/5d0b7ee8-4aac-11e7-8a13-f818a4f66f09.png)
||deliverys.n2s.co.kr/afm.php?zoneid=1000090&loc=1&ref=1
||etobang.com/etoad/300_250.php

**Comment by SlowMemory** [comment]
문제가 재현되지 않습니다.
 - 광고가 나타나는 페이지의 url,
 - 사용하시는 광고차단 프로그램, 사용하시는 필터 목록

을 각각 알려주실 수 있으신가요?
