### ISSUE TITLE
크몽, 고파스 관련 문제입니다

### ISSUE THREAD

**Issue by WingsK** [SlowMemory/List-KR#143]
안녕하세요.

1. 모바일 환경에서 크몽의 상품을 볼 때, 서비스설명의 내용 더보기 버튼이 보이지 않습니다.
Ex)https://kmong.com/gig/64476

2. 역시 모바일 환경에서 고파스 접속 시 메인 화면에서 상단 광고가 보입니다.
https://www.koreapas.com/m/main.php

감사합니다.

**Comment by SlowMemory** [comment]
제보 감사합니다. 크몽 관련 문제는 필터 업데이트 후 확인 부탁드립니다.
모바일 환경에서 고파스에 접속하면 로그인 페이지가 뜹니다. 제가 아이디가 없는 관계로 광고를 확인하고 규칙을 업데이트 하기가 어렵습니다.

페이지를 데스크탑 브라우저로 여신 후 페이지를 html 파일로 저장하여 이곳에 올려 주시거나, 페이지의 소스 코드를 텍스트 파일로 복사해서 올려주시면 감사하겠습니다.

**Comment by bradly1** [comment]
저의 경우도 똑같이 뜨네요 
[koreapas.txt](https://github.com/SlowMemory/List-KR/files/1074357/koreapas.txt)

<a href="https://goo.gl/yXgzN3" target="_blank"><img src="https://www.koreapas.com/bbs/no_unicorn/eye170630pc2.jpg" width=280 border=0>

이 부분을 차단하면 될것같습니다.

**Comment by WingsK** [comment]
안녕하세요.

크몽 건은 해결된 듯 합니다.

고파스의 경우 PC에서 모바일 주소로 접속 시 광고가 표시되지 않는 듯 합니다. 모바일에서는 표시되고요. PC에서 저장한 HTML 파일입니다.

**Comment by SlowMemory** [comment]
PC에서 모바일 페이지로 접속하려면 User Agent 변경 확장 프로그램 등을 통해 User Agent를 모바일 브라우저의 것으로 변경하시면 됩니다. 광고가 나타나는 페이지의 HTML 코드와 스크린샷을 올려주시면 감사드리겠습니다.

**Comment by WingsK** [comment]
[새 텍스트 문서.txt](https://github.com/SlowMemory/List-KR/files/1085656/default.txt)
첨부했습니다.

**Comment by SlowMemory** [comment]
@WingsK 스크린샷도 함께 올려주시면 감사드리겠습니다.

**Comment by WingsK** [comment]
![kakaotalk_20170623_224151922](https://user-images.githubusercontent.com/28503484/27484728-44a32d4e-5865-11e7-95bd-985c7b22b8cd.png)
첨부했습니다.

**Comment by SlowMemory** [comment]
올려주신 스크린샷에 나타난 광고 이미지는 https://www.koreapas.com/bbs/no_unicorn/anamwithb.jpg 이며
다음 규칙
```
||koreapas.com/bbs/no_unicorn/$image
```
으로 차단이 되어야 합니다. 

제 기기에서는 정상적으로 차단이 됩니다.
[screenshot](https://user-images.githubusercontent.com/19346646/27506170-e24ee10e-58ed-11e7-9942-6ce99576eae9.png)

크롬 브라우저에서 해당 이미지를 캐싱하여 차단되지 않는 것일 수 있습니다. 크롬 브라우저 앱의 캐시를 안드로이드 설정에서 지우시면 문제가 해결될 수 있습니다.
