### ISSUE TITLE
알바몬 메인 상단 배너

### ISSUE THREAD

**Issue by edoko** [SlowMemory/List-KR#144]
하루에 한번씩 상단에 큰 배너가 나옵니다.

매번 눌러줘야 그날은 없어지는데

www.albamon.com##.stickyBestalba.sticky

를 룰에 추가하면 사라지는데 반영 부탁드리겠습니다.

**Comment by SlowMemory** [comment]
안녕하세요, 이러한 웹사이트의 자체 홍보용 배너는 List-KR에서 차단하는 대상이 아닙니다. 규칙을 사용자 필터에 추가하여 사용하시거나, 사용하시는 광고 차단 프로그램의 support 등에 제보하실 수 있을 듯 합니다.
