### ISSUE TITLE
해외 어학사이트 rong-chang.com 차단 부탁드립니다.

### ISSUE THREAD

**Issue by gonchur** [SlowMemory/List-KR#146]
http://www.rong-chang.com/eslread/

adguard 가 설치되있다는 창이 나와서 안나오게 하려고 몇 시간째 끙끙대고 있네요.ㅠㅠ
아래 규칙으로 테스트 해봐도 되는듯 안되는듯 반복되는게 보이는데 비전산 전공자라 그런지
소스를 아무리 까봐도 뭘 더 차단해야 될지 모르겠어요. 혹시 테스트 가능하시면 말씀 부탁드립니다.
||rong-chang.com#@#.adsbox
||rong-chang.com##DIV.warning
||rong-chang.com#@#.adsbygoogle
||rong-chang.com#@#.warning-content

**Comment by SlowMemory** [comment]
`rong-chang.com#@#.adsbox`를 추가하시면 될 듯합니다.

주소 기반 차단 규칙에서 사용되는 `||` 기호는 도메인을 나타내기 위한 주소이며 요소 숨김 규칙에서는 특별한 의미가 없습니다. `##, #@#, #$#, #%#` 등 규칙을 쓰실 때는 `||` 없이 도메인만 쓰시면 됩니다.

**Comment by gonchur** [comment]
|| 늘 쓰는줄 알았는데 말씀 감사합니다.
