### ISSUE TITLE
안녕하십니까. 웹사이트 광고 차단 문의드립니다.

### ISSUE THREAD

**Issue by todayhumor** [SlowMemory/List-KR#148]
윈도우 8.1 및 익스플로러 11 사용자입니다.

http://www.tomovie.net/bbs/board.php?bo_table=torrent_movie_eng
상단 및 우측 사이드바 광고 제거 요청드립니다. 감사합니다.

![23](https://user-images.githubusercontent.com/27630015/27211574-2e1e3486-5295-11e7-90b3-5a65ada292f5.JPG)

**Comment by SlowMemory** [comment]
제보 감사합니다. 필터 업데이트 후 확인 부탁드립니다.
