### ISSUE TITLE
네이버 블로그 모바일 페이지 이웃추가 팝업

### ISSUE THREAD

**Issue by madmatic4git** [SlowMemory/List-KR#149]
주로 검색엔진에서 링크될때 발생하는 문제이고, 직접 접속해도 동일합니다.

취소 버튼을 누를수가 없어서 팝업 창을 없앨 수 없습니다.

인터넷 익스플로러에서만 발생하는 문제 같습니다. (windows 10 & ie11 & adguard 사용중)

크롬과 안드로이드 환경에서는 문제없습니다.

http://i.imgur.com/bx3RrPS.png

https://m.blog.naver.com/wms1407/220769247218

**Comment by SlowMemory** [comment]
제 기기에서는 IE11 사용시 Adguard를 사용 중지해도 이웃추가 팝업 레이어가 닫히지 않습니다. 글쓴님의 환경에서는 Adguard를 종료하시면 같은 문제가 발생하지 않나요?

해당 레이어를 숨기려면 `m.blog.naver.com##._buddyRecommendationLayer` 를 사용자 필터에 추가하시면 됩니다.

**Comment by madmatic4git** [comment]
ie11 자체적인 문제인지는 생각치도 못했네요. 알려주신 사용자 필터로 불편함을 덜었습니다.
