### ISSUE TITLE
voda.donga.com 재생 안됨

### ISSUE THREAD

**Issue by madmatic4git** [SlowMemory/List-KR#150]
광고는 나타나지 않지만 "15초 후 광고를 건너뛸 수 있습니다." 메세지만 나타나고 재생되지 않습니다.

windows & android 동일합니다.

http://voda.donga.com

**Comment by SlowMemory** [comment]
제보 감사합니다. 필터 업데이트 후 확인 부탁드립니다.

**Comment by madmatic4git** [comment]
필터 업데이트 후 제대로 재생됩니다. 감사합니다.
