### ISSUE TITLE
네이버 스포츠 광고 차단이 되지 않습니다.

### ISSUE THREAD

**Issue by exp10it3r8** [SlowMemory/List-KR#151]
Windows10 Education Edition 64-bit, Chrome 버전 59.0.3071.109 (64비트), Adguard 6.2.369.1938, list-kr 1.0.3.6 버전 사용 중입니다.

아래와 같이 네이버 스포츠 광고 차단이 되지 않습니다. 확인 부탁드립니다.
발생 주소는 다음과 같습니다.
http://sports.news.naver.com/kbaseball/vod/index.nhn?category=kbo&listType=total&date=&gameId=&teamCode=&playerId=&keyword=&id=320153&page=1

![kbo](https://user-images.githubusercontent.com/29661572/27489240-c5143824-5874-11e7-98ee-da50158ded4e.PNG)

**Comment by SlowMemory** [comment]
제보 감사합니다. 필터 업데이트 후 확인 부탁드립니다.

**Comment by exp10it3r8** [comment]
감사합니다.
