### ISSUE TITLE
네이버TV 캐스트 광고 차단 문의드립니다

### ISSUE THREAD

**Issue by todayhumor** [SlowMemory/List-KR#157]
최근에 이런 비슷한 문제들이 종종 보이길래 저에게는 그저 머나먼 이야기일 줄 알았습니다.
가끔 신경쓰이긴했지만 잘 활용하지 않았던 네이버 tv캐스트였기 때문입니다.

http://m.tv.naver.com/v/1803975
![screenshot_2017-07-04-09-40-04](https://user-images.githubusercontent.com/27630015/27811143-aff6de2a-609d-11e7-8604-7f0d1cb3df16.png)

그러나 어제와 오늘 이런 일들이 모바일에서 보이더라구요.
4.4.2 킷캣 안드로이드 정식.  LG-F350S 모델 사용중이고, 크롬 47.0.2526.83 버전입니다.

**Comment by SlowMemory** [comment]
제보 감사합니다. 확인해본 결과 일부 적용되어야 하는 규칙이 적용되지 않고 있더군요. 이는 Adguard 앱의 버그인 듯합니다. 우선 해당 버그가 해결되기 전까지 어떻게 규칙을 적용할 수 있을지 생각해 보겠습니다..
