### ISSUE TITLE
LG 다운로드 자료실 다운로드 불가능

### ISSUE THREAD

**Issue by WingsK** [SlowMemory/List-KR#158]
안녕하세요.

LG 다운로드 자료실에서 각종 파일의 다운로드가 불가능합니다.

https://www.lgservice.co.kr/download/selectSearchView.do#none

저와 같은 경우는 위 링크에서 43UD79T의 소프트웨어의 다운로드가 불가능했습니ㅏㄷ.

항상 감사합니다.

**Comment by SlowMemory** [comment]
링크가 잘못된 것 같습니다. 올려주신 링크는 https://www.lgservice.co.kr/download/selectProductSearch.do#none 로 리다이렉트 됩니다. 검색하신 소프트웨어가 어떤 상품의 소프트웨어인지요?

**Comment by WingsK** [comment]
모니터-43UD79T 입니다. 모든 파일의 다운로드가 불가능합니다.

**Comment by SlowMemory** [comment]
제보 감사합니다. 다운로드 버튼 클릭 event handler에서 acecounter 의 리소스의 특정 함수를 호출하여 발생하는 문제인 듯 합니다. 해당 리소스를 허용하여 해결하였습니다. (리소스가 수집한 정보를 acecounter 서버로 전송하는요청은 여전히 차단됩니다)
