### ISSUE TITLE
디시인사이드 어플 광고 차단 부탁드립니다.

### ISSUE THREAD

**Issue by diajw** [SlowMemory/List-KR#160]
안녕하세요. 덕분에 쾌적하게 광고 없는 생활 이어가고 있습니다.

디시인사이드 어플에 광고가 워낙 많아 완벽하게 차단되지 못하고 있는것 같습니다.

adguard 안드로이드 버젼 사용중이묘 https / 고품질로 이용중인데

공백이 생기거나 광고가 나오는 경우가 가끔 발생하여 문의 드립니다. 감사합니다.

**Comment by SlowMemory** [comment]
제 기기에서는 광고가 재현되지 않습니다. 나타나는 광고의 스크린샷을 올려주실 수 있으신가요?
