### ISSUE TITLE
moeni.net 광고차단 문의

### ISSUE THREAD

**Issue by DandyClubs** [SlowMemory/List-KR#161]
moeni.net 사이트에 클릭을 하더보면..
bridsun.com으로 시작되는 탭이 열렸다가 리다이렉트 되던데요.

광고차단 규칙을 어떻게 해야 될까요?

**Comment by SlowMemory** [comment]
안녕하세요, 제 측에서는 문제가 재현되지 않습니다만, moeni.net에서는 go.onclasrv.com 도메인으로부터 특정 팝업 광고 리소스를 로드하는데, 해당 리소스는 요청이 차단되면 차단 리스트에 등록되지 않은 도메인을 통해 리소스를 다시 요청합니다.

어떤 광고차단 프로그램의 몇 버전을 사용하고 계신가요?

**Comment by DandyClubs** [comment]
uBlock Origin 최신버전을 사용하고 있고

파폭과 크롬을 이용하고 있습니다.

팝업 주소도 자주 바뀌는군요

사용중인 필터입니다.

113,722 네트워크 필터 ＋ 84,414 표면 필터:

 내 필터​​​​​281개 중 278개 사용 중​​​​
uBlock filters​​​​​1,539개 중 1,539개 사용 중​​​​
uBlock filters – Badware risks​​​​​8개 중 8개 사용 중​​​​
uBlock filters – Privacy​​​​​59개 중 59개 사용 중​​​​
uBlock filters – Unbreak​​​​​178개 중 178개 사용 중​​​​

광고 (3)
Adblock Warning Removal List​​​​​382개 중 366개 사용 중​​​​
Anti-Adblock Killer | Reek​​​​​2,179개 중 2,168개 사용 중​​​​
EasyList​​​​​75,077개 중 74,854개 사용 중​​​​

개인정보 (1)
EasyPrivacy​​​​​13,313개 중 13,296개 사용 중​​​​

멀웨어 도메인 (1)
Malware domains​​​​​26,952개 중 26,952개 사용 중​​​​

소셜 (1)
Fanboy’s Annoyance List​​​​​26,246개 중 26,226개 사용 중​​​​

지역, 언어 (2)
CHN: EasyList China (中文)​​​​​13,787개 중 13,761개 사용 중​​​​
RUS: RU AdList (Дополнительная региональная подписка)​​​​​20,536개 중 20,435개 사용 중​​​​

사용자 지정 (9)
https://ransomwaretracker.abuse.ch/downloads/RW_DOMBL.txt​​​​​1,844개 중 1,587개 사용 중​​​​
https://ransomwaretracker.abuse.ch/downloads/RW_IPBL.txt​​​​​353개 중 353개 사용 중​​​​
https://ransomwaretracker.abuse.ch/downloads/RW_URLBL.txt​​​​​10,721개 중 10,721개 사용 중​​​​
Adware filters​​​​​178개 중 174개 사용 중​​​​
Anti popads.net​​​​​1,614개 중 1,610개 사용 중​​​​
Block-EU-Cookie-Shit-List​​​​​1,152개 중 586개 사용 중​​​​
List-KR​​​​​2,879개 중 2,864개 사용 중​​​​
List-KR unbreak​​​​​77개 중 77개 사용 중​​​​
Overlay Blocker​​​​​50개 중 44개 사용 중​​​​

**Comment by SlowMemory** [comment]
안녕하세요, 다시 한번 확인해보니, moeni.net 사이트에서는 go.onclasrv.net 서버로부터 로드되는 팝업 광고 외에 Amazon Cloudfront에서 로드되는 타 광고사의 팝업 광고 또한 사용하고 있더군요. 해당 광고가 항상 페이지에 삽입되지는 않는 탓에 처음 사이트를 방문했을 때 놓쳤던 것 같습니다.


페이지 소스를 보시면 매우 길고 심하게 난독화된 자바스크립트 코드가 있을 텐데, 이것이 제가 가리키는 팝업 광고의 소스입니다. 이 광고는 ad-maven.com 사의 팝업 광고로 알려져 있으며 올해까지도 멀웨어 유포의 경유지가 된 것으로 알려져 있습니다. 소스 파일을 차단하면 좋을 텐데, 해당 파일이 차단될 시 moeni.net 측에서 광고차단 알림이 뜨도록 설정해놓았더군요. 우선 Adguard에서 사용되는 자바스크립트 삽입 규칙으로 해당 소스코드의 실행을 중지하도록 하였고, ublock origin에서는 비슷한 효과를 가진 규칙으로 `moeni.net##script:inject(abort-on-property-write.js, Fingerprint2)` 를 사용자 필터에 추가하시면 팝업 광고가 차단되리라 생각합니다.
