### ISSUE TITLE
네이버 카페 문의 드립니다.

### ISSUE THREAD

**Issue by iodrome** [SlowMemory/List-KR#162]
네이버 카페 게시글 보면 본문과 댓글 사이에 북마크, 구독 버튼이 있는데 Adguard 활성화 시 이 버튼들이 사라집니다. 네이버 카페 말고 네이버 블로그도 이 버튼들이 있는데 Adguard 활성화 시 역시 이 버튼들이 사라집니다.

![image](https://user-images.githubusercontent.com/30247080/28294126-04caff08-6b93-11e7-9eb1-22e3c4c81722.png)
Adguard 미사용

![image](https://user-images.githubusercontent.com/30247080/28294136-0d77ce4c-6b93-11e7-8325-259b256b7d5c.png)
Adguard 사용

<br>
그리고 안드로이드에서 에브리온TV 동영상 광고가 완전히 차단되지 않습니다.
채널간 이동 시에 이따금씩 동영상 광고가 나옵니다. 
3개 중에 아무 거나 하나 사용자 필터로 추가하면 동영상 광고 안 나오는데 뭐가 효율적인지는 모르겠습니다. 

||api.wecandeo.com
||ss.dawin.tv
||dawinvad.fms.wecandeo.com

아래는 Packet Capture 어플로 확인한 정보입니다.

##

GET /video?k=BOKNS9AQWrEAJSk8zOKFs2PIRtwtPNLRQEEd3pCkCNisUnXipDKVCdSwieie HTTP/1.1
Host: api.wecandeo.com
Connection: Keep-Alive
Accept-Encoding: gzip

##

GET /imp?tag=play_start&dsp=CPVC&sid=6T3JW042FPJ&uid=c847bc20-6aec-11e7-8336-afec49292fb2&aid=e8c91b8b-d137-4f22-8663-0d3aa3a1905d&ud=0&cat=null&ag=null&ge=null&cid=6018&key=8c1765c3-9c97-4d85-9e6f-fab4cc755a61&xps=eJw1zs1OhDAQAOC3mRtmpmXZcuiBJksiERKM2rC3QrG7sGhcWBWe3lZj5vLNT2bmo7MSBRIyJLDm6%2FwmM6%2FP%2FirZHcLk2xQTdGEsRgQXQJ7kkzkk7C%2FA2LN9HyX9QvaiS6kVbWSJ76P4lbFIJAmP0HJjuKEUdxY6P8jidA%2FGeSVIAkyAiBl0V6%2BUe7mwjwjc7f9Xfx1uvthsDitWDOWQLdWUX5oVv0v9zB%2Be3FZuzdLo46XZ6l05jOtxul9hmeVBFZXOZ5W53L6MRa1PpLRT7SOdelXP6geqOlAD&dawin=A01 HTTP/1.1
Host: ss.dawin.tv
Connection: Keep-Alive

##

GET /100/274/2017/06/02/17/V4242690.mp4?key=lVe3k7w1wPHt3EcdrkWUdyGuyxsv6AshT08UAx8h4bjjwYnU53fhClYTGT2i8Xy%2BGbAko2IwxH2fFx0LLOiv8SeYHJBKOPvVb%2FzKnvTY7xw%3D&px-bps=863343&px-bufahead=10&packageId=1000990&videoId=6496277 HTTP/1.1
Host: dawinvad.fms.wecandeo.com
Connection: Keep-Alive
Accept-Encoding: gzip

**Comment by SlowMemory** [comment]
제보 감사드립니다. 에브리온tv 앱과 관련하여 마찬가지 요청이 발생하는 것을 확인하였습니다.
`ss.dawin.tv, dawinvad.fms.wecandeo.com` 두 도메인을 차단하도록 업데이트 하였습니다.

네이버 카페 게시글의 구독 버튼이 차단되는 문제에 대해선, '소셜 미디어 필터' 를 사용하고 계신가요? 해당 필터의 `naver.com##.naver-splugin` 규칙이 차단하고 있는 것 같습니다.
차단되는 버튼들은 카페 게시글을 타 플랫폼으로 공유하기 위한 버튼이라, '소셜 미디어 필터' 의 차단 대상에 부합하는 듯합니다. 해당 필터는 List-KR과는 관련이 없으니, Adguard 측으로 직접 피드백을 보내시길 바랍니다.

**Comment by iodrome** [comment]
소셜 미디어 필터에서 차단하는지 몰랐습니다. '소설 미디어 필터' 해제하거나 사용자 필터 추가하니 정상적으로 나옵니다. 에브리온tv도 정상적으로 광고 차단 됩니다. 감사합니다.
