### ISSUE TITLE
adblock 감지 사이트

### ISSUE THREAD

**Issue by exp10it3r8** [SlowMemory/List-KR#165]
https://reshade.me/presets

웹사이트 이용에 불편함은 없으나, adblock 감지가 되어 일단 올려봅니다.

**Comment by SlowMemory** [comment]
안녕하세요, 해당 웹사이트에서는 `https://reshade.me/media/system/js/advert.js` 파일이 차단되는지 여부를 감지하여 메세지를 표시하고 있습니다.
`@@||reshade.me/media/system/js/advert.js^` 규칙을 추가하여 이 파일을 허용하시거나, `reshade.me##.g-particle > div[style="text-align: center;"] > script + p` 를 추가하셔서 감지 메세지를 가리시면 되리라 생각됩니다.

해당 웹사이트는 한국 웹사이트가 아니므로, List-KR에 따로 필터를 추가하지는 않겠습니다.
