### ISSUE TITLE
adguard 사용 시 네이버 블로그가 들어가지지 않습니다.

### ISSUE THREAD

**Issue by exp10it3r8** [SlowMemory/List-KR#166]
![default](https://user-images.githubusercontent.com/29661572/28671528-0282fffc-7318-11e7-8d13-843817af83be.png)
이와 같은 모습으로 특히 '연결이 재설정되었습니다.' 라고 뜹니다. adguard 보호 해제 시 정상 접속이 가능하네요.. KR 필터의 문제인지 adguard 의 문제인지는 모르겠습니다.

windows 10 education edition 64-bit, Chrome 버전 60.0.3112.78(공식 빌드) (64비트), list-kr 1.0.3.19 버전, adguard windows 버전 6.2.379.1984 사용 중입니다.

**Comment by nskzhd** [comment]
제가 한 일주일전에 겪었던문제랑 비슷해 보이는데... 
저도 pc에서 네이버관련 페이지들..블로그 까페 등이 연결이 자꾸 안되더군요.(아주 가끔 됨)

애드가드쪽에 문의메일 보내니..(로그포함)
필터가 너무 많이 켜져있다고 주요필터 몇개와 자주 사용하는 언어기반 필터만 켜고 나머진 다 꺼보라고 하더군요. 
(English filter / Spyware filter / Annoyances filter / Social media filter / Experimental filter)
그래서 보니깐 제가 켠 기억이 없지만.. 프랑스 독일 러시아 등등 잔뜩 켜져있더라구요. 그래서 다 끄고 다시 처음처럼 주요필터 몇개와 list kr만 켰더니..지금은 문제가 생기지 않고 있습니다.

**Comment by exp10it3r8** [comment]
해결되었습니다. 최근 버전부터 추가된 '설정->스텔스모드' 에 Strip URLs from tracking parameters 를 활성화시킬경우 네이버 블로그에 들어가지지 않습니다. 체크를 해제하니 정상 작동되네요. 해결되었으니 글은  닫겠습니다.

**Comment by DandyClubs** [comment]
전 스텔스 모드 사용을 안해서요. 사용하면 먼가 리다이렉트 사이트들이나 기타 사이트들이 제대로 안되는 현상이 있더라구요
