### ISSUE TITLE
안녕하세요 웹사이트 광고 차단 문의드립니다.

### ISSUE THREAD

**Issue by todayhumor** [SlowMemory/List-KR#168]
윈도우 10 64비트 사용중이고,
익스플로러 11과 엣지 사용중입니다.
![default](https://user-images.githubusercontent.com/27630015/28768630-53fbb286-7613-11e7-96ad-1ffe0e9edb4c.PNG)

해당 사이트 주소는 https://ttocorps.com/  이며 상단 및 양쪽 사이드바에 많은 광고가 있습니다. 잘 부탁드리겠습니다.

**Comment by SlowMemory** [comment]
제보 감사합니다. 필터 업데이트 후 확인 부탁드립니다.
