### ISSUE TITLE
안녕하세요 갑자기 PC에서 이상한 광고가 나옵니다.

### ISSUE THREAD

**Issue by todayhumor** [SlowMemory/List-KR#169]
![default](https://user-images.githubusercontent.com/27630015/29100626-a7bb27f0-7ce7-11e7-92de-b7c58d5edfc5.PNG)

윈도우 10 64비트인데, 백신을 여러개 설치했습니다.
상주 백신이  Avira,  Appcheck, Windows defender, ViRobot 그리고 Adguard 입니다.
최근 의심되는 프로그램이 ViRobot 또는 PC 카카오톡인데요. 
아래 이미지와 같은 광고가 바탕화면 우측 하단에서 발생합니다. 느낌이 PC 카톡 같다는 생각이듭니다.
거의 반필수 프로그램이라서 그냥 삭제하기는 좀 그런데.. 설치할때 뭔가 잘못된 동의를 선택한게 아닌지 좀 걱정됩니다.
이 부분도 Adguard 에서 차단이 될 수 있나요?

**Comment by SlowMemory** [comment]
원인이 카카오톡 pc 버전이라면, Adguard에서 해당 프로그램을 필터링하도록 설정하시면 됩니다. 카카오톡 pc버전을 필터링하도록 설정되어 있나요?

**Comment by todayhumor** [comment]
응용 프로그램 필터링에서 하면 되나보네요.
감사합니다.
