### ISSUE TITLE
안녕하세요 2가지 광고차단 문의드립니다.

### ISSUE THREAD

**Issue by todayhumor** [SlowMemory/List-KR#170]
먼저 PC 상에서의 광고 차단 말씀드립니다.
1. 윈도우 10 64비트, 브라우저는 MS 엣지 사용중입니다.
오늘(17.8.23) Daum.net에서 MLB 시청중에 우측 하단에 보여진 작은 광고창입니다. 

2. 노트5 마쉬멜로 버전 사용중입니다.
해당 광고의 원인은 뭐야이번호라는 앱인데, 한번씩 출력이 되더라구요. 

아참, 혹시 엣지 브라우저에서 확장 프로그램 중 애드가드가 있던데 그거랑 PC에 인스톨해서 쓰는거랑 같은 기능인건가요?(엣지브라우저만 쓸 경우에요)

**Comment by SlowMemory** [comment]
문제를 확인할 수 있는 정확한 url 과 광고의 스크린샷을 올려주시기 바랍니다.

**Comment by todayhumor** [comment]
네 감사합니다. 새로 글 올려서 이 글은 닫겠습니다.
