### ISSUE TITLE
다음카페 어플 인기글 탭도 애드가드 필터를 이용하여 무력화가 가능한가요

### ISSUE THREAD

**Issue by cjh980402** [SlowMemory/List-KR#171]
https://m.clien.net/service/board/lecture/11099227
저 글에선 필터를 이용하여 카카오톡 채널탭을 무력화했는데
다음 카페 어플 인기글 탭도 가능한가요?
가능하다면 해당 기능 필터를 알려주신다면 감사히 쓰겠습니다.

**Comment by SlowMemory** [comment]
`||api.m.cafe.daum.net/mcafe/api/v2/favorite/articles^` 필터를 사용해 보세요.

**Comment by cjh980402** [comment]
감사합니다. list kr 필터 항상 잘 쓰고있습니다.
