### ISSUE TITLE
안녕하세요 모바일에서 광고차단이 되질 않습니다.

### ISSUE THREAD

**Issue by todayhumor** [SlowMemory/List-KR#172]
얼마전 Gpro2에서 노트5로 바꾼 이후로 잘 안되는것 같습니다.
노트5 마쉬멜로 버전이고 브라우저는 삼성 기본 인터넷 브라우저 사용중입니다.
애드가드 모바일 버전은 최신 버전으로 업데이트는 17년 8월 30일 입니다.

1. 해당 광고의 원인은 "뭐야이번호"라는 앱인데, 한번씩 출력이 되더라구요.
![screenshot_20170822-182707](https://user-images.githubusercontent.com/27630015/29865527-b712aef6-8db0-11e7-8f32-4de992386496.png)

2.  애드가드 앱 자체가 빈번하게 작동이 되질 않습니다.
jorte 캘린더라는 앱에서 일정을 입력하는 창 아래 광고가 나옵니다.
![screenshot_20170826-015112](https://user-images.githubusercontent.com/27630015/29865664-078bc106-8db1-11e7-9311-76915b2658da.png)

3. 모바일 웹(삼성 기본 브라우저)으로 들어간 m.ppomppu.com  싸이트 광고차단도 안되는것 같습니다.
  http://m.ppomppu.co.kr/new/bbs_view.php?id=freeboard&no=5457099&page=1
![screenshot_20170830-183105](https://user-images.githubusercontent.com/27630015/29865999-029cd0d0-8db2-11e7-811d-0622a80ed5f8.png)

반면 같은 주소를  PC에서 가보면 또 차단이 됩니다.
![default](https://user-images.githubusercontent.com/27630015/29865868-a88b0544-8db1-11e7-8cea-cf9104126eb1.PNG)

애드가드를 껐다가 다시 재실행 하면 잠깐 되었는데, 이제는 그조차도 되질 않습니다. 

-카카오톡 PC 버전 윈도우 바탕화면 우측 하단 광고도 조만간 올리도록 하겠습니다.
-아참, 혹시 엣지 브라우저에서 확장 프로그램 중 애드가드가 있던데 그거랑 PC에 인스톨해서 쓰는거랑 같은 기능인건가요? 중복되는 거면 하나 안쓰려고 합니다.(엣지브라우저만 쓸 경우에요)

**Comment by todayhumor** [comment]
3가지 모바일 오류 자체 해결했습니다.
애드가드 지웠다가 재설치했습니다.
감사합니다.

혹시 엣지 브라우저에서 확장 프로그램 중 애드가드가 있던데 그거랑 PC에 인스톨해서 쓰는거랑 같은 기능인건가요? 중복되는 거면 하나 안쓰려고 합니다.(엣지브라우저만 쓸 경우에요)

**Comment by SlowMemory** [comment]
다른 기능입니다. 둘 중 하나만 쓰셔도 되고, 아마 둘 다 사용하시더라도 엣지 브라우저의 확장 프로그램은 자동으로 [integration mode](https://kb.adguard.com/en/browser-extensions/integration-mode) 로 전환되고 PC에 설치된 버전만 광고 차단을 하게 되는 것으로 알고 있습니다.
