### ISSUE TITLE
mlbpark 모바일 버젼 광고 차단이 불완전합니다.

### ISSUE THREAD

**Issue by diajw** [SlowMemory/List-KR#173]
인녕하세요. [엠엘비파크](http://mlbpark.donga.com/mp/b.php?b=bullpen) 모바일로 들어가면 맨밑에 항상 뜨거운 광고들이 보입니다. 혹시 가릴수 있을지요?

**Comment by SlowMemory** [comment]
안녕하세요, 해당 이미지는 `||dimg.donga.com/carriage/MLBPARK/cron/board_east/board_east_mlbpark.js^` 규칙을 추가하시면 차단이 가능합니다.

해당 이미지가 광고의 정의에 부합하지 않는 것 같습니다. mlbpark 사이트 이용자의 대다수가 해당 이미지를 광고로 느낀다면 차단하는 것을 검토할 수 있겠습니다.

**Comment by diajw** [comment]
규칙 따로 알려주셔서 감사드립니다. 광고가 아니라고 볼수도 있으니 원하는 사람만 따로 추가하는게 좋겠습니다. 좋은 하루 보내시기 바랍니다.
