### ISSUE TITLE
넥슨 게임 필터 관련

### ISSUE THREAD

**Issue by okmoon** [SlowMemory/List-KR#174]
넥슨에서 천애명월도란 게임을 실행하려고 하는데
계속 플레이 팝업창이 안 뜨더군요
그래서 로그를 봤더니
||js.nx.com/*/da/playlog.*min.js
해당 규칙이 실행을 막고 있었습니다
비활성화 시키니까 실행이 잘 되네요
빼거나 수정하시는 게 좋을 듯하여 적으러 왔습니다
조금이나마 좋은 필터 만드시는데 도움이 되실까 해서요
항상 잘 사용하고 있습니다! 감사합니다

**Comment by SlowMemory** [comment]
제보 감사합니다! 문제가 되는 규칙을 삭제하였으니 필터 업데이트 후 확인 부탁드립니다.
