### ISSUE TITLE
디시인사이드 웹 광고 차단시 공백이 남는 문제

### ISSUE THREAD

**Issue by hw0603** [SlowMemory/List-KR#175]
애드가드 PC버전 사용중인데 디시 웹에서 광고차단 활성화 시 캡쳐 사진과 같이 큰 공백이 남습니다. 어떻게 해결해야 할까요? 비슷한 이슈를 읽어보니 필터 업데이트가 필요한 듯 한데..

http://imgdb.kr/cnvQ

**Comment by SlowMemory** [comment]
안녕하세요, 광고가 아닌 페이지 요소가 차단되는 경우 그 요소를 차단하는 필터에 수정이 필요합니다.

제 기기에서 올려주신 스크린샷의 페이지 http://gall.dcinside.com/board/lists/?id=youjung 에 접속했을 때는 스크린샷에 표시해주신 공간에 개념글 목록이 정상적으로 표시됩니다.

List-KR 필터 외에 다른 어떤 필터를 사용하고 계신가요?

**Comment by hw0603** [comment]
우선 빠른 코멘트 감사합니다.
Adguard 이외에 "슬림디시" 라는 크롬 확장프로그램 CSS를 적용중이지만 IE에서도 동일 증상이 나타나는것으로 보아 CSS상의 문제는 아닌 것 같습니다.
필터는 기본으로 활성화되는 필터에 List-KR 필터 두개만 추가하여 사용중입니다. 현재는 글 목록 페이지에서만 애드가드를 일시 중지하는 구문을 추가해 사용중인데 당연하지만 이 경우에는 문제가 발생하지 않네요

+추가) 저 흰색 박스가 나타나는 현상 이외에도 디시 운영자측에서 작성한 공지글의 경우, 원래 볼드체로 "운영자"라는 닉네임이 나타나야 정상이지만 애드가드 사용 설정 시 공백처리되어 보이지 않습니다.

**Comment by SlowMemory** [comment]
제 기기에서는 말씀하신 두 현상 모두 재현되지 않습니다. 애드가드에는 기본으로 활성화되는 필터가 정해져 있지 않습니다. 처음 인스톨 시 튜토리얼에서 무엇을 클릭하느냐에 따라, 어떤 시스템 언어를 사용하는지 에 따라 기본으로 활성화되는 필터가 달라집니다. 활성화된 필터 목록을 알려 주셔야 재현이 가능합니다.

**Comment by hw0603** [comment]
List-KR unbreak
영어 필터
스파이웨어 필터
소셜미디어 필터
List-KR 입니다.

크게 문제될만한 필터는 사용하지 않는 것 같은데.. 이대로 설정하셔도 재현이 안되신다면 이슈를 닫아야겠네요ㅠㅠ
