### ISSUE TITLE
daum.net 에서 동영상 재생이 안됩니다.

### ISSUE THREAD

**Issue by ryubato** [SlowMemory/List-KR#177]
안녕하세요. 최근에 Adguard 를 구매해서 사용 중입니다.
daum.net 에서 스포츠란의 동영상 재생이 안되어 테스트 한 결과
List-KR 필터에 이슈가 있어 보입니다. 확인 요청드립니다.

OS: 윈도우 10
Browser: IE 엣지, 파이어 폭스
Site:  daum.net

**Comment by SlowMemory** [comment]
안녕하세요, 이외에도 카카오 tv 사이트의 동영상 재생 문제가 제보되어 관련 필터를 추가하였습니다. 필터를 업데이트 하시고 여전히 문제가 발생하는지 확인 부탁드립니다.
