### ISSUE TITLE
넹버 모바일 쇼핑몰 연결 문제

### ISSUE THREAD

**Issue by beauami** [SlowMemory/List-KR#179]
https://m.search.naver.com/search.naver?query=안국+루테인+플러스&where=m&sm=mtp_sly.hst&acr=3

ios safari adguard pro

모방ㄹ 네이버에서 검색 후 쇼핑몰 연결시 차단되어 연결이 안되는 증상이 종종 있습니다.

**Comment by SlowMemory** [comment]
안녕하세요, 문제 재현에 어려움이 있습니다. 사용 중이신 필터 목록을 알려주실 수 있으신가요?
또, 다음 두 규칙을 사용자 필터에 직접 추가하셨을 때 문제가 해결되는지 확인 가능하신가요?
```
@@||cc.naver.com^

@@||adcr.naver.com^
```

**Comment by beauami** [comment]
안녕하세요.

잘 됩니다!!

빠른 답변 감사드립니다.

2017년 10월 12일 (목) 오후 1:36, SlowMemory <notifications@github.com>님이 작성:
