### ISSUE TITLE
광고가 차단되지 않은 웹사이트 주소입니다.

### ISSUE THREAD

**Issue by tmddlfdl23** [SlowMemory/List-KR#181]
[https://tczoa.info/](https://tczoa.info/)

해당사이트에 차단되지 않은 광고가 있습니다.
부탁드립니다.
![default](https://user-images.githubusercontent.com/32754854/31526322-0c8b2b0c-b001-11e7-8187-476f333cdc2e.png)

**Comment by SlowMemory** [comment]
제보 감사드립니다. 필터 업데이트 후 확인 부탁드립니다.

**Comment by tmddlfdl23** [comment]
제대로 차단이 되고있습니다. 
항상 감사드립니다.
