### ISSUE TITLE
네이버 모바일 게임 카테고리 광고

### ISSUE THREAD

**Issue by zxc132** [SlowMemory/List-KR#183]
게임 카테고리에서 나오는 광고 차단
m.naver.com##DIV[class='cui_thumbtext ct_ad_premium']

**Comment by SlowMemory** [comment]
안녕하세요, 제 측에서는 네이버 모바일 홈페이지에서 해당 규칙으로 가려질 만한 요소가 없습니다. 광고가 나타난 스크린샷을 올려주실 수 있으신가요?
