### ISSUE TITLE
차단이 되지 않는 사이트네요.

### ISSUE THREAD

**Issue by proplcy** [SlowMemory/List-KR#186]
https://www.totomi.co/

가끔 광고 꺼달라는거 보면 그냥 그걸 차단시키면 되는데 아예 사이트를 이동시켜버리니... 어찌해야 할지 모르겠네요.

**Comment by SlowMemory** [comment]
제보 감사합니다. 필터 업데이트 후 확인 부탁드립니다.

일반적으로, 어떤 사이트에서 광고 차단을 감지한다면 
 - 페이지의 요소 차단을 `@@||totomi.co^$elemhide` 등의 규칙을 사용자 필터에 추가하여 해제
 - 필터링 로그에서 차단된 것으로 나타나는 네트워크 요청을 하나씩 허용
를 광고 차단이 감지되지 않을 때까지 반복하시면 됩니다. 단 이는 말 그대로 광고를 허용하는 것이기에 결과적으로 광고가 나타날 수 있습니다.

**Comment by proplcy** [comment]
감사합니다~ 필터 업데이트 후 정상적으로 차단이 됩니다. 추후에 다른 사이트에서 광고차단을 발견하게 된다면 한번 해보겠습니다
