### ISSUE TITLE
Adguard Content Blocker에 대해 여쭤볼 수 있을까요?

### ISSUE THREAD

**Issue by yjysgpif6662** [SlowMemory/List-KR#188]
저는 모바일 기기에서 홈페이지에서 받는 Adguard가 불편해서 삼성 브라우저랑 연동되는 Adguard Content Blocker를 사용 중입니다.

근데 이건 PC버전이랑 비교하면 너무 애로사항이 많더군요

네이버 같은 곳에서의 동영상 광고 차단이나 성인 배너 또는 팜업 광고처럼 악질적인 광고 차단, 또는 PC버전의 요소차단 기능 같은 것 말이죠

요소차단이야 앱 제작자분들이 기능을 만들어 주셔야 되는 문제니 어쩔 수 없지만, 네이버 같은 곳의 동영상 광고나 팝업팝 광고, 성인배너 같은 것들은 유니콘 앱에서는 다 차단이 되던데  어떻게 해결할 방법이 없을까요?

덤으로 인터넷에 찾아보니
"다른 광고차단 프로그램들은 브라우저에 한해서 광고를 필터링한다면, Adguard는 아예 시스템 네트워크 레벨에서 광고를 필터링해버린다."
라던데 Adguard Content Blocker도 마찬가지인지와 유니콘 앱은 어느쪽에 속하는지도 알고 싶습니다

**Comment by SlowMemory** [comment]
1. 차단되지 않은 광고가 있다면, 어떤 페이지에서 나타나는지 스크린샷과 함께 제보해주시면 본 List-KR 필터의 업데이트를 통해 차단됩니다.

2. 제 기기에서는 네이버 측에서 말씀하신 바와 같은 "악질적인 광고" 가 나타나지 않아, 무엇을 말씀하시는지 알기 어렵습니다.

3. 언급하신 유료 애플리케이션 또한 삼성 브라우저의 "컨텐츠 차단 api" 를 이용하여, Adguard Content Blocker와의 차이는 없습니다. 인용하신 Adguard에 대한 설명은 pc 버전이나 시스템 레벨 광고 차단을 하는 Adguard 안드로이드 버전에만 해당됩니다.

**Comment by yjysgpif6662** [comment]
그렇군요 
답변 감사합니다
