### ISSUE TITLE
고파스 관련 제보입니다

### ISSUE THREAD

**Issue by WingsK** [SlowMemory/List-KR#190]
안녕하세요.

고려대학교 커뮤니티 사이트인 고파스에서 총 4개의 광고가 표시되고 있습니다. 요소 차단 후 편집기 규칙 첨부했습니다.

koreapas.com##DIV:nth-child(8) > TABLE:first-child > TBODY > TR:nth-child(2) > TD:last-child > A:last-child > IMG
koreapas.com##DIV:nth-child(11) > TABLE:first-child > TBODY > TR > TD:nth-child(2) > A:last-child > IMG
koreapas.com##DIV:nth-child(11) > TABLE:first-child > TBODY > TR > TD:last-child > A:last-child > IMG
koreapas.com##DIV:nth-child(11) > TABLE:nth-child(5) > TBODY > TR:first-child > TD:first-child > TABLE > TBODY > TR:last-child > TD > A:last-child > IMG

또한 웹 페이지를 다른 이름으로 저장한 파일 역시 첨부했습니다. 감사합니다.
[[고파스]_files.zip](https://github.com/SlowMemory/List-KR/files/1449543/_files.zip)

**Comment by SlowMemory** [comment]
제보 감사합니다. https://koreapas.com 으로 접속했을 때 나타나는 메인 화면의 광고를 차단하도록 업데이트 하였으며 오래된 규칙을 제거하였습니다. 필터 업데이트 후 확인 부탁드립니다.
