### ISSUE TITLE
네이버 로그인 부분이 생략됩니다.

### ISSUE THREAD

**Issue by snowphone** [SlowMemory/List-KR#191]
![image](https://user-images.githubusercontent.com/23140464/32588237-b1b88098-c550-11e7-807c-e6efc63a882d.png)

위와 같이 list-kr 사용시에 로그인 부분이 생략되어버립니다.

Adguard에서 English filter와 LIST-KR만 사용중입니다.

**Comment by SlowMemory** [comment]
이상하네요. 제 기기에서는 그러한 현상이 나타나지 않으며 해당 요소를 차단할 만한 규칙도 없습니다.
혹시 '스텔스 모드' 를 사용 중이시라면 사용 중지해 보시고,
필터를 최신 버전으로 업데이트, '사용자 필터' 사용 해제, 브라우저 캐시 삭제 후 확인 부탁드립니다.
여전히 문제가 발생한다면,
규칙 `@@||naver.com^$elemhide` 를 사용자 필터에 추가하신 후 로그인 섹션이 차단되는 문제가 해결되는지 확인 부탁드립니다.
