### ISSUE TITLE
케이툰에서 웹툰 내용이 안나옵니다.

### ISSUE THREAD

**Issue by hijae** [SlowMemory/List-KR#196]
https://v2.myktoon.com/web/works/viewer.kt?timesseq=118755
내용이 안뜨는 중입니다.

**Comment by SlowMemory** [comment]
제보 감사합니다! 다음 광고 관련 리소스를 차단할 시 광고 노출 API를 호출하는 코드에서 오류가 발생하여 이후 코드가 실행되지 않는 문제가 있었습니다. 필터 업데이트 후 문제가 해결되었는지 확인 부탁드립니다.
