### ISSUE TITLE
네이버 뉴스에 차단되지 않는 광고 제보합니다.

### ISSUE THREAD

**Issue by tmddlfdl23** [SlowMemory/List-KR#201]
다른부분은 다 차단이 되는데
'뉴스' [http://news.naver.com/](url) 의 우측에 하나
'스포츠' [http://sports.news.naver.com/index.nhn](url) 의 우측 중간에 두개

부분만 차단이 되질 않습니다.

![222](https://user-images.githubusercontent.com/32754854/34282029-09ff6150-e706-11e7-9f9c-6069d07d13e9.png)

![11](https://user-images.githubusercontent.com/32754854/34282028-092d3a7c-e706-11e7-9b43-47b7bb0eacda.png)

**Comment by SlowMemory** [comment]
제보 감사드립니다. 필터 업데이트 후 확인 부탁드립니다.

**Comment by tmddlfdl23** [comment]
업데이트 후 차단이 정상적으로 되고 있습니다.
항상 감사드립니다.
