### ISSUE TITLE
네이버 카페 댓글 이미지 오른쪽 클릭

### ISSUE THREAD

**Issue by Mo-norn** [SlowMemory/List-KR#205]
![screenshot 2017-12-27 at 22 42 30](https://user-images.githubusercontent.com/34658160/34384035-f89104fe-eb5c-11e7-8f29-df24d7e7e6c1.png)

댓글에 이미지 오른쪽 클릭하면  무반응, 이미지 클릭하여 오른쪽 클릭하면 '마우스 오른쪽 버튼은 사용할 수 없습니다. ' 메시지 발생합니다.

**Comment by SlowMemory** [comment]
문제가 발생하는 페이지의 주소를 알려주시면 감사드리겠습니다.

**Comment by Mo-norn** [comment]
Absolute Enable Right Click & Copy 확장 스크립트로 해결했는데요.
pc버전으로 네이버 카페 댓글 그림은 다 동일한 현상입니다. 글이 아닌 '댓글'이고요.

**Comment by SlowMemory** [comment]
필터 업데이트 후 확인 부탁드립니다.

**Comment by Mo-norn** [comment]
아 이게 같은 카페라고 해도 다 다른가봐요. 
카페글 검색으로 댓글 이미지는 저도 오른쪽 클릭이 되는데요. 제가 원하는 카페는 안됩니다.
그래서 카페 가입이 필요 없는 사이트를 또 찾았는데요. 여기는 글이랑 댓글 둘다 안됩니다.
http://cafe.naver.com/fincih/186998

**Comment by SlowMemory** [comment]
위 커밋에서 추가한 규칙들로 현재 문제가 해결된 것 같습니다.
