### ISSUE TITLE
29cm 상품 후기, 상품 Q&A등 내용 안보임.

### ISSUE THREAD

**Issue by Mo-norn** [SlowMemory/List-KR#207]
사이트: http://www.29cm.co.kr/

![screenshot 2018-01-01 at 19 55 23](https://user-images.githubusercontent.com/34658160/34467206-d9ef9ef0-ef2d-11e7-9bf9-e7a55526922d.png)

-  상품 후기 Q&A 내용 차단합니다.

![screenshot 2018-01-01 at 19 56 00](https://user-images.githubusercontent.com/34658160/34467207-da2b448c-ef2d-11e7-847c-76858fbdaf6c.png)

List-KR의 ' ||megadata.co.kr^$third-party' 차단 해제 후 내용 나옵니다.

**Comment by SlowMemory** [comment]
제보 감사합니다! 필터 업데이트 확인 부탁드립니다.

**Comment by Mo-norn** [comment]
네 확인하였습니다. 잘 되네요.
