### ISSUE TITLE
판도라  TV 광고차단되어서 영상이 나오지 않는다고 하네요.

### ISSUE THREAD

**Issue by DandyClubs** [SlowMemory/List-KR#209]
어제까지는 멀쩡했는데요.

오늘부터 영상이 안나오네요.

광고 차단 프로그램이 실행되어 있는 경우 영상 시청이 불가능합니다.

이런 메세지만 출력되더군요.

해외사이트 검색해보니..

@@||imasdk.googleapis.com/js/sdkloader/ima3.js$domain=m.pandora.tv

위와 같은 필터가 있어서.. 모바일 전용인듯 하여..

사용자 필터에

@@||imasdk.googleapis.com/js/sdkloader/ima3.js$domain=pandora.tv

위와 같이 추가해주긴 했습니다.

영어필터에 위가 같이 차단하는 필터가 있어서 이 때문인 것으로 파악됩니다.

||imasdk.googleapis.com^$third-party

**Comment by SlowMemory** [comment]
제보 감사합니다. 말씀하신 필터가 가장 적합한 해결책이라 판단되어 그대로 필터에 추가하였습니다.
