### ISSUE TITLE
클리앙 사이트 광고 계속 떱니다. 

### ISSUE THREAD

**Issue by super3023** [SlowMemory/List-KR#210]
https://www.clien.net/   

Ad site address

Include symptoms photo.

https://www.clien.net/service/board/cm_andro/11668828

클리앙 사이트 인데 광고는 막아 주는데 빈칸이 생깁니다. 그리고 일부 광고도 계속 나옵니다. 
사진 공유할려고 하니 제대로 않되네요!. 현재 모바일만 그렇습니다. 

클리앙 사이트 게시글에 올려 뒀습니다. 링크 했으니 제발 좀 고쳐 주세요!..
스트레스 엄청 쌓입니다. 제발 
감사합니다.

**Comment by SlowMemory** [comment]
안녕하세요, 올려주신 이슈를 확인하였을 당시 링크하신 클리앙 게시글에 이미 문제가 해결되었다고 올려 주셔서 추가로 댓글을 달지 않았습니다.

댓글에 '단순화된 도메인 네임 필터' 를 체크하셨다고 하셨는데요, 해당 필터는 애드가드 앱을 DNS 레벨 광고차단 용도로 사용할 때만 의미가 있는 필터이며, 핕터 내용 자체는 '영어 필터', '스파이웨이 필터' 와 중복되어, 이를 체크 해제하셔도 될 것 같습니다.
