### ISSUE TITLE
네이버 TV캐스트

### ISSUE THREAD

**Issue by nagato7** [SlowMemory/List-KR#46]
iOS Adguard에서 List-KR을 사용하고 있는데, 네이버 TV캐스트에서 동영상 부분 인터페이스가 아예 사라져서 검은 빈칸으로만 남아 있습니다. 역사를 보니 최근 tvcast.naver.com 스크립트를 바꾸셨는데 이것 때문인가 싶기도 하네요.

범용 필터로 기획되었으므로 특정 환경에 대해 예외처리가 어렵다면 할 수 없습니다만, 혹시 다른 솔루션이 있을 수도 있어 일단 문의드립니다.

**Comment by SlowMemory** [comment]
안녕하세요, 제보 감사드립니다!

먼저 제게 iOS 기기가 없어서 직접 테스트를 해 보기가 어려운 점 양해 부탁드립니다. 그래도 할 수 있는 한 최대한 해결하도록 해보겠습니다.
우선 다음 필터를 사용자 지정 필터에 추가하신 후 동영상 재생이 되는지 확인해주실 수 있으신가요?

`
@@/wcslog.js
`
이 규칙은 이미 포함되어 있어야 하는 규칙이지만, Adguard측에서 아직 포함시키지 않았을 가능성이 있어 확인을 요청드립니다.
만약 여전히 동영상 재생이 안 된다면, 다음 규칙을 추가하였을 때는 어떤지 확인해주시면 감사하겠습니다.
`
@@||smartmediarep.com
@@||dn.naver.com
`

최근 변경한 부분은 iOS 버전에는 적용되지 않는 규칙입니다. 동영상 광고의 정보를 불러오는 파일에서 광고 정보를 지우는 규칙이며 애드가드 윈도우, 맥, 안드로이드 버전에서 지원되고, iOS에서는 content blocker API의 한계로 지원되지 않습니다.

**Comment by nagato7** [comment]
`@@/wcslog.js`

를 사용자 필터에 추가하면 정상적으로 로딩하는군요.

**Comment by SlowMemory** [comment]
확인 감사합니다. 현재 필터에서 네이버 애널리틱스 관련 스크립트를 차단하고 있는데, 이 스크립트에서 정의하고 있는 변수를 페이지의 다른 스크립트에서 불러오는 경우 그 스크립트 전체가 실행되지 않는 경우가 있더군요. 애드가드 타 버전에서는 JS 삽입으로 해결하고 있지만 iOS나 ublock origin 에서는 지원되지 않아 unbreak.txt 파일에 이들을 위한 예외 필터를 포함시키고 있습니다. 애드가드 측에 이 필터를 포함시키도록 요청해놓았습니다. 당분간은 이 예외 규칙을 추가해주시고 추후 필터가 업데이트 되면 제외하시면 될 것 같습니다.

추가로 위의 규칙 대신
```
@@||wcs.naver.net/wcslog.js
```
을 추가하여도 문제가 해결되는지 확인해주시면 감사드리겠습니다.

**Comment by nagato7** [comment]
`@@||wcs.naver.net/wcslog.js`

를 추가해도 영상이 작동합니다.

**Comment by SlowMemory** [comment]
확인 감사합니다!
