### ISSUE TITLE
네이버 캐스트 광고

### ISSUE THREAD

**Issue by joyfuI** [SlowMemory/List-KR#47]
naver-smr.smartmediarep.com 뿐만 아니라 smrmembers-smr.smartmediarep.com도 생겼습니다.
주소명을 보면 앞으로도 *-smr.smartmediarep.com 같은 식으로 계속 추가될듯하네요.

**Comment by SlowMemory** [comment]
제보 감사합니다! joyful님께서 제보해주신 url이 실제로 나타남을 확인하였고 4ed1ff3b5ef25b7c05cb9e4126e203a237e1437e 에서 포함시켰습니다.

말씀하신 좀 더 일반적인 규칙도 고려하고 있으나, 아직 해당 규칙이 광고만을 제거할 지 확실치 않아 일단은 좀 더 지켜봐야 할 것 같습니다. 비슷한 광고 주소를 또 발견하시면 알려주시길 부탁드립니다.

+) 혹시 ublock origin을 쓰고 계시다면 unbreak.txt도 추가하여 사용하시는 걸 추천합니다. 일부 Adguard용 규칙에 대한 보충으로, 이러한 규칙이 적용되지 않는 광고 차단기에서 몇몇 사이트가 깨지는 것을 방지하는 규칙으로 이루어져 있습니다.
