### ISSUE TITLE
Coolenjoy 이미지 표시 불가

### ISSUE THREAD

**Issue by swan201** [SlowMemory/List-KR#48]
http://www.coolenjoy.net/bbs/28/2524988

해당게시물의 이미지가 광고차단기 사용시 보이지 않네요

IE11 Insider Preview, Adguard 6.1 사용중입니다.

**Comment by SlowMemory** [comment]
문제되는 규칙을 삭제하였습니다. 필터를 업데이트 하시고 확인 부탁드립니다.
현재 쿨앤조이 홈페이지에서 상단 배너, 우측 스폰서들의 띠배너를 모두 가리고 있는데, 이에 대해서도 건의사항 있으시면 말씀해주세요.

**Comment by swan201** [comment]
상단배너와 우측의 띠배너는 공백이 오히려 배경역할을해서 좋은것 같습니다 다만 좌상단의 배너삭제로 인한 메뉴위의 공백은 제거되면 보기에 일괄적으로 보일것 같네요. 

+ 우측 띠배너는 게시물메뉴에서 광고창이 뜹니다

**Comment by SlowMemory** [comment]
좌상단 공백을 줄이도록 업데이트 하였습니다.

게시물 페이지에서 우측 띠배너가 뜨는 현상은 저도 몇번 경험했는데요, 차단하는 규칙은 이미 있고 브라우저 캐시 문제가 아닐까 싶습니다. 몇 번 페이지 전환을 해 보시거나 캐시 삭제를 하시고 다시 확인해보세요.

제보, 제안 감사드립니다!

**Comment by DandyClubs** [comment]
저의 경우는 광고라기 보단 바로가기 수준인지라.. 허용해서 사용하고 있습니다.
