### ISSUE TITLE
Youtube App 광고차단 실패

### ISSUE THREAD

**Issue by swan201** [SlowMemory/List-KR#49]
현재 웹브라우징을 통한 Youtube 광고는 전부 차단(PC,모바일 동일) 되는걸로 확인되나 Youtube 앱을통한 광고는 차단이 되지 않는것 같네요.

**Comment by SlowMemory** [comment]
유튜브 광고의 경우 앱의 자체 필터에서 다루어져야 하는 문제입니다. Adguard앱의 피드백 기능을 통해 제보해보시는 것을 추천합니다.

하지만 다음을 체크해보실 수 있을 것 같습니다.

 - YouTube 앱의 광고는 https 연결을 통해 전송된다고 합니다. Adguard 설정에서 https 필터링을 사용하도록 설정해주셔야 합니다. 앱의 설정 -> HTTPS filtering 에서 Install certificate 와 Filter HTTPS connections 옆에 체크되어있는지 확인해보세요.
 - 안드로이드 설정에 들어가셔서 YouTube 앱의 캐시와 데이터를 삭제하시고 시도해보세요. 제 경우에는 이렇게 해서 해결된 적이 있었습니다. YouTube 앱에서 광고를 미리 다운받아놓는 것 같습니다.

물론 유료버전을 사용하는 경우에 한합니다. 이렇게 해도 광고가 새어나온다는 유저들이 있고, 관련해서 앱 개발자측에서 네트워크 로그 파일을 받아서 필터를 업데이트 하고 있는 것으로 알고 있습니다.

**Comment by swan201** [comment]
캐시삭제후 정상작동하네요 감사합니다
