### ISSUE TITLE
danawa.com 상품의견 페이지 클릭이 안되는군요.

### ISSUE THREAD

**Issue by DandyClubs** [SlowMemory/List-KR#50]
다나와 상품의견에서 1 2 3 4 등등 페이지 이동 관련 자바스크립트 이벤트가 안되는군요.

이것과 관련된 자바스크립트가 차단되어서 그런것으로 보여집니다.

테스트는 크롬과 파폭에서 uBlock Origin v1.7.6으로 테스트 했습니다.

@@||static.danawa.com/js/logger_trackEvent.js$script,first-party 임으로 이걸 허용해주니 상품의견 페이지 이동이 되는군요.

**Comment by SlowMemory** [comment]
제보 감사합니다! 말씀하신 스크립트를 차단하지 않도록 업데이트 하였습니다. logger_trackEvent.js에서 정의하는 함수를 페이지 이동시 호출되는 함수에서 불러오는 것 같더군요. 아예 logger_*.js 규칙을 지울까도 생각했지만 나머지 js는 다른 스크립트에서 호출되는 경우가 없는 듯 하여 그대로 두었습니다.

필터를 업데이트 하시고 확인 부탁드립니다.
