### ISSUE TITLE
여기다 수정 사항 요청드리면 되나요?

### ISSUE THREAD

**Issue by chickendul** [SlowMemory/List-KR#52]
올려주셔서 잘 쓰고 있는데, 네이버 티비캐스트 이용시에 댓글창이 로드되지 않는 문제가 발생합니다.

크롬에 uBlock Origin을 사용했구요 문제가 되는 규칙은 다음과 같았습니다.

tvcast.naver.com/resources/*/clickcr_*.js^

이 규칙을 제거하고 사용하면 정상적으로 이용됨을 확인하였습니다.

**Comment by SlowMemory** [comment]
네 이곳에 올려주시면 됩니다! 해당 문제는 ublock origin에서 unbreak.txt를 사용하시면 해결됩니다. 필터를 추가하실 때 `https://github.com/SlowMemory/List-KR/raw/master/filter.txt`
 와 함께 `https://github.com/SlowMemory/List-KR/raw/master/unbreak.txt `도 추가해주세요. 아마 이 부분이 안내가 덜 되어서 혼란이 조금 있을 것 같네요.
