### ISSUE TITLE
m.dic.naver.com (모바일 네이버 사전 페이지) 검색 불가 문제

### ISSUE THREAD

**Issue by tgpark** [SlowMemory/List-KR#53]
naver.com#%#if (window.addEventListener) { window.addEventListener('DOMContentLoaded', function() { window.clickcr = window.nclk = function() { }; } ); }

m.dic.naver.com에서 검색을 실행할 때 nclk() 실행하는데 위 필터 때문에 검색이 되지 않습니다.

저는 임시로
naver.com#%#if (window.addEventListener) { window.addEventListener('DOMContentLoaded', function() { window.clickcr = window.nclk = function() { }; } ); }$domain~=m.dic.naver.com
수정해서 검색 가능하게 했습니다. 
adguard 필터 작성 룰은 생소한 관계로 확인하시고 맞게 수정해주셨으면 좋겠습니다.

**Comment by SlowMemory** [comment]
제보 감사합니다!

네이버 모바일 사전 페이지에서 사용되는 코드 중 이 nclk 함수와 얽혀있는 코드가 많은 것 같아 nclk를 수정하지 않도록 임시로 변경했습니다. 되도록 사용자 정보 수집을 차단하고 싶은데, 이 경우 어떻게 하면 좋을지는 더 생각해봐야 할 것 같습니다.

저도 정확히는 모르지만, #%# 규칙은 #%# 뒤에 오는 스크립트를 그대로 페이지 <head>부분에 삽입하는 것으로 알고 있습니다. $domain= 은 url 차단 규칙에서 사용되는 옵션이고, 이 경우에는 아마 자바스크립트 문법 에러로 취급되어 규칙 전체가 실행되지 않았을 듯 합니다.
