### ISSUE TITLE
Edge에서 pgr21 광고 차단이 안 됩니다.

### ISSUE THREAD

**Issue by Cassius99** [SlowMemory/List-KR#54]
게시판을 눌러서 들어가면 글과 댓글 사이에 보이는 광고가 Edge에서 차단이 되지 않습니다.
IE11에서는 잘 차단되는데 Edge에서만 안 되네요. 아무래도 Adguard 자체의 문제인 것 같지만 일단 남겨봅니다.

**Comment by Cassius99** [comment]
![pgr](https://cloud.githubusercontent.com/assets/20850210/18051613/93967aac-6e30-11e6-9064-36c7ec203a18.png)

**Comment by SlowMemory** [comment]
올려주신 스크린샷에 나타나는 광고는 구글 광고로 애드가드의 영어 필터에서 차단이 되어야 합니다. 혹시 엣지 브라우저의 필터링이 꺼져있는 것은 아닌가요? 
- 영어 필터가 활성화되어 있는지,
- 앱 필터링 -> 필터링 중인 앱 목록에서 Microsoft Edge에 체크가 되어 있는지,
- 일반 설정 -> WFP 네트워크 드라이버 사용에 체크가 되어 있는지 확인해주세요.
- 또 엣지 브라우저에서 TCP fast open 기능을 사용하고 계신지도 확인 부탁드립니다. 확인하는 방법은 http://www.tenforums.com/attachments/tutorials/89987d1468437257-microsoft-edge-tcp-fast-open-enable-disable-windows-10-a-microsoft_edge_tcp_fast_open.png 를 참조하세요.
- 마지막으로 트레이 아이콘에서 애드가드가 꺼져 있는 것은 아닌지 -_- 도 한번 확인해볼만 한 것 같습니다.

**Comment by Cassius99** [comment]
WFP Network Driver 옵션을 활성화하니까 잘 차단되네요. 감사합니다.
