### ISSUE TITLE
clien.net 모바일 본문 광고 변경

### ISSUE THREAD

**Issue by nagato7** [SlowMemory/List-KR#55]
클리앙 모바일 본문 하단 광고가 변경되어서 이전 룰로 차단되지 않습니다. ([예시](http://m.clien.net/cs3/board?bo_table=news&bo_style=view&wr_id=2229572&page=&spt=-77897))

![example](http://i.imgur.com/5HOyaHr.png)

**Comment by SlowMemory** [comment]
제보 감사합니다! 43c9900 에서 반영하였습니다.
