### ISSUE TITLE
TVCast Naver

### ISSUE THREAD

**Issue by p1nkyy** [SlowMemory/List-KR#56]
Hello, I'm not Korean but I enjoy watching some clips in Naver. Could you help remove the ads that's played before each videos? Sample: http://tvcast.naver.com/v/1101507/list/91592
Thank you before!

**Comment by SlowMemory** [comment]
Hi, are you actually using this filter? If not, you can follow the instructions in [README.md](https://github.com/SlowMemory/List-KR/blob/master/README.md) to add it. Preroll video ads in tvcast.naver.com are already being blocked by this filter, although I am aware that there are people reporting some ads from ad servers that they recently started to use.

If you are already using it, can you indicate the browser and the adblocker you are using? Also how often does the preroll ad shows up on your end? Answers for those would help troubleshooting the issue.

**Comment by p1nkyy** [comment]
Hello, so sorry I didn't check before I write this issue, I have subscribed to several Korean adblock filters to get rid of the video ads and only you so far who have responded. I'm in FF 48.0.2, I'm using ABP 2.7.3 but it said your filter failed, not a valid filters list). Thank you for responding btw.
The video ads have always being shown in my browser.

**Comment by SlowMemory** [comment]
My filter supports Adguard and ublock origin. All filter rules are in Adguard's syntax, ublock origin will ignore it if it cannot understand, and ABP will throw a parse error.

**Comment by p1nkyy** [comment]
Thank you, that's very kind of you and sorry to post in the wrong place since I've never used your filter in the first place.
However, the filters above caused the video to never be played. After I deleted one of them:
||naver-smr.smartmediarep.com^
the video played but the video ads is still there >.<

**Comment by SlowMemory** [comment]
It's okay to post such questions here. 

Regarding the issue that video does not play, there are several solutions:

- Use Chrome.
- Use a browser extension that can spoof your browser's user agent string to change it to that of IE or Opera.
- Use Adguard Windows/Mac/Android version, which support $replace rules.

It looks like Naver tvcast uses different video serving systems in some browsers that make the video won't play if a loading of a preroll ad failed. On my end with Firefox, the video you provided (http://tvcast.naver.com/v/1101507/list/91592) is played with the new system. 
tension that can spoof your browser's user agent string to change it to that of IE or Opera.
- Use Adguard Windows/Mac/Android version, which support $replace rules.

It looks like Naver TVcast uses different video serving systems in some browsers which throws a "network error" and stops the player if a loading of a preroll video ad failed. On my end with Firefox, the video you provided (http://tvcast.naver.com/v/1101507/list/91592) is played with the new system.

Adguard can filter such ads with $replace rules.

**Comment by SMed79** [comment]
`||smartmediarep.com^*.mp4|`

**Adblock Plus** with the filter above block the preroll video ads for me in all cases.

https://forums.lanik.us/viewtopic.php?f=62&t=24297

**Comment by SlowMemory** [comment]
@SMed79 Thanks, I haven't think about the idea using ```.mp4|```. So far it is distinguishing ad vods and main contents well, but I'm not sure.
Also, this does not resolve the issue with the OP that video is not playing in FF. I have tried your rule with Adblock Plus but no avail.
There are many people reporting that merely blocking the ad vod occasionally breaks video playback in FF. It will breaks some videos in Chrome too, but it is less often.

**Comment by SlowMemory** [comment]
@p1nkyy Have you checked solutions above?

**Comment by p1nkyy** [comment]
Hello @SlowMemory , unfortunately didn't work at all for me

**Comment by SlowMemory** [comment]
Have you tried with Chrome and ABP?

**Comment by p1nkyy** [comment]
I'm a bit touched that you keep following this up :')
My main browser is FF, never use GC unless a job specifically told me to. So in the mean time, I'll just bear with the ads. Gonna close this issue since it's not the fault of your filter in the first place anyway. Thanks so much @SlowMemory!
