### ISSUE TITLE
디시인사이드 popkonTV 광고 차단 요청합니다.

### ISSUE THREAD

**Issue by BGKG** [SlowMemory/List-KR#57]
김유식 대장은 짤방이 없는 게시물에 사용자 동의 없이 강제로 재생되는 동영상 광고를 도입했습니다. 심지어 모바일 버전에서도 동영상이 강제 재생됩니다. 이는 사용자들의 소중한 데이터를 낭비하게 합니다.

저는 다음  필터를 추가하여 사용중입니다.
||m.dcinside.com/event/video_play_ad.html

![1](https://cloud.githubusercontent.com/assets/19350190/18695524/6489d0be-7fed-11e6-86aa-4dfd9b83332c.jpg)
링크 : http://gall.dcinside.com/board/view/?id=rlike&no=59370
필터 추가 전, 후 스크린샷 입니다.
이 필터의 문제는 PC버전에서만 위 스샷과 같이 광고가 있던 자리가 크게 비어있게 됩니다.

List-KR에도 위 필터 혹은 이보다 더 나은 필터가 추가되길 바랍니다. 

사용중인 브라우저
PC : firefox
Mobile : 삼성 브라우저

**Comment by SlowMemory** [comment]
우선 
```
||dcinside.com/event/video_play_ad.html^
추가했습니다. 제 경우에는 이 규칙 사용시 광고가 있던 자리까지 없어지는데 혹시 어떤 광고차단 소프트웨어를 사용하고 계신가요?

모바일 웹에서는 팝콘tv 광고가 나오는 경우를 찾지 못했습니다. 예를 하나만 들어주실 수 있으실까요?

**Comment by BGKG** [comment]
PC로는 firefox 확장 프로그램 버전 Adguard 필터를 사용하고 있습니다. 스크린샷과 같은 링크로 모든 필터를 끄고 List-KR 필터만 키고 다시 실험해봤습니다. 결과는 그대로 공백이 남아있었습니다.

모바일 버전으로 다시 확인하고 몇 가지 사실을 알아냈습니다. 몇몇 갤러리에는 팝콘tv 광고가 나오지 않았습니다. 물고기 갤러리나 식물갤 같은 갤러리에는 나오지 않더라고요. 또 갤러리 별로 광고가 나올 확률이 다른 것 같았습니다. 또한 광고가 나왔던 글일지라도 다시 그 글을 열어보면 광고가 나오지 않기도 했습니다. 아래 사진의 월드 오브 탱크 갤러리에서는 높은 확률로 나왔습니다. 

![2](https://cloud.githubusercontent.com/assets/19350190/18703823/8967f002-8022-11e6-8d52-dd05a877579f.jpg)

링크: http://m.dcinside.com/view.php?id=worldoftanks&no=2661350&page=1
모바일 환경은 삼성 브라우저, vpn을 사용하는 Adguard 무료 버전입니다.

**Comment by SlowMemory** [comment]
파이어폭스 확장 프로그램에서 제 필터를 쓰신다면 버전이 2.4.9 이상이실 듯 하네요.
최근 Adguard 확장 프로그램 업데이트 중 iframe이 제대로 차단되지 않는 버그가 있었습니다. 글쓴님의 경우에도 아마 이 버그 때문에 빈 공간이 남는 것일 듯 하네요. https://addons.mozilla.org/en-US/firefox/addon/adguard-adblocker/versions/ 에서 최신 2.4.13버전을 설치하시면 해결됩니다.

모바일에서도 똑같이 http://m.dcinside.com/event/video_play_ad.html 를 통해 동영상 광고가 들어오고 앞서 추가한 규칙으로 차단되는 것으로 보입니다.

**Comment by BGKG** [comment]
2.4.13 버전으로 설치하니 해결됬습니다.  감사합니다.

ublock orign 쓰다가 우연히 adguard를 사용하게 됐는데 빠르고 훨씬 좋네요. 많은 발전이 이루어졌으면 좋겠습니다.
