### ISSUE TITLE
현재 네이버미디어캐스트 막히네요.

### ISSUE THREAD

**Issue by ssogoooood** [SlowMemory/List-KR#58]
ublock로 lisk kr과 unblock 적용해서 쓰다가
어제쯤 부터 네트워크 로딩에 실패했다고 뜹니다.

**Comment by SlowMemory** [comment]
안녕하세요, 현재 네이버 티비캐스트에서는 비디오를 재생하는 두 가지 시스템을 가지고 있는데, 새 버전에서는 광고 동영상이 로드되지 않을 시 "네트워크 상태가 원할하지 않아 영상 로딩에 실패했습니다. 페이지 새로고침 후 다시 실행해 주시기 바랍니다." 라는 오류 메세지를 출력하며 동영상 재생을 멈추도록 되어 있습니다. 이 새 버전의 광고의 경우 저는 ublock origin으로 차단하는 방법이 있는지 알지 못합니다.

과거에도 파이어폭스에서는 새 버전을 사용했지만, 익스플로러와 크롬에서는 새 버전이 거의 사용되지 않았습니다. 그런데 점점 광고 차단이 불가능한 시스템의 사용을 늘려가는 것 같네요. 크롬을 계속 사용하시면서 광고도 차단하는 방법이 몇 가지 있습니다.

- [애드가드(Adguard) 윈도우즈 버전](http://adguard.com/?aid=26141 )을 사용하시면 됩니다. 애드가드 윈도우즈 버전은 광고 메타데이터가 브라우저에 로드되기 전 필터링하는 것이 가능하여 오류 없이 광고를 차단할 수 있습니다.

- 브라우저의 User Agent를 수정하는 확장 프로그램으로 UA를 IE나 오페라의 것으로 바꾸시면 됩니다. 앞서 말씀드렸듯이 네이버 티비캐스트에서는 특정 브라우저에서만 새 버전의 비디오 재생 시스템을 사용해왔고 브라우저의 UA를 감지하여 어떤 시스템을 사용할 지 결정하는 듯 합니다. 
 - https://chrome.google.com/webstore/detail/user-agent-switcher-for-c/djflhoibgkdhkhhcedjiklpkjnoahfmg 를 설치하세요.
 - 아이콘을 눌러 UA를 Opera로 바꾸세요.  이렇게 하시면 ublock origin으로 정상적으로 광고차단이 될 겁니다.
