### ISSUE TITLE
https://anigod.com/ 조치 바랍니다.

### ISSUE THREAD

**Issue by kaedep** [SlowMemory/List-KR#59]
`https://anigod.com/`
예전에 조치 되었던걸로 기억합니다만. 또 막아버렸습니다. 이에 대한 조치 부탁드립니다.

**Comment by SlowMemory** [comment]
약간 바뀌었네요. 필터 업데이트 후 확인 부탁드립니다.

**Comment by kaedep** [comment]
네 잘 됩니다. 감사합니다.
