### ISSUE TITLE
네이버 tv캐스트 광고차단

### ISSUE THREAD

**Issue by Dike123** [SlowMemory/List-KR#60]
얼마전까지만 해도 네트워크 상태가 원활하지 않아~~
이렇게 뜨다가

며칠전부터 영상이 재생은 되나 검은화면에서 소리만 나오는 형식으로 바뀌었습니다.
현재 adguard프로그램을 쓰고 있으며, 크롬으로 이용중입니다.

물론 여전히 UA spoofer를 통해 오페라로 변경하면 시청이 가능한 상태라 큰 불편함은 없습니다만 혹시 해결이 가능한가요?

**Comment by SlowMemory** [comment]
제보 감사드립니다! 며칠 전 네이버 TV캐스트에서 광고 동영상 차단 시 동영상 재생이 불가하도록 바뀌었는데, 또 시스템이 바뀐 듯 하군요.

Adguard Chrome 확장 프로그램 사용 시 말씀하신 현상이 발생하는 것을 확인했습니다. Adguard 데스크탑 프로그램을 사용 시에는 말씀하신 문제가 발생하지 않는데, 크롬에서 확장 프로그램으로 애드가드를 사용하고 계신 것이 맞나요?

아직 문제의 원인이 무엇인지 정확히 파악하지 못했지만, 필터 문제가 아닌 광고 차단 확장프로그램 자체에서 해결되어야 할 문제로 추정 중입니다.

임시로 다음 규칙을 사용자 필터에 추가하시면 동영상 재생이 가능하시리라 생각합니다.
```
tvcast.naver.com#%#window.addEventListener("DOMContentLoaded",function(){setTimeout(function(){var a=document.querySelector('video[id^="rmcPlayer_"]');a&&a.setAttribute("style",a.getAttribute("style").replace(/display\s*:[^;!]*!\s*important\s*(;|$)/,""))},1E3)});
```
하지만 이는 임시 해결책이며, 문제를 좀 더 살펴보고 필요시 프로그램 개발자에게 문의하여 문제가 해결될 수 있도록 할 예정입니다.

**Comment by Dike123** [comment]
답변 감사합니다. 현재 크롬 확장팩 adguard를 쓰고있는것이 맞구요.
해당 필터를 추가하니 대부분의 영상이 정상으로 재생이 되네요. 임시 해결책이지만 좋네요. 빠른 답변 감사합니다.

**Comment by SlowMemory** [comment]
개발자에게 문의한 결과, 확장 프로그램에서 차단된 동영상 요소가 브라우저 화면을 차지하지 않도록 숨기는 로직으로 인한 문제라고 합니다. 네이버 tv캐스트가 최근 업데이트된 후, 광고 동영상과 주 동영상을 같은 요소에서 재생하도록 바뀐 듯 합니다. 이런 경우에도 정상적으로 차단할 수 있도록 확장 프로그램을 업데이트할 예정이라고 합니다만, 시일이 좀 걸릴 것으로 추정되어 임시 규칙을 https://github.com/SlowMemory/List-KR/commit/5afbab23ca474344036f4129d178a8aa249aff5c 에서 추가하였습니다. 확장 프로그램이 업데이트되면 임시 규칙을 제거할 예정입니다.
