### ISSUE TITLE
www.yuncomics.com Adblock Warning 문제

### ISSUE THREAD

**Issue by PROBLEM-MAN** [SlowMemory/List-KR#61]
항상 응원하면서 열혈팬인 유저입니다!

다름이 아니라, 며칠 전부터 Adguard를 사용해도 Adblock Warning이 자꾸 가로막더군요.
데스크탑에서 사용은 멀쩡하게 잘 막아주는 것 같습니다. 아마도 데스크탑에서 사용하는 크롬은 Tampermonkey로
Anti Adblock Killer를 사용중이라 아예 Adblock Warning를 걸러주니 상관이 없는데, 문제는 제가 아이폰 사용자라서 유저 스크립트를 이용하고 싶어도 못하는 신세라 애드가드의 필터에 의존하는 수 밖에는 없습니다. ㅠㅠ
아이폰 사용환경은 iOS 10.0.2, Safari 브라우저, Adguard 사용중 입니다.
서버관리자가 자꾸 규칙을 변경하는 탓인지, 아니면 아이폰이 문제인지는 모르겠지만, 너무 거슬리게 만드네요...
모쪼록 잘 해결해 주시면 감사하겠습니다!

항상 응원합니다!
![img_0353](https://cloud.githubusercontent.com/assets/22818642/19354049/58c5b6c0-91a0-11e6-8afd-d5796ed75af5.PNG)

**Comment by SlowMemory** [comment]
안녕하세요! 크롬 확장 프로그램에서는 Adguard 자체만으로도 yuncomics 접속이 가능합니다. List-KR을 활성화 하지 않고도 가능한 것으로 알고 있습니다.
iOS에서 어떤 필터를 사용하고 계신지 알 수 있을까요? '사파리 필터' 도 사용하고 계신가요?

**Comment by PROBLEM-MAN** [comment]
아 저는 브라우저를 사파리로 이용중이고,
사용필터는, 처음 애드가드에 설정된 
영어 필터, 스파이웨어 필터, 소셜미디어 필터는 기본 사용중이며, 모바일 광고 필터와 사파리 필터도 사용 중입니다.
물론 List-KR은 기본 구독이구요 
어떤 필터에서 문제가 있는지 하나씩 꺼보기도 했지만 저로써는 문제를 찾아낼 수가 없어서 고민에 빠졌습니다.

**Comment by SlowMemory** [comment]
제가 iOS 기기가 없어서 우선은 안드로이드 기기와 데스크탑에서 최대한 환경을 사파리와 비슷하게 만들어서(자바스크립트 룰/html 필터링 비활성화, UA spoofing) 실험 중입니다만, 제 경우에는 광고 차단이 감지되지가 않네요. 아이폰을 하나 장만하든지 해야겠습니다...

PC에서 점검하였을 때는 웹사이트 측에서 과거와 비교해 크게 바뀐 것은 없어 보였습니다.


필터를 최신 버전으로 다시 한 번 업데이트해보시고 확인 부탁드리며, 혹시 Adguard 앱의 버전이 몇인지 알려주실 수 있으신가요? 현재 최신 버전은 1.1.0이고 1.0.8 버전에서 지금 문제가 되는 yuncomics 관련 규칙에 영향을 미칠 수도 있는 업데이트가 있었습니다. 또 1.1.0버전 업데이트가 10월 7일 자로 나와 있는데, 얼마 전부터 문제가 발생하셨다면 이 업데이트의 문제일 수도 있을 것 같습니다.

**Comment by PROBLEM-MAN** [comment]
Adguard의 버전은 1.1.0입니다.

아 제가 하나 말씀드린다는 걸 하나 깜빡했군요.
제가 아이패드도 같이 사용하면서, 아이패드에도 Adguard를 설치해뒀습니다.
이렇게 한번씩 Adblcok Warning이 뜰 때, 아이폰 사용할 때는 제 머릿속에서는 도저히 납득이 가지는 않는데
설명을 드리자면, 이게 문제되는 사이트를 링크를 타고 들어가는 방식인데 처음 들어가서 경고가 뜨면,
제가 탭을 닫고 다시 그 링크를 눌러서 몇 번 반복하면 어느새 광고 차단 경고가 안 뜨는 상황이 발생합니다.
아이패드로는 예전부터 똑같은 시도를 해도 바로바로 경고가 떠서 안 되더군요.

알고리즘으로 해보자면,
'경고가 뜨는 사이트의 링크를 클릭한다'-'문제가 되는 사이트를 접속하자 마자 경고가 뜬다'-'경고가 뜨는 문제의 사이트의 탭을 닫는다'-'다시 링크를 눌러 문제의 사이트를 들어간다'-'경고가 다시 뜬다'-'앞의 상황을 반복한다'-'경고가 뜨지 않는 때가 오며 사이트 이용이 가능하다'

이렇게 설명 드릴 수가 있겠네요.

필터를 업데이트 해도 같은 상황인 것을 보아하니, Adguard의 문제가 있는 것 같기도 합니다.

저게 무슨 이유로 저렇게 작동을 하는 건지...
차단이 되다 안되다...뭔가 네트워크 문제인가 싶어서 광고 서버와의 통신을 보려해도 iOS라 볼 수가 없으니...

지금은 해당되지 않는 상황이긴 한데, 문제되는 사이트에서 연속으로 새로고침 몇 번 반복하다 보면 마찬가지로 
경고차단이 말끔이 사라지는 경우가 많았습니다.
그때도 물론 아이패드는 안되구요...

**Comment by SlowMemory** [comment]
앗, 직접 조사해주셔서 감사합니다! 위에 묘사해주신 내용으로 제가 직접 문의를 넣겠습니다. 상세히 묘사해주신 덕에 아마 개발진도 문제를 재현하기 쉬울 것 같네요.

**Comment by SlowMemory** [comment]
@PROBLEM-MAN 안녕하세요, 혹시 제보하신 문제가 아직도 유효한지 확인해주실 수 있으신가요?
최근에 이 문제와 관련되었을 가능성이 있는 [버그 제보](https://github.com/AdguardTeam/AdguardForiOS/issues/255)가 또 올라왔더군요. 

위의 포스트에서 상세히 설명해주신 뒤로 제가 개발자에게 제보한 내용은 https://github.com/AdguardTeam/AdguardForiOS/issues/184 에서 확인하실 수 있습니다. 추가 논의는 https://github.com/AdguardTeam/AdguardFilters/issues/3201 에서 이루어지고 있는데, 재현이 어렵다고 하며 다른 소득은 없는 것으로 보입니다.

모든 사파리 컨텐츠 차단기는 결국 차단기에 필터 데이터베이스를 제공하는 역할을 할 뿐이며 실제 필터링은 사파리 브라우저가 하는 것입니다.
이것이 Adguard iOS 앱과 여타 사파리 광고차단 앱들이 브라우저 확장 프로그램이나 다른 운영체제의 프로그램과 다른 부분인데요, 필터에 문제가 있는 상황은 아니리라 추측하며 Adguard 앱 또는 사파리 컨텐츠 차단기의 문제인데, 여러 주체가 개입된 문제라 개발자 입장에서도 한번에 원인을 찾아내기가 어려운 것 같습니다.

유사한 버그 제보가 올라온 만큼, 문제가 여전히 재현되신다면 저도 개발자들이 이 문제를 다시 한 번 들여다보도록 제보해 보겠습니다.

**Comment by PROBLEM-MAN** [comment]
흐음... 논의하고 글들도 읽어보고 왔습니다.

@@||yuncomics.com^$elemhide 필터도 추가해 보기는 했는데, 별 다른 동향은 없는 것 같습니다. 
아직 그대로 차단 표시가 뜨기는 하는데, 불편 정도야 뭐 감수하면 되는데 개발자 분들이 힘드실 것 같네요;;

혹시나 아이폰이 문제 인가 싶어서 아이패드로 1.1.0으로 다시 올려서 커스텀 필터 넣고 시도했지만 결과는 같더군요.

으 커스텀 필터로도 안된다면 정말 사파리 컨텐츠 차단기나 Adguard 둘중 하나가 문제이지 싶네요.

**Comment by gotitbro** [comment]
;@PROBLEM-MAN I read your reply through **Google Translate**, you can add the by going to the **_Adguard app_** > **_User Filters_** > Tap on "+"icon on top right and then paste `@@||yuncomics.com^$elemhide` in the field and tap "**Done**".

**Comment by PROBLEM-MAN** [comment]
@gotitbro  Thanks, It works perfectly! 
Then I have to add this filter as same.

Have a nice day!

**Comment by gotitbro** [comment]
That's great @PROBLEM-MAN :)

**Comment by SlowMemory** [comment]
안녕하세요, Adguard iOS 앱의 관련 버그가 현재 해결된 것 같습니다. 
현재 yuncomics.com 도메인은 쓰이지 않지만 wasabisyrup.com에도 같은 규칙이 적용되고 있습니다. 한번 확인해 주시고 최신 버전에서 문제가 계속 발생한다면 알려주시면 감사드리겠습니다.
