### ISSUE TITLE
adv screen recorder 앱 하단 광고

### ISSUE THREAD

**Issue by nskzhd** [SlowMemory/List-KR#62]
https://play.google.com/store/apps/details?id=com.blogspot.byterevapps.lollipopscreenrecorder
이전까지는 광고가 나오지 않았는데 최근 업데이트 후 하단광고가 뜨기시작하네요.
혹시 차단 가능한 룰 추가 부탁드려도 될까요?

**Comment by nskzhd** [comment]
아 adguard 안드로이드용에 slowmemory님 필터 추가해서 사용중입니다.

**Comment by SlowMemory** [comment]
안녕하세요, 방금 확인해봤는데 제 기기에서는 광고가 나타나지 않습니다. https로 로드되는 페이스북 광고가 차단되고 있는 것으로 나타나는데요, 앱에서 https 필터링을 활성화하셨는지 확인 부탁드립니다.

**Comment by nskzhd** [comment]
답변 감사드립니다. https필터링을 활성화하지 않아도 제가 쓰는 앱들은 다 차단이 되길래 지금까지 그냥 사용했었는데.. 말씀해주신대로 켰더니 문의드린 앱에서도 더이상 광고가 나타나지않네요ㅎㅎ 감사합니다.
