### ISSUE TITLE
로또리치 사이트 관련이요.

### ISSUE THREAD

**Issue by 7nani4u** [SlowMemory/List-KR#63]
uBlock Origin v1.9.10 버전을 쓰고 있는 중인데요.

로또리치 사이트에 들어가면 상단 메뉴바가 보이는 않는 증상이 있습니다.

혹시 고쳐주실수는 없는건가요 ?

**Comment by SlowMemory** [comment]
제보 감사드립니다! 로또리치 측에서 타 웹사이트에 게재하는 광고를 차단하는 과정에서 발생한 부작용인듯 하네요. 필터 업데이트 후 문제가 해결되었는지 확인해주세요 :)

**Comment by 7nani4u** [comment]
네~ 해걸 되었습니다. 고쳐주셔서 감사드려요 !!
