### ISSUE TITLE
안드로이드 Adguard 베타 버전에 List-KR이 추가되었습니다.

### ISSUE THREAD

**Issue by Intrainos** [SlowMemory/List-KR#64]
2.8.1 beta 에서 추가되었습니다. 필터 리스트중 가장 마지막에 있습니다
AdguardTeam/AdguardForAndroid#756 이슈가 닫혔지만, 아직 한국 유저 기본값으로 설정되지는 않았기 때문에 Readme.md에 내용을 쓰는것이 좋아보입니다.

**Comment by SlowMemory** [comment]
제안해주셔서 감사합니다! 말씀해주신 대로 설명을 업데이트 하였습니다.
