### ISSUE TITLE
time.navyism.com 광고차단 회피 문제

### ISSUE THREAD

**Issue by Moore2512** [SlowMemory/List-KR#65]
![navyism2](https://cloud.githubusercontent.com/assets/23067086/19710645/e1604d14-9b6a-11e6-9647-f7226c21c343.png)

원래 특정서버의 시간을 보여주는 기능을 갖고있으나, 광고차단 프로그램을 쓰고 들어가면 기능이 사라짐과 동시에 유저를 비아냥대는 문구가 나타납니다. (파란색 네모 부분)

윈도우10, 크롬, 애드가드 2.4.14버전이며 List-KR 1.0.1.28버전을 쓰고 있습니다.

**Comment by SlowMemory** [comment]
제보 감사합니다! https://github.com/SlowMemory/List-KR/commit/226638cf7db4909affa10fdbc2728610688ddfab 에서 해결되었습니다. 필터 업데이트 후 확인해주세요.

**Comment by Moore2512** [comment]
답변 감사합니다.
