### ISSUE TITLE
모바일 네이버 페이지

### ISSUE THREAD

**Issue by tgpark** [SlowMemory/List-KR#66]
http://m.news.naver.com/hotissue/main.nhn?sid1=100&cid=1053020&gid=1051906&dummy=1611051338

안드로이드 모바일 크롬에서 위 주소의 어떤 뉴스 기사를 클릭하든 처음엔 알 수 없는 오류가 발생했다는 페이지가 뜹니다. 그 상태에서 새로고침을 해야만 기사가 제대로 보입니다.

pc에서는 문제 없는데 유독 안드로이드에서만 이러네요.
참고로 adguard에서 lisr-kr 필터 해제하면 정상적으로 한 번에 다 열립니다.

**Comment by SlowMemory** [comment]
안녕하세요, 현재 문제 재현에 어려움이 있습니다. 오류 메시지가 어떻게 보이는지 화면을 캡쳐하여 알려주실 수 있으신가요?

**Comment by tgpark** [comment]
지금은 제가 본문 건 본문 링크의 기사들은 잘 열리는데...
다시 네이버 모바일 메인 페이지에 ㅂㄹㅎ 관련 기사로 m.naver.com/hotissue/...... 페이지로 이동한 후 거기 기사들 열어보면 또 동일하게 발생합니다. 크롬, 크롬 베타로 방금 또 확인했습니다.

http://m.imgur.com/a/giDkH

**Comment by tgpark** [comment]
http://imgur.com/a/giDkH

지금은 또 제가 본문 링크는 잘 열리는데...
다시 네이버 모바일 메인페이지에서 최순실 관련 기사 클릭 -> 핫이슈로

**Comment by SlowMemory** [comment]
제 기기에서는 애드가드를 완전히 언인스톨한 상태에서도 주소 http://m.news.naver.com/hotissue/read.nhn?sid1=100&cid=1051768&iid=49278322&oid=421&aid=0002375989 로 접속하면 문제가 재현이 됩니다. PC에서는 브라우저의 캐시, 쿠시 등을 완전히 삭제한 후 페이지에 접속하면 마찬가지 화면이 뜹니다. 임시 파일이 삭제되지 않은 브라우저를 통해 접속하면 접속이 되고, 같은 브라우저에서 임시파일을 삭제한 후 접속하면 마찬가지 오류 메시지가 뜨는군요.

이러한 결과로 볼 때, 이 문제가 네이버측의 문제가 아닌가 싶습니다.

@tgpark 님께서는 이 문제를 언제부터 경험하셨나요?

**Comment by SlowMemory** [comment]
앗, 말씀하신 스텝을 정확히 따라가니 재현이 되는군요! 확인해보겠습니다.

**Comment by SlowMemory** [comment]
제 기기에서는 애드가드를 완전히 언인스톨한 상태에서도 주소 http://m.news.naver.com/hotissue/read.nhn?sid1=100&cid=1051768&iid=49278322&oid=421&aid=0002375989 로 접속하면 문제가 재현이 됩니다. PC에서는 브라우저의 캐시, 쿠시 등을 완전히 삭제한 후 페이지에 접속하면 마찬가지 화면이 뜹니다. 임시 파일이 삭제되지 않은 브라우저를 통해 접속하면 접속이 되고, 같은 브라우저에서 임시파일을 삭제한 후 접속하면 마찬가지 오류 메시지가 뜨는군요.
이러한 결과로 볼 때, 이 문제가 네이버측의 문제가 아닌가 싶습니다.
@tgpark 님께서는 이 문제를 언제부터 경험하셨나요?

**Comment by tgpark** [comment]
아... 그런가요? 
지금 adguard 종료하고 크롬 데이터 초기화하고 확인해보니 동일한 문제가 발생하는군요.
경험은 몇 달 된 것 같은데 정확하게는 모르겠습니다.
보통 포털 뉴스 기사는 네이버 보단 주로 다음에서 보며 이 문제를 경험해도 당시엔 사용하던 공유기(와이파이)가 종종 순간적으로 끊기는 일이 발생해서 공유기 문제로 생각하고 넘겼거든요.

**Comment by SlowMemory** [comment]
쿠키와 일부 관련이 있는 문제 같습니다.

제 기기에서는 아래 현상이 일관적으로 재현됩니다:

1.  pc에서 ccleaner를 통해 크롬 브라우저의 임시 파일을 지우고 크롬 주소창에 http://m.news.naver.com/hotissue/read.nhn?sid1=100&cid=1051768&iid=49278322&oid=421&aid=0002375989 를 입력하고 엔터를 눌러 들어가면 오류가 발생합니다.
2. 여기서 새로고침을 반복해도 계속 오류가 발생합니다.
3. 이 때 콘솔에서 `document.cookie="BMR=.";` 를 실행하여 임의로 쿠키 값을 지정하고 새로고침을 누르면 페이지가 정상적으로 표시됩니다.

만약 제 필터가 문제 발생에 기여하는 바가 있다면, 네이버 홈페이지에서 광고와 트래커(광고 차단을 사용하는지 여부도 수집합니다) 를 차단하여 일반적으로 링크를 타고 들어가는 과정에서 생성되는 쿠키가 생성되지 않을 가능성이 있습니다.

그러나 다른 사이트에서 링크를 통하거나 주소를 복사하여 바로 접속하는 것도 충분히 가능하고, 브라우저의 임시 파일을 자주 지우는 사용자도 많은데, 이런 상황에서 페이지를 표시하지 못한다면 이것이 사용자의 문제라기보다는 서버측의 버그가 아닌가 싶습니다. 이를 필터를 수정하여 해결하는 것은 어렵고, 네이버에 이런 버그를 제보하는 창구가 있나 모르겠네요.
