### ISSUE TITLE
list-kr 필터 adguard android beta 추가된 것에 관하여...

### ISSUE THREAD

**Issue by beginnergit** [SlowMemory/List-KR#67]
list-kr 필터를 항상 감사하게 사용하고 있는 유저입니다.

다름아니라 adguard 안드 베타 2.8.15부터 list-kr필터가 추가되었다는걸 보고

설치해봤는데 아직 필터 목록에 없네요. 

최근 나온 2.8.40버전도 설치하고 목록 제일 밑으로 내려봐도 없구요. 

업뎃 중단된 korean adblock만 있습니다.

xda adguard 포럼같은곳에 남겨야하지만 영어가 젬병이라 일단 여기에 남겨봅니다.

폰, 태블릿 둘 다 깔아봐도 같네요. 이게 저만 해당되는 문제인지...

**Comment by SlowMemory** [comment]
앗 이상하네요, [이 글](http://www.clien.net/cs2/bbs/board.php?bo_table=cm_andro&wr_id=362003)의 스크린샷과 같이 필터 목록의 맨 아래에 나타나지 않는다는 말씀이신가요? 설정 -> 광고 차단 탭에 들어가셔서 어떻게 보이시는지 알려주실 수 있으신가요? 필터가 추가되는 건 앱에 하드코딩되는 부분이라 우선 앱을 완전히 삭제하시고 재설치해보실 수 있을 것 같습니다.

**Comment by beginnergit** [comment]
늦게 확인해서 죄송합니다.

slowmemory님께서 알려주신대로 공식 홈페이지에서 정식버전 설치 후 베타 선택 후 업데이트 확인해서 설치하니 필터 목록에 나타나네요.. 이거 참.. 귀신에 홀린듯하네요..

github 베타 페이지에서 설치 파일 바로 받아서 설치했을땐 안 나왔던것같았는데요..;;

여튼 친절한 답변 감사드립니다.

**Comment by SlowMemory** [comment]
그렇다면 github 베타 페이지에 올라간 apk에 문제가 있을 수도 있겠네요. 알려주셔서 감사합니다^^
