### ISSUE TITLE
톱스타 뉴스 사이트 광고가 많이 뜨네요

### ISSUE THREAD

**Issue by cjh980402** [SlowMemory/List-KR#68]
이 사이트 광고차단 규칙도 추가해주실수 있을까요?

**Comment by SlowMemory** [comment]
안녕하세요, 톱스타 뉴스 사이트는 topstarnews.net 을 말씀하시는 것이 맞나요? 제가 확인했을 때는 모바일 데스크탑 모두 특별히 뜨는 광고가 없었습니다. 여전히 광고가 뜨신다면 사용하시는 광고 차단 소프트웨어 명, 사용하고 계신 필터 목록과 광고의 위치를 스크린샷으로 표시해서 올려주시면 감사하겠습니다.

**Comment by cjh980402** [comment]
adguard이용하는데 지금은 다시 잘 되네요. 또 한가지 궁금한 것이 있는데 사용자필터에 
https://github.com/SlowMemory/List-KR/blob/master/filter.txt  로 적용할 때랑
https://github.com/SlowMemory/List-KR/raw/master/filter.txt 로 적용하면 다른가요?

**Comment by cjh980402** [comment]
adguard 이용하고요 하단에
http://nsclick.neoebiz.co.kr/cpmClick_cpc.php로 시작하는 광고가 뜹니다.

**Comment by cjh980402** [comment]
adguard이용합니다. 하단에
http://nsclick.neoebiz.co.kr/cpmClick_cpc.php 로 시작하는 광고도 뜹니다

**Comment by SlowMemory** [comment]
반드시 https://github.com/SlowMemory/List-KR/raw/master/filter.txt 로 적용하셔야 필터 내용이 적용됩니다. https://github.com/SlowMemory/List-KR/blob/master/filter.txt 링크로 적용하시면, 이 링크를 눌렀을 때 나타나는 페이지의 html 코드를 필터로 적용하게 됩니다.

> adguard이용합니다. 하단에 http://nsclick.neoebiz.co.kr/cpmClick_cpc.php 로 시작하는 광고도 뜹니다
1. adguard를 어떤 운영체제에서 사용하고 계신가요?
1. 광고가 나타나는 페이지의 url을 복사해서 여기 올려주실 수 있으신가요?
1. 사용자 필터에 다음 규칙을 추가하시면 광고가 사라지나요?
```
||neoebiz.co.kr^$third-party
```

**Comment by cjh980402** [comment]
감사합니다! 잘 되네요ㅎㅎ

**Comment by SlowMemory** [comment]
문제가 해결되었다니 다행이네요. 참고로 안드로이드에서 사용 중이시라면, 곧 사용자 필터에 List-KR을 수동으로 적용할 필요 없이, '설정->광고 차단'에서 선택할 수 있게 되어 백그라운드 자동 업데이트가 가능하게 됩니다. 현재도 Adguard 베타 버전을 사용하시면 적용 가능합니다.
