### ISSUE TITLE
애드가드 사용시 사이트 메뉴가 아예 나타나지 않습니다.

### ISSUE THREAD

**Issue by Moore2512** [SlowMemory/List-KR#69]
http://kknd2ro.cafe24.com/

입니다.

아예 사이트 내용 전체를 막아버리는군요

**Comment by SlowMemory** [comment]
제보 감사합니다. https://github.com/SlowMemory/List-KR/commit/90e8c935fb86c0d51115340d9c4ce014ff96cde3 에서 해결되었습니다. 필터 업데이트 후 확인 부탁드립니다.
