### ISSUE TITLE
www.coolenjoy.net 느려짐 문제.

### ISSUE THREAD

**Issue by open-mindt** [SlowMemory/List-KR#71]
크롬에 Adguard Adblocker 설치해서  기본셋팅에 느린기억님 필터를 사용하고 있는데요.

위에 사이트 게시판에 들어가면 거의 5~7초 동안  버벅 이면서 화면을 움직일 수 없는 상태가 됩니다. 

시간이 지나면 괜찮아 지구요. 느린기억님 필터를 끄면  버벅임 없이 빠릿해 지구요. 뭐가 문제인 걸까요.

**Comment by SlowMemory** [comment]
안녕하세요, 3일 전에 릴리즈된 최신 Adguard 크롬 확장프로그램에 문제가 있는 것 같습니다. 이 문제로 인해 몇몇 웹사이트와 네이버 tv캐스트 홈페이지도 영향을 받고 있습니다. 해결되기 전까지는 차단을 하지 않거나/다른 광고차단 툴을 사용하셔야 할 듯합니다. Adguard 확장 프로그램 2.5.8버전의 문제이며 Adguard 데스크탑 프로그램, 안드로이드, iOS 등 다른 플랫폼에는 영향이 없습니다. 문제가 해결되면 이곳에 알려드리겠습니다.

**Comment by open-mindt** [comment]
확장 프로그램 업데이트가 문제였군요. 크롬 확장이 고쳐질 때까지 그냥 써야 갰네요.
답변해 주셔서 감사합니다.
