### ISSUE TITLE
Edge 브라우저에서 필터 구독이 되지 않습니다.

### ISSUE THREAD

**Issue by YCM0802** [SlowMemory/List-KR#72]
![adp2](https://cloud.githubusercontent.com/assets/24618197/21284853/69363914-c46b-11e6-808e-42a919aa97e5.JPG)
![adp1](https://cloud.githubusercontent.com/assets/24618197/21284854/69363176-c46b-11e6-9009-207b7f742faa.JPG)

제 방법이 잘못된 건가요? 그렇다면 알려주시기 바랍니다

**Comment by SlowMemory** [comment]
현재 Adblock Plus는 지원하고 있지 않습니다. Adblock Plus에서는 구독하려는 필터에 호환되지 않는 규칙이 있는 경우 스크린샷과 같은 오류가 발생합니다. List-KR을 사용하기 위해서는 uBlock origin 또는 Adguard를 이용해 주세요. Adblock Plus용 한국 웹 필터로 Youslist 를 구독하실 수 있습니다.
