### ISSUE TITLE
안드로이드 Localcast 앱 하단 광고 외

### ISSUE THREAD

**Issue by nskzhd** [SlowMemory/List-KR#73]
지금까지 광고 차단이 잘 되어 문제없이 썼었던 앱인데..(거의 매일같이 쓰던 앱입니다)
어제부터 Localcast (https://play.google.com/store/apps/details?id=de.stefanpledl.localcast) 라는 앱과 shiftup(플레이스토어에는 없는 앱)이라는 앱에서 광고가 뜨기 시작하네요.
Localcast는 하단배너광고 자리가 원래 검정색으로 아무것도 없었는데 이미지가 깨진것처럼 나오기 시작하더니 이제는 아예 광고배너가 뜨기 시작했구요. (캐시를 지웠더니 다시 이미지가 깨진것처럼 나오네요)
shiftup은 아무런 광고팝업도 배너도 없었는데, 어제부터 앱 실행시 전체화면 광고팝업이 뜨는데 광고의 내용은 없고 그냥 검정색의 전체화면 팝업이 뜹니다.

차단 부탁드려봅니다.

**Comment by SlowMemory** [comment]
Localcast 앱에서는 광고가 재현되지 않습니다. 광고가 나타나는 스크린샷을 올려주실 수 있으신가요?
shiftup 앱은 어디서 다운받으면 좋을까요? ^^;;

**Comment by nskzhd** [comment]
Localcast 광고가 뜰때와 이미지가 깨진것처럼 나올때 두가지 스크린샷이구요.
shiftup 전체화면팝업이 뜰때 스크린샷도 올립니다.

shiftup은 https://goo.gl/bgh7ZL 여기서 다운가능합니다.
![localcast 2](https://cloud.githubusercontent.com/assets/22853516/21520585/d1834252-cd38-11e6-8357-075781b2ab1d.png)
![localcast 1](https://cloud.githubusercontent.com/assets/22853516/21520586/d1867e0e-cd38-11e6-9373-f84c2037f274.png)
![shiftup](https://cloud.githubusercontent.com/assets/22853516/21520587/d1872c96-cd38-11e6-88a7-e08dbf2b3287.png)

**Comment by SlowMemory** [comment]
광고가 나타나는 경우를 찾으려 계속 시도해봤지만 실패했습니다.

글쓴님의 경우가 알려진 버그일 가능성이 있는데요, 이런 경우 Adguard 앱의 로우 레벨 설정에서 pref.vpn.ipv6.disable, pref.vpn.ipv6.bypass, pref.proxy.block.ipv6 중 하나를 체크하시고 앱 캐시 삭제, 재부팅 하시면 문제가 해결될 수 있습니다. 한번 해 보시고 확인해주시면 감사드리겠습니다.

**Comment by nskzhd** [comment]
도움감사드립니다. 말씀해주신대로 설정을 이리저리 바꿔봐도 효과가 없네요.
localcast도 다시 깔아보고 adguard도 다시 깔아보고 했는데.. 해결이 안되네요.

**Comment by SlowMemory** [comment]
문의 시 답장으로 왔던 메일에 답장으로 여전히 안된다고 보내 보세요. 문제를 해결하기 위해 앱 로그 등 더 자세한 정보를 요구할 것 같습니다. 제게 직접 앱 로그를 보내주셔도 확인해볼 수 있습니다.

**Comment by nskzhd** [comment]
감사합니다.앱로그는 어떻게 생성해서 보내드리면 될까요?

**Comment by SlowMemory** [comment]
앱 로그는 이렇게 보내주시면 됩니다.

1. 광고가 차단되지 않는 앱을 종료하시고 캐시와 데이터를 삭제하세요.
1. "설정 ⇒ 고급 설정 ⇒ 로깅 레벨" 에서 "모두 기록" 에 선택하세요.
1. 메인 화면에서 보호를 한번 껏다 켜세요.
1. 문제를 재현 (예를 들어, 광고가 차단되지 않는 앱을 실행하여 광고가 페이지에 나타나는 것을 확인)하시고, 로깅 레벨을 다시 "기본" 으로 바꿔주세요.
1. Android/data/com.adguard.android/cache/log 에 들어가셔서 가장 최근의 adguard.log 파일을 이곳에 올려주시거나 https://list-kr.github.io/form.html 를 통해 보내주세요.

**Comment by nskzhd** [comment]
로그파일 생성해서 올립니다.
도움 정말 감사합니다!

**Comment by SlowMemory** [comment]
로그 파일을 확인했습니다. 나타난 광고가 
![336x280-1](https://cloud.githubusercontent.com/assets/19346646/21589958/98b41270-d13a-11e6-8b47-76ea5a267912.jpg)
이 맞나요? 이외에도 다른 광고가 있었나요?
차단되지 않은 특정 광고사로의 네트워크 연결이 있었으며, 관련 요청을 차단하기 위한 필터를 업데이트 했습니다. Adguard 서버에서 필터가 업데이트되기 위해서는 1시간 정도 시간이 걸릴 수 있으니 필터가 업데이트된 후 광고가 나타나는지 다시 한번 확인해주세요. 만약 여전히 광고가 나타나신다면 마찬가지 방법으로 로그를 첨부해주시면 감사드리겠습니다.

**Comment by nskzhd** [comment]
로그를 생성하는중에 로컬캐스트를 실행했을때는 광고자리부분에 모두 이미지가 깨진것처럼 나와서 실제 어떤 광고가 떴었는지는 알 수가 없었습니다. 저번에 캡쳐를 올릴때 떴던 광고가 쿠차광고였던걸 보면.. 아마 이 광고고 맞을거라고 생각됩니다.

애드가드 필터 업데이트가 저녁 10시 37분경에 업데이트 되었다고 나오는데 말씀하신 필터추가업데이트가 된건지 잘 몰라서, 일단 list-kr은 해제하고 유저필터에 list-kr 필터 주소를 추가해서 조금전에 확인해봤습니다.

계속해서 광고자리 부분에 이미지가 깨진것 같은 형태가 뜨고
![screenshot_2017-01-03-00-50-55re](https://cloud.githubusercontent.com/assets/22853516/21592501/3fa9819e-d151-11e6-91be-c4aa1e0068a4.png)

뒤로가기를 누르면 이런식으로 전체 광고가 뜨는 경우도 있구요. 
(광고자체가 보이는 경우와 그냥 까만화면만 뜨는 경우 두가지 입니다. 
까만화면만 뜨는 경우는 localcast 뿐만아니라 shiftup에서도 나타납니다.)
![screenshot_2017-01-03-00-51-08re](https://cloud.githubusercontent.com/assets/22853516/21592516/68ffe114-d151-11e6-8072-8609ef36fdf6.png) ![screenshot_2017-01-03-00-53-13re](https://cloud.githubusercontent.com/assets/22853516/21592517/690f527a-d151-11e6-91ff-576cad95a549.png)

그리고 하단 광고자리 부분에 광고가 뜨는 경우도 계속해서 발생합니다.
![screenshot_2017-01-03-00-54-01re](https://cloud.githubusercontent.com/assets/22853516/21592528/8486588c-d151-11e6-9899-64edf046a4d9.png)

추가로 사용하는 보안카드앱을 실행했더니 여기서도 하단광고가 떠서 추가해봅니다.
![screenshot_2017-01-03-01-12-53 re](https://cloud.githubusercontent.com/assets/22853516/21592678/baea48ce-d152-11e6-847a-84b905c411d1.png)

로그파일도 첨부합니다.

감사합니다 :)
[adguard log.zip](https://github.com/SlowMemory/List-KR/files/681115/adguard.log.zip)

**Comment by SlowMemory** [comment]
차단되지 않은 광고 중 Cauly 광고가 있네요. Adguard에서 모든 포트를 필터링하지 않아 발생하는 문제일 가능성이 있는데, http://clien.net/cs2/bbs/board.php?bo_table=cm_andro&wr_id=373336 에 관련하여 글을 올린 적 있습니다. 확인하시고 DNS 요청 필터링을 사용하실 경우에 문제가 해결되는지 확인 가능하신가요?

**Comment by nskzhd** [comment]
와! 해결됐습니다!!!! 더이상 뜨지않네요!
보안카드앱 하단 광고자리에 크게 cauly라고 글자는 뜨는데 이것도 광고인지 아닌지는 모르겠지만 거슬리는건 아니라 넘어가도 될것 같습니다ㅎㅎ

늦은 시간까지 답변해주시고 감사드립니다ㅎㅎ

**Comment by SlowMemory** [comment]
문제가 해결되었다니 다행이네요! DNS 필터링을 활성화해야만 차단되는 경우는 개발자 측에서도 인지하고 있다고 합니다. 향후 업데이트에서 추가 설정 없이도 차단되도록 업데이트될 듯합니다.
