### ISSUE TITLE
minitoon.net에서 adblock을 감지합니다.

### ISSUE THREAD

**Issue by edoko** [SlowMemory/List-KR#74]
http://minitoon.net/ 에서 어떠한 만화 게시글을 봤을 때,
"광고 차단 플러그인 (애드블록 등)을 해제해야 컨텐츠를 볼 수 있습니다." 라는 메세지가 출력되며 게시글 내용은 출력되지 않습니다.

Chrome Beta에서 uBlock Origin 1.10.4 버전을 사용하고 있으며,
현재 필터는 디폴트 옵션에서 KOR 필터는 전부 비활성화하고, List-KR 필터 2개만 추가하여 활성화한 상태입니다.
('광고' 분류에서는 Anti-Adblock Killer | Reek, EasyList만 활성화되어있는데 Adblock Warning Removal List 옵션을 활성화하면 아예 위의 메세지와 게시글 자체가 전부 사라져버립니다.)

+ 분명히 지금까지는 문제 없다가 갑자기 다른 게시글을 누른 후부터 ublock을 비활성화하지 않는 이상 게시글을 볼 수가 없게 되었습니다.

**Comment by SlowMemory** [comment]
제보 감사합니다! 필터 업데이트 후 해결되었는지 확인 부탁드립니다.
