### ISSUE TITLE
Anigod 사이트 fuckadblock 문제

### ISSUE THREAD

**Issue by gustjr9959** [SlowMemory/List-KR#75]
아이폰에서 adguard pro를 사용중입니다. 마루마루같은 페이지에서는 정상적으로 작동하나 anigod의 경우에는 광고 필터링을 취소해달라는 메세지가 뜨고 흰색 화면만 보입니다. 나무위키에서는 바디가 삭제된 후 처리되어서 그렇다고 합니다. 해결법을 위해 스크립트를 넣어보려 했지만 문법 형식이 맞지 않아 불가능했습니다. 사용중인 필터는 영어, 스파이웨어, 소셜미디어, annoyance ,유용한 광고 필터, adguard dns 필터, 사파리 필터, adblcok warning removal list, anti-adblock killer, korean adblock list, list-kr, malware domains 입니다. 어떤 방법으로 이 메시지를 지울 수 있을까요?

**Comment by SlowMemory** [comment]
안녕하세요, 아래 두 규칙을 각각 사용자 지정 규칙에 직접 추가하고 테스트해 보세요.
```
@@||anigod.com^$elemhide
@@||gryfindor.com^$elemhide
```
현재 iOS 버전 앱의 버그로 인해 일부 규칙이 정상적으로 적용되지 않는 문제가 있는데, 이 문제의 영향으로 생각됩니다. 이 문제의 영향이 맞다면 위 규칙을 추가하여 임시로 해결할 수 있습니다.
해당 버그는 https://github.com/AdguardTeam/AdguardForiOS/issues/255 에서 진행 상황을 확인하실 수 있으며 해결되고 정식 버전에 반영되면 임시 규칙을 제거하셔도 됩니다.

**Comment by SlowMemory** [comment]
아, 이슈 트래커에서는 아직 open이라 나와 있지만 이미 고쳐진 것 같네요. 다른 원인이 있는 듯 하여 필터를 업데이트 하였습니다. 확인 부탁드립니다!

**Comment by gustjr9959** [comment]
위에 있는 규칙을 추가하고 필터를 업데이트 했지만 상태는 같았습니다. List-kr 1월 2일 것이 마지막 업데이트라고 나오는 상태입니다. 말씀하신 대로 앱에 버그가 있는 게 맞는 거라고 생각합니다. 혹은 anigod 사이트가 아이피 차단을 했을 가능성도 있나요?

**Comment by SlowMemory** [comment]
> 문법 형식이 맞지 않아 불가능했습니다.

자바스크립트 삽입 규칙은 iOS 버전에서 지원되지 않습니다.
> 사용중인 필터는 영어, 스파이웨어, 소셜미디어, annoyance ,유용한 광고 필터, adguard dns 필터, 사파리 필터, adblcok warning removal list, anti-adblock killer, korean adblock list, list-kr, malware domains 입니다.

모든 사파리 컨텐츠 차단기는 애플에서 강제한 정책으로 인해 50000개보다 많은 규칙을 사용할 수 없습니다. 현재 글쓴님의 앱에서 총 규칙의 개수가 몇 개인지, 실제 활성화된 규칙 수가 총 규칙 수보다 적은지 확인 가능하신가요?

5만 개가 넘는다면, Adguard DNS, adblock warning removal list, korean adblock list, anti-adblock killer 순서로 제거하시면 될 듯 합니다.
> 혹은 anigod 사이트가 아이피 차단을 했을 가능성도 있나요?

가능성은 있지만 제가 해당 사이트 관계자가 아니라 답을 드리기가 어렵습니다. IP 차단이 의심되신다면, 글쓴님의 환경에서 모바일 데이터로 접속해 보시거나 다른 와이파이에 연결하여 접속하셨을 때 달라지는 것이 있는지 확인해보시면 될 것 같습니다.
