### ISSUE TITLE
안드로이드 Dcinside 어플 사용시 게시글 내 광고 차단문제

### ISSUE THREAD

**Issue by ghost** [SlowMemory/List-KR#76]
.

**Comment by SlowMemory** [comment]
안녕하세요, 이 글에 설명드린 대로 DNS 필터링 차단 또는 포트 추가 후 앱 캐시 삭제하고 광고가 차단되는지 확인해보세요.

**Comment by slirrrr** [comment]
답변 감사드립니다.

두 개 다 시도 해보았고 캐시삭제도, 데이터 삭제도 해봤는데 게시글 내에서는 여전히 광고가 나오네요.

원인이 뭘지 잘 모르겠네요.

**Comment by SlowMemory** [comment]
그렇다면 "설정 ➜ 고급 설정 ➜ 로우 레벨 설정"에서 
로컬 VPN 모드를 사용하고 계시면 pref.vpn.ipv6.disable,
로컬 http 프록시 모드를 사용하고 계시면 pref.proxy.block.ipv6 을 체크하고 사용해 보세요.

여전히 안 되신다면 앱의 로그를 올려주시면 감사드리겠습니다.

**Comment by slirrrr** [comment]
여전히 광고가 나오는데 로그는 어떻게 찾나요?

**Comment by SlowMemory** [comment]
앱 로그는 이렇게 보내주시면 됩니다.

    광고가 차단되지 않는 앱을 종료하시고 캐시와 데이터를 삭제하세요.
    "설정 ⇒ 고급 설정 ⇒ 로깅 레벨" 에서 "모두 기록" 에 선택하세요.
    메인 화면에서 보호를 한번 껏다 켜세요.
    문제를 재현 (예를 들어, 광고가 차단되지 않는 앱을 실행하여 광고가 페이지에 나타나는 것을 확인)하시고, 로깅 레벨을 다시 "기본" 으로 바꿔주세요.
    Android/data/com.adguard.android/cache/log 에 들어가셔서 가장 최근의 adguard.log 파일을 이곳에 올려주시거나 https://list-kr.github.io/form.html 를 통해 보내주세요.

**Comment by slirrrr** [comment]
방금 찾았는데 로그가 매우 기네요 삭제하고 다시 게시글에 들어가 광고 차단이 안 되는것을 확인하고 로그를 드리면 될까요

**Comment by slirrrr** [comment]
아방금 답변봤습니다 저대로해서 보내드리겠습니다

**Comment by slirrrr** [comment]
[adguard.log.txt](https://github.com/SlowMemory/List-KR/files/690420/adguard.log.txt)
말씀하신대로 로그를 뽑았습니다. 늦은밤에 감사드립니다.

**Comment by ameshkov** [comment]
`downinfo.cauly.co.kr` domain is not blocked. Could it be the culprit?

**Comment by ameshkov** [comment]
Also it seems that the app might be using facebook ad network:
```
02:17:38.536 [pool-2-thread-60] DEBUG com.adguard.android.FilteringLog - TCP id=100163 CONNECT https://graph.facebook.com/ com.dcinside.app 1482 56782
```

You can take care of it with this rule:
`||graph.facebook.com^$domain=com.dcinside.app`

**Comment by ameshkov** [comment]
And one more thing, it requests ad settings from here:
http://json.dcinside.com/App/app_ad_setting.php

I suppose it's possible to suppress all the ads by applying a $replace rule to it:
`||json.dcinside.com/App/app_ad_setting.php$replace=/true/false/`

**Comment by slirrrr** [comment]
이분이 말씀 해 주신대로 해봤지만 여전히 광고가 노출 되네요. 그냥 사용해야 하는 것인지 ㅠㅠ

**Comment by SlowMemory** [comment]
@slirrrr 안녕하세요, 필터를 업데이트 하시고 확인 부탁드립니다.
여전히 광고가 보이신다면 확인하신 광고의 스크린샷과 마찬가지 방법으로 앱 로그를 올려주시면 감사드리겠습니다.
