### ISSUE TITLE
티비캐스트 광고 관련 

### ISSUE THREAD

**Issue by cjh980402** [SlowMemory/List-KR#77]
티비캐스트 어플에서는 광고차단이 잘 되는데
네이버포스트에 올라온 티비캐스트 영상을
 브라우저에서 볼때는 광고차단이 안 되네요.

**Comment by SlowMemory** [comment]
안녕하세요, 광고차단이 되지 않는 영상을 확인할 수 있는 url과 사용 환경을 알려주실 수 있으신가요?

**Comment by cjh980402** [comment]
http://m.post.naver.com/viewer/postView.nhn?volumeNo=6007000&memberNo=28456565
영상은 저 포스트에 있는거고
adguard는 안드로이드입니다.

**Comment by SlowMemory** [comment]
감사합니다. 필터 업데이트 후 확인 부탁드립니다!

**Comment by cjh980402** [comment]
잘 됩니다.  감사합니다!
