### ISSUE TITLE
혹시 adguard필터로 광고있던자리 공백도 메울수 있나요?

### ISSUE THREAD

**Issue by cjh980402** [SlowMemory/List-KR#78]
dc갤러리에서 광고차단은 잘 되는데
공백이 크게 남아서 부탁드려봅니다.
http://m.dcinside.com/list.php?id=kimsohyun
+ 톱스타뉴스에서 광고차단 되고
data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAB4AAAAeCAMAAAAM7l6QAAAABGdBTUEAAK/INwWK6QAAABl0RVh0U29mdHdhcmUAQWRvYmUgSW1hZ2VSZWFkeXHJZTwAAAAYUExURaCgoFRUVObm5tXV1b6+vhISEv///wAAAG4mtYgAAAC7SURBVHjapJPbDsMgDEMTiNn///EozZVWaNLyBsYOOaWEYxE+h/pR5u0UOMs8OqprUMg8xmhJh8wNMvlSR/bL2iCV0ddS4MlXNbZwtHsDnjwLcbXsD28Mpvr0SwoKLJrfNZl3atZyHeInVPUXBJm59tdbPWXZzUX25v0lXFkVfmkwnbeVfJeNVeVvUINV8As5szJ+/kn0VsZKozrKc2g7P7Fwqqzu/gLvTeWpLV3yYMSvD/zvv+RYXwEGABQUFO8GQFs7AAAAAElFTkSuQmCC
라는 x자그림만 남는것도 차단되나요?

**Comment by SlowMemory** [comment]
제보 감사드립니다! 광고가 있던 공백을 차단하는 것 또한 필터의 목적 중 하나입니다. 필터를 업데이트 하시고 여전히 공백이 있다면 스크린샷을 첨부해주세요.

**Comment by cjh980402** [comment]
http://img1.daumcdn.net/thumb/R720x0.q80/?scode=mtistory&fname=http%3A%2F%2Fcfile24.uf.tistory.com%2Fimage%2F227D84395885AD5D0BC7A2
http://img1.daumcdn.net/thumb/R720x0.q80/?scode=mtistory&fname=http%3A%2F%2Fcfile1.uf.tistory.com%2Fimage%2F2247C8425885AD5E30B438
http://img1.daumcdn.net/thumb/R720x0.q80/?scode=mtistory&fname=http%3A%2F%2Fcfile29.uf.tistory.com%2Fimage%2F217525465885AD5F27671E
http://img1.daumcdn.net/thumb/R720x0.q80/?scode=mtistory&fname=http%3A%2F%2Fcfile21.uf.tistory.com%2Fimage%2F256BC3455885AD5F1E3FA5
http://img1.daumcdn.net/thumb/R720x0.q80/?scode=mtistory&fname=http%3A%2F%2Fcfile4.uf.tistory.com%2Fimage%2F236A6D415885AD600E2118
공백이 아직 있네요. x자도 있고

**Comment by cjh980402** [comment]
감사합니다!

**Comment by cjh980402** [comment]
http://m.dcinside.com/view.php?id=kimsohyun&no=45055&page=1
http://www.topstarnews.net/detail.php?number=237771
http://img1.daumcdn.net/thumb/R720x0.q80/?scode=mtistory&fname=http%3A%2F%2Fcfile6.uf.tistory.com%2Fimage%2F2155AE405885B224379655
http://img1.daumcdn.net/thumb/R720x0.q80/?scode=mtistory&fname=http%3A%2F%2Fcfile5.uf.tistory.com%2Fimage%2F2105DB455885B2222380FD
갤러리 메인은 됐습니다 감사합니다!
이 두군데도 부탁드리겠습니다

**Comment by SlowMemory** [comment]
필터 업데이트 후 확인 부탁드립니다 :)

**Comment by cjh980402** [comment]
항상 감사합니다.
잘 돼요ㅎㅎ

**Comment by cjh980402** [comment]
http://img1.daumcdn.net/thumb/R720x0.q80/?scode=mtistory&fname=http%3A%2F%2Fcfile26.uf.tistory.com%2Fimage%2F237FD2335887647B280B6D
http://m.dcinside.com/view.php?id=kimsohyun&no=45102&page=1
마지막으로 딱 한 군데만 더 부탁드릴게요! 
항상 업뎃 자주 해주셔서 감사합니다.
그리고 궁금한 점이 있는데 차단된다고 공백이 바로 메워지는 것이 아닌거죠?

**Comment by SlowMemory** [comment]
제보 감사합니다! 또 차단되지 않은 광고나 공백이 있으면 제보 부탁드립니다.

광고 이미지/플래시 자체는 광고를 받아오는 데 사용하는 서버를 차단하여 이루어집니다. 대부분 사이트에서 공통적인 서버를 사용하기 때문에 특별히 웹사이트마다 차단 규칙을 추가하지 않더라도 광고 자체는 대부분 차단됩니다.
하지만 웹사이트 측에서 광고가 로드될 공간을 미리 만들어놓고 그 자리에 광고를 로드하는 경우, 광고가 차단되더라도 빈 공간이 남게 됩니다. 이는 광고사 측에서 설정하는 것이 아닌 광고를 게시하는 웹사이트 측에서 설정하는 것이기 때문에 대부분 그 사이트만을 위한 규칙을 따로 추가해야 합니다

**Comment by cjh980402** [comment]
그렇군요.  감사드립니다:)
