### ISSUE TITLE
광고차단 회피 스크립트 적용중인 사이트

### ISSUE THREAD

**Issue by ohij** [SlowMemory/List-KR#79]
http://mongri.net/2876
http://jimnong.tistory.com/641
http://caskers.tistory.com/652
http://www.hangulogame.com/post/game/gc/459/
http://persnacons.tistory.com/807
http://www.airtravelinfo.kr/xe/air_sense_board/1050189

밑에 두개 사이트는 따로 경고문구는 나오지 않네요. adguard를 끄면  숨겨진 내용이 나옵니다.

**Comment by SlowMemory** [comment]
제보 감사드립니다. 말씀하신 사이트 관련 필터를 추가하였으니, 필터 업데이트 후 확인 부탁드립니다.

**Comment by ohij** [comment]
http://persnacons.tistory.com
위 사이트 다시 확인 부탁드립니다. 여전히 포스트를 누르면 본문이 안보입니다.

**Comment by SlowMemory** [comment]
확인 감사드립니다. 해당 사이트의 본문을 가리지 않도록 필터를 다시 추가하였습니다.
