### ISSUE TITLE
광고공백 제보합니다!

### ISSUE THREAD

**Issue by cjh980402** [SlowMemory/List-KR#80]
http://m.dcinside.com/list.php?serVal=ㅇㅇ&id=kimsohyun&s_type=all
검색창밑에 공백이 있습니다.

**Comment by SlowMemory** [comment]
제보 감사합니다! 필터 업데이트 후 확인 부탁드립니다.

**Comment by cjh980402** [comment]
항상 감사합니다ㅎㅎ
업데이트 하니
없어졌네요 바로ㄷㄷ
