### ISSUE TITLE
http://afreecatv.com/ 외

### ISSUE THREAD

**Issue by ohij** [SlowMemory/List-KR#82]
1. pc 브라우저로 afreecatv.com 에 들어가서 live방에 들어가면 소리가 나지 않고 채팅방 접속이 안되는 현상이 있습니다. 모바일앱은 정상입니다
2. 모바일 아프리카tv 앱을 실행하면 까만 화면에 로딩표시만 계속나오고 진행이 안됩니다. 홈키로 나갔다 들어오거나 전원버튼으로 화면을 껏다키면 해결은 됩니다. 까만화면이 원래 광고가 표시되는 화면인데 애드가드와 충돌이 되는것 같습니다.
3. http://est0que.tistory.com/3331
   http://whria.net/xe/index.php?mid=gomphoto
   http://prettygom.com/
광고차단방지 스크립트 적용중인 사이트입니다. 요즘 이런곳이 많이 보이던데 보일때마다 필터 추가하는 방법밖에 없나요? 일괄적용은 안되려나요?

**Comment by SlowMemory** [comment]
제보 감사드립니다!


1 - https://github.com/SlowMemory/List-KR/commit/5c05a6eb69a11623652294aa586f445e5eb50d91 에서 문제를 해결하도록 업데이트 하였으니 확인 부탁드립니다.
2 - 필터로 인한 것이 아니라 Adguard 앱 측의 버그인 듯 합니다. 현재 버그 제보를 한 상태입니다.
3 - 대부분의 경우, 광고 차단기에서 '요소 숨김' 만 예외 설정하시면 됩니다. 

Adguard 윈도우 버전의 Adguard 도우미를 사용하신다면, 아래와 같이 설정하시면 됩니다.
 - 도우미에서 '예외 추가' 클릭
 - 에외 규칙 범위를 '전체 도메인' 으로 설정
 - 고급 설정 클릭 - '요소 숨김 해제' 에만 체크, 나머지는 체크 해제

ublock origin을 사용하신다면 아래와 같이 설정하시면 됩니다.
 - 확장 프로그램 아이콘 클릭
 - 팝업창 맨 아래의 4개의 아이콘 중 눈 모양의 아이콘 (Toggle cosmetic filtering for this site) 클릭

광고차단을 감지하는 방식이 사이트마다 다른 탓에 일괄 적용하기는 어렵습니다. 다만 가장 많이 사용되는 fuckAdBlock 스크립트의 경우, 이를 무력화하는 규칙을 모든 사이트에 적용하더라도 큰 문제는 발생하지 않을 것 같습니다.
```
#%#(function(){var a={debug:{set:function(){return a}},on:function(b,c){b||setTimeout(function(){c()},1);return a},onDetected:function(b){return a.on(!0,b)},onNotDetected:function(b){return a.on(!1,b)},check:function(){}};Object.defineProperty(window,"fuckAdBlock",{get:function(){return a}})})();
```
을 사용자 필터에 추가하시면 됩니다.
