### ISSUE TITLE
m.ppomppu.co.kr 게시판 문제

### ISSUE THREAD

**Issue by akranrkso** [SlowMemory/List-KR#83]
안드로이드에서 사용중

m.ppomppu.co.kr##FORM + DIV[style^="padding-top"]

이 규칙이 적용되니 메인메뉴에서 검색후 나오는 결과물에서 게시판 넘김용 화살표가

사라집니다.

2. 윈도우, 익스플로러11 사용중

ppomppu.co.kr##div.ad

적용시에 뽐뿌사이트 전체 검색창에서 광고창이 깨져서 나옵니다.

**Comment by SlowMemory** [comment]
제보 감사드립니다. 말씀하신 문제를 해결하고 오래된 규칙을 일부 제거하였습니다.
차단되지 않은 광고나 다른 레이아웃 문제가 있다면 알려주시면 감사드리겠습니다.
