### ISSUE TITLE
tcafe.com 에서 광고차단이 작동하지 않는 문제

### ISSUE THREAD

**Issue by akranrkso** [SlowMemory/List-KR#84]
익스플로러 11버전에서  tcafe3.com, tcaferr.com에서 광고차단이 되지않는 문제가 있습니다.

**Comment by SlowMemory** [comment]
안녕하세요, tcafe 사이트 관련 규칙에 tcaferr.com도 추가하였습니다.
인터넷 익스플로러에서만 광고차단이 되지 않는 문제는 해당 웹사이트에서 `<META http-equiv=X-UA-Compatible content=IE=8>` 태그로 호환성 보기를 강제하고 있기 때문이며 Adguard에 버그 리포트를 열어두었습니다.

**Comment by SlowMemory** [comment]
임시로 호환성 보기를 강제하는 태그를 필터링하는 규칙을 추가하였습니다.
사용하는 브라우저에 상관 없이 같은 컨텐츠를 전송하는 것으로 보아 호환성 보기가 적용되지 않는 것으로 인한 큰 문제는 없을 것으로 판단했습니다. Adguard 업데이트에서 해당 버그가 고쳐지면 임시 규칙을 삭제할 예정입니다.
