### ISSUE TITLE
네이버 TV 캐스트에서 오류가 납니다.

### ISSUE THREAD

**Issue by khlee518** [SlowMemory/List-KR#86]
삼성 인터넷 브라우저 4.0.10.53 버전으로
네이버 TV캐스트 동영상을 재생하면
서버오류라는 이유로 동영상 재생이 안됩니다.
죄송하지만 혹시 확인해주실수 있을까요!
감사합니다!

**Comment by khlee518** [comment]
TV캐스트에 있는 모든 동영상이 다 재생안되는거 같습니다!

**Comment by SlowMemory** [comment]
안녕하세요, List-KR 필터를 컨텐츠 차단기를 통해 사용하고 계신가요? 어떤 앱을 사용하고 계신지 이름과 버전을 알려주시면 감사드리겠습니다.

**Comment by khlee518** [comment]
필터 업데이트후 해결되었네요!
감사합니다.^^
