### ISSUE TITLE
네이버 카페에서 공지를 차단할 수 있을까요?

### ISSUE THREAD

**Issue by okmoon** [SlowMemory/List-KR#87]
카페를 들어가보면 게시판 화면의 반 정도를 공지로 해놓은 카페를 많이 보게 되는데
이런 공지를 일괄 제거할 수 있는 필터링 규칙이 있는지 궁금합니다

**Comment by SlowMemory** [comment]
```
cafe.naver.com###cafe-intro
```
이 규칙을 한번 사용해 보세요.

원하시는 용도에 맞지 않는다면, 사이트 스크린샷을 통해 차단하고자 하시는 요소를 표시해주시면 도움이 될 듯합니다.

**Comment by okmoon** [comment]
![a](https://cloud.githubusercontent.com/assets/19366475/24099447/a7bca912-0db2-11e7-9464-5bf020f40abf.png)
![b](https://cloud.githubusercontent.com/assets/19366475/24099448/a7c23e4a-0db2-11e7-90e7-87826165a4b2.png)
답변해주셔서 감사합니다
답변해주신 필터링 규칙을 적용해보았으나 공지와 관련된 규칙이 아닌 것 같습니다
선택 자체가 불가능해서 따로 규칙을 적용해줘야 할 것 같은데 어떻게 해야 할지 모르겠습니다
예시 스크린샷으로 첨부한 곳은 중고나라입니다 (cafe.naver.com/joonggonara)
검색하여 클리앙에서 tr 규칙 적용법을 보았으나, tr:has는 각 카페마다 공지 규칙이 다르므로 공지를 일일히 다 등록해줘야 하는 번거로움이 있습니다
이미 하나하나 등록은 했습니다만 꼭 이런 방법이어야 할까란 궁금증 때문에요 공지 수십개를 복사-붙여넣기 해서 규칙에 추가하고, 공지가 추가되면 또 작업해줘야 하니까요
말머리에 붙은 공지 아이콘을 인식하여 차단해 버릴 수는 없을까요?

**Comment by SlowMemory** [comment]
공지 아이콘은 ico-list-notice 클래스를 가진 img 태그이므로 `cafe.naver.com##.board-box > tbody > tr:has(.ico-list-notice)`를 적용하시면 될 듯합니다.

그런데 네이버 게시판의 경우에는 공지 게시글의 tr 요소에 _noticeArticle 클래스와 bg-color가 있어서, `cafe.naver.com##.board-box > tbody > tr.bg-color` 또는 `cafe.naver.com##.board-box > tbody > tr._noticeArticle` 를 이용하셔도 비슷한 결과를 얻으실 수 있으며, 이 규칙이 :has를 사용하지 않아 더 빠릅니다.

**Comment by okmoon** [comment]
적용해보니 정말 깔끔해졌습니다
카페 여러군데 들어갈 때마다 화면 한가득 가리는 공지 때문에 스크롤을 여러번 내려줘야 했는데
덕분에 훨씬 쾌적한 웹서핑이 되었습니다
진심으로 감사드립니다!
