### ISSUE TITLE
특정 사이트를 검색에서도 뜨지않게 하는 규칙같은 게 있나요?

### ISSUE THREAD

**Issue by cjh980402** [SlowMemory/List-KR#88]
사용자 필터에 개인적으로 넣고 싶은데 방법을 모르네요...

**Comment by SlowMemory** [comment]
하나의 규칙으로 모든 검색엔진에서 적용하기는 어렵고, 검색엔진 사이트에 따라 규칙을 만들어서 차단할 수 있습니다.

모바일 구글, 네이버의 경우에는 http://clien.net/cs2/bbs/board.php?bo_table=cm_andro&wr_id=384576 이곳에 제가 남긴 댓글을 참조하세요. 그 외 필요하신 검색엔진이 있으시다면 한번 규칙을 만들어 보겠습니다.

검색 결과 키워드 필터링을 위한 확장 프로그램이나 유저스크립트가 있을 법 한데.. 구글의 경우에는 검색해보니
https://chrome.google.com/webstore/detail/personal-blocklist-by-goo/nolijncfnkgaikbjbdaogikpmpbdcdef?hl=en
https://chrome.google.com/webstore/detail/customblocker/elnfhbjabfcepfnaeoehffgmifcfjlha?hl=en
등이 나오네요. 검색 결과 중 특정 도메인이 안 나오게 할 수 있다고 합니다.
