### ISSUE TITLE
sitetrans.naver.net 사이트 접속이 안됩니다.

### ISSUE THREAD

**Issue by 1k2k3k** [SlowMemory/List-KR#89]
애드가드 버전 6.1.314.1628
엣지,크롬에서 사용 중
사용중인 필터
영어
러시아
일본
easylist china
list-kr
스파이웨어
소셜미디어
사용자필터

오전에 접속되다가 갑자기 접속이 안되네요.
접속을 하면 아래 링크와 같이 뜹니다. 
https://goo.gl/aowz6W

**Comment by SlowMemory** [comment]
안녕하세요, 해당 화면은 광고 차단 필터가 아니라 브라우징 보안 모듈에서 차단할 때 나타나는 화면입니다.
이를 확인하려면, 브라우징 보안을 잠시 사용 해제하시고 접속이 잘 되는지 확인해보세요. 

우선 현재는 접속이 잘 되는 듯 합니다. 브라우징 보안 모듈에 의해 차단된 경우('위험할 수 있습니다' 메세지가 표시)  프로그램의 "고객 지원" 버튼을 누르셔서 페이지가 잘못 차단되었다고 피드백을 보내 주시면 됩니다.
