### ISSUE TITLE
카카오톡 PC버전 광고차단

### ISSUE THREAD

**Issue by ian0371** [SlowMemory/List-KR#90]
카카오톡 PC버전을 실행하면 기본적으로 최하단에 광고가 포함되어있고, 로그인 할 때 팝업 광고가 뜹니다.
이를 차단할 수 있을까요?

![tmp](https://cloud.githubusercontent.com/assets/7467216/24111545/1d644f36-0dda-11e7-81a6-2dbf9e2dc84e.png)

**Comment by SlowMemory** [comment]
Adguard 윈도우 버전에서는, 카카오톡 pc버전의 실행파일을 필터링하도록 등록하시면 됩니다.
그러나 이 경우 광고가 나타나는 자리에 디폴트로 다음 뉴스 배너 이미지가 뜨게 됩니다. 이 배너는 카카오톡 설치 파일에 포함된 이미지로 Adguard로는 차단할 수 없습니다.

http://real21c.com/kakao-noadv/ 를 적용하시면 광고 영역까지 없어지던 것으로 기억합니다. 이쪽을 시도해보시는 것도 좋을 것 같습니다.

**Comment by ian0371** [comment]
아하 application을 따로 등록해야하는 것이었군요!
감사합니다 :)
