### ISSUE TITLE
DC inside 광고 규칙 추가 요청합니다. 

### ISSUE THREAD

**Issue by bradly1** [SlowMemory/List-KR#91]
gall.dcinside.com###dgn_gallery_left > DIV.ad_esmplus

몇몇 갤러리에서 게시글 검색시에 저 광고배너가 떠서요.. 
추가 부탁드립니다.

**Comment by SlowMemory** [comment]
안녕하세요, 광고 배너가 나타나는 정확한 URL을 알려주시면 감사드리겠습니다.

**Comment by bradly1** [comment]
http://gall.dcinside.com/board/lists/?id=pridepc_new3&s_type=search_all&s_keyword=%EC%A0%9C%EC%A3%BC

제가 확인했던 페이지는 여기입니다

**Comment by SlowMemory** [comment]
감사합니다. https://github.com/SlowMemory/List-KR/commit/7b030340bbe9f70650ce72c313c0deec0dd4f16e 에서 해당 광고 배너를 차단하도록 업데이트 하였습니다.
