### ISSUE TITLE
네이트 웹사이트에서 비어있는 부분 안보이게 할수 없나요? 

### ISSUE THREAD

**Issue by bradly1** [SlowMemory/List-KR#92]
adguard 윈도우용을 사용중입니다. 
네이트 페이지를 접속하면, 광고가 있던 자리가 비어있는데, 이 부분 삭제가 안되나 해서 문의를 드립니다. 

![default](https://cloud.githubusercontent.com/assets/6886994/24144033/1f0bb352-0e6f-11e7-9346-9c7d80bccbf2.png)

![3](https://cloud.githubusercontent.com/assets/6886994/24146676/123c485c-0e7a-11e7-9363-de3c765d4690.png)

![4](https://cloud.githubusercontent.com/assets/6886994/24146677/129d7500-0e7a-11e7-9cd2-d1789c58b404.png)

Firefox 를 사용중입니다.

**Comment by bradly1** [comment]
또한, adguard android 사용중에도 m.nate.com 을 접속하면 이전 광고자리가 빈 페이지로 남아있습니다..

**Comment by SlowMemory** [comment]
없앨 수 있습니다. 하지만 없애기 위해선 단순히 광고 요소를 숨기는 것이 아니라 광고가 아닌 요소의 위치를 바꾸는 CSS를 삽입해야 합니다. 즉 네이트 측에서 사이트 레이아웃을 지정해놓은 CSS를 덮어써야 합니다.

광고 차단을 넘어서 본인의 주관이 들어간 CSS를 삽입하여 포털의 메인 화면을 변형하는 것은 본 필터의 범위를 넘어선다고 생각되어 일반적으로 시도하지 않으나,

다음 홈페이지도 비슷한 문제가 있으며 이 경우 CSS 수정을 하지 않으면 미관상 좋지 않아 몇 가지 규칙을 적용하고 있습니다.
네이트 홈페이지의 경우에도 고려해 보겠습니다.

다음 규칙을 사용자 필터에 직접 추가하시면 빈 공간을 없앨 수 있습니다.

```
www.nate.com#$#body > #mainContainer > #container > #content > #shopping.area_shopping { top:290px!important; }
www.nate.com#$#body > #mainContainer > #container > #content > .area_ranking { top: 825px!important; }
www.nate.com#$#body > #mainContainer > #container > #footer { margin-top:20px!important; }
www.nate.com#$#body > #mainContainer > #container > #header { margin-bottom:0px!important; }
```

사용해보시고 네이트 홈페이지에 문제가 발생한다면 제보해주시면 감사드리겠습니다. 저도 어느 정도 사용해보고 필터에 추가할지 결정하려 합니다.

**Comment by bradly1** [comment]
문제 없습니다~~
