### ISSUE TITLE
네이버 라이트홈에서 반응이 느립니다.

### ISSUE THREAD

**Issue by janghayuun** [SlowMemory/List-KR#93]
삼성인터넷베타 5.4.00-15
삼성인터넷 4.2.20-28
adguard context blocker 1.6.3
라이트홈에서 뉴스 클릭 후 5초 정도 후에 로딩이 시작됩니다. 라이트홈이 적용되지 않는 검색은 바로바로됩니다.
새 탭에서 열거나 list-kr을 제거했을 때에는 바로 뜹니다.

**Comment by SlowMemory** [comment]
안녕하세요, 필터를 import 하실 때
```
https://github.com/SlowMemory/List-KR/raw/master/unbreak.txt 
```
도 import 하여 사용해 주세요.

**Comment by janghayuun** [comment]
필터쪽만 보다보니 user filter가 있는지 몰라ㅛ네요. 감사합니다
