### ISSUE TITLE
모바일 네이버 메인 광고배너는 어떻게 지우나요?

### ISSUE THREAD

**Issue by yangjh815** [SlowMemory/List-KR#95]
네이버 모바일 페이지에서 뜨는 배너광고 2개 중에 아래쪽은 차단되는데 위쪽 광고는 계속 떠있어서요
사용자규칙에서 mv.ad.naver.com 추가해도 그대로고..
제 생각에는 https문제 같기도 해요
adguard에서 https인증서 깔고 사용하도록 해놨지만 다른 어떤 사이트에서 차단 안 되던 것들이 http도메인으로 접속하면 차단이 완벽하더라구요
규칙의 문제인지 네이버의 https 보안이 막강한 문젠지는 모르겠지만..ㅠㅠ 혹시 방법을 아신다면 부탁드려요

**Comment by yangjh815** [comment]
배너 주소 남겨요
https://mv.ad.naver.com/fxclick?eu=EU10000002&ac=7512863&src=3093809&br=2467581&evtcd=P901&x_ti=798&tb=NEWS_1&rk=WNpcKQpjaWoAAKsAyJUAAAVn&eltts=xyj4cQgFTiA1ZTmWN0SA2A%3D%3D&lu=

**Comment by SlowMemory** [comment]
안녕하세요, 제 기기에서는 광고가 나타나지 않아 정확히 어떤 광고를 말씀하시는 것인지 알기 어렵습니다.
광고가 나타나는 페이지의 정확한 주소와, 광고가 나타날 때의 화면을 캡쳐하여 올려 주시면 감사하겠습니다.

올려주신 주소는 배너를 클릭했을 때의 연결되는 주소입니다. 배너를 차단하기 위해선 배너 이미지의 주소를 알아야 합니다. 
>다른 어떤 사이트에서 차단 안 되던 것들이 http도메인으로 접속하면 차단이 완벽

이 또한 나타나선 안되는 현상입니다. 어떤 사이트에서 이러한 현상을 경험하셨는지 알려주시면 확인해 보겠습니다.

**Comment by yangjh815** [comment]
http에선 차단 되고 https에선 다 뜨는 건 tcafe4.com 입니다
네이버는 http 로 접속이 안되서 확인 못해봤네요
제가 쓰는 브라우저는 삼성인터넷 베타 5.4.00-15 와 http://m.blog.naver.com/madzun/220866544354 이 주소의 브라우저를 씁니다
광고가 뜨는 곳은 네이버메인(https://m.naver.com)이고 위의 배너주소는 해당 배너광고를 길게 눌러서 링크복사를 한 거예요
배너이미지의 주소는 어떻게 따나요?

스샷은 첨부방법을 몰라서 구글드라이브 업로드한 부소를 남겨요
https://drive.google.com/open?id=0B7TqoIVxEIDca0VCZnpCLUFkVXM&authuser=0

**Comment by SlowMemory** [comment]
https://tcafe4.com 에서 광고차단이 잘 됩니다.
글쓴님께서 겪고 계신 증상은 앱의 버그 또는 앱의 설정 문제로 추정됩니다.
[이 링크](https://github.com/SlowMemory/List-KR/wiki/Adguard-%EC%95%88%EB%93%9C%EB%A1%9C%EC%9D%B4%EB%93%9C-%EB%B2%84%EC%A0%84%EC%9D%98-%EB%A1%9C%EA%B7%B8%EB%A5%BC-%EC%96%BB%EB%8A%94-%EB%B2%95) 를 참조하셔서 광고가 차단되지 않는 페이지를 방문하시고 full log를 보내주시면 감사드리겠습니다.
