### ISSUE TITLE
Gom TV 광고차단이 에러나는것 같습니다

### ISSUE THREAD

**Issue by bradly1** [SlowMemory/List-KR#96]
동영상 자체가 재생이 안되네요..
http://m.gomtv.com/14706701

Android용 사용하고 있습니다.
확인좀 해주시면 감사하겠습니다

**Comment by bradly1** [comment]
Adguard Android 사용하고 있습니다

**Comment by SlowMemory** [comment]
제보 감사합니다. 필터 업데이트 후 여전히 문제가 발생하면 알려주세요.

**Comment by bradly1** [comment]
문제 없습니다.
사용중 문제 발생하면 다시 issue open 하겠습니다.
