### ISSUE TITLE
일부 인앱 광고 차단과 관련하여 질문드립니다.

### ISSUE THREAD

**Issue by sigle4u** [SlowMemory/List-KR#97]
안드로이드 앱은 2.8정식 버전이고 현재 최신 필터로 업데이트 되어있습니다.
LG G6 SKT 누가 7.0이구요.

저같은 경우 특정 앱만 광고를 차단하고 대부분의 앱이나 서비스는 풀어버리는 방식으로 Adguard를 쓰고 있습니다.

클리앙이나 나무위키에 나오는 ipv6 관련 설정이나 포트 설정을 한 상태이며 아래 문제는 wifi, lte 가리지 않고 공통적으로 나타나고 있습니다.

구글 관련 서비스 중에서
계정 관리자
Google Play 서비스
Google 백업 전송
Google Services Framwork

이렇게는 무조건 체크가 되어야지 전체적으로 인앱 광고가 차단이 되더군요.
(google 백업 전송을 체크 해제하면 일부 앱은 차단이 되고 일부 앱은 차단이 되지 않습니다.)

문제는 Google 백업 전송을 체크하면 특정 앱 (T인증 같은...)에서 푸시가 안 옵니다.
Google 백업 전송을 체크하고 T인증을 체크 해제를 하여도 푸시가 오지 않습니다.

다른 문자나 카톡 같은 건 정상적으로 수신하여서 관련 문제가 있는지 한참 몰랐네요.

Google 백업 전송 체크 해제를 하면 푸시는 잘 오는데 인앱 광고가 나옵니다. 
ex: 아리 키우기, 편한 가게부 (편한 가계부는 설정 -> 설정관리에 들어가면 하단에 광고가 있습니다.)

**Comment by SlowMemory** [comment]
안녕하세요, 관련 문제를 여러 번 제보받았으나 제 측에서 재현이 잘 안 됩니다.
푸시가 안 오는 사례를 단계별로 더 자세히 설명해주실 있으신가요?
어떤 앱을 설치해서, 어떤 순서로 어떤 동작을 수행했을 때 푸시가 와야 하는 데 Adguard 실행 시 푸시가 안 오는지 설명해주시면 감사드리겠습니다.

**Comment by sigle4u** [comment]
최근 업데이트 이후 Google 백업 전송을 체크 해제 하더라도 정상적으로 광고가 차단되고 있습니다.
혹여 나중을 위해 제 세팅값을 남겨봅니다.

저같은 경우 나무위키나 클리앙을 참조하여 세팅을 하였고 인앱광고를 차단하고 싶은 앱이나 체크하지 않으면 광고가 나오는 서비스를 제외하고는 모두 체크 해제를 했습니다.

고급 설정 -> 로우 레벨 설정
pref.splash.enabled
pref.vpn.disable.pause
pref.vpn.ipv6.disable
체크되어 있고 pref.filtered.ports에서 클리앙 등에 올려진 포트 번호를 추가하였습니다.

앱관리에서 체크되어 있는 부분
광고를 차단하고 싶은 개별 앱들 (예를 들어 크롬, 아리키우기, 편한가계부는 체크되어 있고 T인증은 체크 해제되어 있습니다.)
Google Play 서비스
Google Services Framework
Google 계정 관리자

특히 Google Play 서비스, Google Services Framework, Google 계정 관리자는 체크가 되어 있지 않으면 앱에서 광고가 나오더군요. 

이렇게 체크되어 있고 나머지는 모두 체크 해제를 하였습니다.
(광고가 나오지 않는 앱 혹은 체크 해제를 해도 광고가 안나오는 서비스 등)

HTTPS 필터링 인증서 설치하고 필터링 사용 중이구요.

이런 상황에서
Google 백업 전송을 체크하면 일부 앱 (T인증, 빠삭 스노방)에서 푸쉬가 안 들어오는 증상이 있습니다.
두 앱의 특징은 화면 중앙에 풍선 알람을 띄우더군요.
(카톡, 네이버 카페 등 대부분의 헤드업 알람 앱들은 푸쉬가 잘 들어옵니다.)

이전에는 Google 백업 전송을 체크하지 않으면 일부 앱 (아리키우기, 편한 가계부 등)에서 광고가 나오는 증상이 있었으나 최근 업데이트 이후 Google 백업 전송 체크와 관계없이 인앱광고가 차단되고 있어 일부 앱에서 푸쉬도 정상적으로 받고 있습니다.


T인증 같은 경우 각종 사이트 가입이나 본인인증을 위해 간편본인인증을 하였을 때 핸드폰 화면 가운데 본인인증 확인 팝업을 띄웁니다.
그거를 클릭하고 들어가서 비밀번호를 누르면 인증이 되는 방식이구요.

Google 백업 전송 체크 등으로 정상적으로 팝업을 받지 못하는 경우 간편본인인증을 하게 되면 화면 중앙에 띄우는 팝업은 없고 T인증 앱을 실행시켜 앱 실행 비밀번호를 1회 넣고 다시 본인인증 비밀번호를 1회 더 넣어 결국 2회의 비밀번호 입력을 요구합니다.

**Comment by SlowMemory** [comment]
제가 SKT를 사용하지 않아 T인증 앱을 실제로 사용해볼 수 없습니다.

T인증 말고 푸시가 안 들어오는 다른 앱은 없으신가요? 빠삭 스노방 앱을 언급하셨는데, 그 앱에서 마찬가지로 어떤 순서로 어떤 동작을 수행했을 때 푸시가 안 들어오는 것을 확인할 수 있는지를 알려주실 수 있으신가요?

또는 T인증 앱을 사용하시며 로그를 작성하셔서 보내주시면 도움이 될 것 같습니다. 로그는 https://github.com/SlowMemory/List-KR/wiki/Adguard-%EC%95%88%EB%93%9C%EB%A1%9C%EC%9D%B4%EB%93%9C-%EB%B2%84%EC%A0%84%EC%9D%98-%EB%A1%9C%EA%B7%B8%EB%A5%BC-%EC%96%BB%EB%8A%94-%EB%B2%95 를 통해 추출하시면 됩니다.

로깅 레벨을 '모두 기록'으로 설정한 상태에서, 간편본인인증을 한번 시도하시고 팝업이 안 뜨는 것을 확인한 뒤 로그를 보내주시면 될 것 같습니다.
