### ISSUE TITLE
모바일 사용자 필터 규칙 적용에 관한 문의

### ISSUE THREAD

**Issue by okmoon** [SlowMemory/List-KR#98]
![1](https://cloud.githubusercontent.com/assets/19366475/24804355/25bdc802-1be9-11e7-9e01-9438d6448a07.png)
![2](https://cloud.githubusercontent.com/assets/19366475/24804356/25bffcf8-1be9-11e7-853e-ba80bdded390.png)

http://theqoo.net/square?filter_mode=normal
이 사이트의 모바일 버전 공지를 차단하려고 합니다
뉴스 보러 자주 들어가는 사이트인데 공지가 화면을 너무 가려서요
theqoo.net###container > DIV.content > SECTION.flatBoard > DIV.m-list.m-element > UL.notice-list.on.hide_notice
PC에서는 필터를 추가한 후 모바일 페이지를 띄우면 첨부한 사진과 같이 잘 차단이 되는데
(네이버 웨일 사이드바를 이용하여 모바일 페이지 테스트를 했습니다)
안드로이드 애드가드 사용자 필터에 동일한 규칙을 추가한 후 들어가보면 공지 차단이 되지 않습니다
모바일 애드가드 사용자 필터는 저런 식의 규칙이 적용이 안 되는건지 궁금합니다
안드로이드 브라우저는 삼성 브라우저 베타 사용중입니다

그리고 게시물을 클릭하면 광고가 뜨는데
theqoo.net###adTopChange 이건 모바일 역시 정상 작동합니다

**Comment by SlowMemory** [comment]
제보 감사합니다. 게시물 상단 광고를 차단하도록 업데이트 하였습니다.
사이트의 공지는, 제 기기에서는 말씀하신 규칙
`theqoo.net###container > DIV.content > SECTION.flatBoard > DIV.m-list.m-element > UL.notice-list.on.hide_notice` 를 추가하면 차단이 잘 됩니다.
글쓴님께서 테스트하실 때 브라우저의 캐시로 인해 규칙이 적용되지 않았거나, 데스크탑 브라우저와 모바일 브라우저에 웹사이트 측에서 다른 페이지를 보여준 것이 원인일 수 있습니다.
또 위 규칙은 공지 요소를 선택하기 위한 조건이 불필요하게 많습니다. `theqoo.net##.m-list > .notice-list` 만으로도 충분하리라 생각합니다.
브라우저의 캐시를 삭제하시고 `theqoo.net##.m-list > .notice-list` 를 추가하시고 다시 테스트해보시기를 권합니다.

**Comment by okmoon** [comment]
캐시 삭제 후 말씀하신 규칙으로 등록했더니 모바일 페이지에서도 공지 없이 쾌적한 화면을 볼 수 있네요!
프로그래밍이나 웹 언어를 하나도 모르는지라 규칙 만드는 게 어려워서 여러개의 공지를 선택 후 중복되는 부분을 찾아서 등록하는 방식으로 했더니 규칙이 쓸데없이 길어지네요
느린기억님 아니었으면 진짜 답답한 웹서핑을 하고 있었을 겁니다
정말 정말 감사합니다
