### ISSUE TITLE
인앱 광고 차단 문의..

### ISSUE THREAD

**Issue by bradly1** [SlowMemory/List-KR#99]
고속버스 모바일 이라는 안드로이드 어플이 있는데 이 어플에 뜨는 광고를 adguard 안드로이드 버전이 차단을 하지 못합니다. 패킷을 분석해서 차단하는데, 혹시 다른 룰이 있다면 좀 요청을 드릴까 해서 issue 를 남깁니다..

https://gist.github.com/bradly1/b62cddba02c738ca5592c09c0c0af752

저는 해당 패킷에서 tube-box.co.kr/* 라는 규칙을 넣어놨는데.. 다른 최적화하는 룰이 있다면 알려주시기 바랍니다..

**Comment by bradly1** [comment]
참고로, app상에서 GET /smartcard/banner1 HTTP/1.1 이 부분이 호출됩니다

**Comment by SlowMemory** [comment]
제보 감사합니다. 위 업데이트에서 해당 광고를 차단하도록 업데이트하였습니다.
